import { supabase } from "@/lib/supabase/client";
import { readPedagogicalLocalFirst, type PedagogicalCacheContext } from "@/lib/offline/pedagogical-cache";
import { beginLocalLearningAttempt, submitLocalLearningAttempt } from "@/lib/offline/learning-sync-store";
import { isInternetReachable } from "@/lib/offline/learning-sync-manager";
import { QuizAttemptStatus, QuizDifficulty, QuizQuestionType } from "./quiz-model";

export * from "./quiz-model";

export type QuizOption = { id: string; answer: string };
export type QuizQuestion = { id: string; promptMarkdown: string; questionType: QuizQuestionType; points: number; options: QuizOption[] };
export type QuizCatalogItem = { quizId: string; title: string; description: string | null; subjectId: string; subjectName: string; chapterId: string; chapterTitle: string; lessonId: string; lessonTitle: string; difficulty: QuizDifficulty | null; durationMinutes: number | null; questionCount: number; displayOrder: number; attemptCount: number; lastStatus: QuizAttemptStatus | null; lastPercentage: number | null; bestPercentage: number | null };
export type QuizDetail = { quizId: string; title: string; description: string | null; subjectName: string; chapterTitle: string; lessonTitle: string; difficulty: QuizDifficulty | null; durationMinutes: number | null; questions: QuizQuestion[]; contentVersion: string | null };
export type QuizAttempt = { attemptId: string; quizId: string; status: QuizAttemptStatus; startedAt: string; durationMinutes: number | null; score?: number; percentage?: number | null; totalQuestions?: number; correctAnswers?: number; incorrectAnswers?: number; submittedAt?: string | null; durationSeconds?: number | null; reviewRequired?: boolean };
export type QuizResult = QuizAttempt & { title: string; questions: Array<QuizQuestion & { answer: unknown; isCorrect: boolean | null; correctOptionIds: string[]; explanationMarkdown: string | null }> };
export type QuizHistoryItem = { attemptId: string; quizId: string; title: string; status: QuizAttemptStatus; score: number; percentage: number | null; startedAt: string; submittedAt: string | null; bestPercentage: number | null; attemptCount: number };

type RpcRow = Record<string, unknown>;
const message = (error: unknown) => typeof error === "object" && error && "message" in error && typeof error.message === "string" ? error.message : "Une erreur Supabase est survenue.";
const numeric = (value: unknown) => { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; };
const nullableNumeric = (value: unknown) => value === null || value === undefined ? null : numeric(value);
const one = (data: unknown) => Array.isArray(data) ? data[0] as RpcRow | undefined : data as RpcRow | null;
const options = (value: unknown): QuizOption[] => Array.isArray(value) ? value.map((item: any) => ({ id: String(item.id), answer: String(item.answer) })) : [];
const stringArray = (value: unknown) => Array.isArray(value) ? value.map(String) : [];
async function currentUserId() { const { data, error } = await supabase.auth.getSession(); if (error || !data.session?.user) throw new Error("Connexion requise pour enregistrer cette tentative."); return data.session.user.id; }

function questionFrom(value: any): QuizQuestion { return { id: String(value.id), promptMarkdown: String(value.prompt_markdown ?? ""), questionType: value.question_type as QuizQuestionType, points: numeric(value.points) || 1, options: options(value.options) }; }
function attemptFrom(row: RpcRow): QuizAttempt { return { attemptId: String(row.attempt_id), quizId: String(row.quiz_id), status: row.status as QuizAttemptStatus, startedAt: String(row.started_at), durationMinutes: nullableNumeric(row.duration_minutes), score: row.score === undefined ? undefined : numeric(row.score), percentage: nullableNumeric(row.percentage), totalQuestions: row.total_questions === undefined ? undefined : numeric(row.total_questions), correctAnswers: row.correct_answers === undefined ? undefined : numeric(row.correct_answers), incorrectAnswers: row.incorrect_answers === undefined ? undefined : numeric(row.incorrect_answers), submittedAt: row.submitted_at as string | null ?? null, durationSeconds: row.duration_seconds === undefined ? undefined : nullableNumeric(row.duration_seconds), reviewRequired: Boolean(row.review_required) }; }

export type QuizCatalogFilters = { subjectId?: string | null; chapterId?: string | null; lessonId?: string | null; difficulty?: QuizDifficulty | null; cacheContext?: PedagogicalCacheContext | null };

export async function getQuizCatalog(filters: QuizCatalogFilters = {}): Promise<QuizCatalogItem[]> {
  const resource = `quizzes/catalog/${filterKey(filters.subjectId, filters.chapterId, filters.lessonId, filters.difficulty)}`;
  return readPedagogicalLocalFirst(filters.cacheContext, resource, async () => {
    const { data, error } = await supabase.rpc("get_my_quiz_catalog", { p_subject_id: filters.subjectId ?? null, p_chapter_id: filters.chapterId ?? null, p_lesson_id: filters.lessonId ?? null, p_difficulty: filters.difficulty ?? null });
    if (error) throw new Error(message(error));
    return (data ?? []).map((row: any) => ({ quizId: String(row.quiz_id), title: String(row.title), description: row.description ?? null, subjectId: String(row.subject_id), subjectName: String(row.subject_name), chapterId: String(row.chapter_id), chapterTitle: String(row.chapter_title), lessonId: String(row.lesson_id), lessonTitle: String(row.lesson_title), difficulty: row.difficulty as QuizDifficulty | null, durationMinutes: nullableNumeric(row.duration_minutes), questionCount: numeric(row.question_count), displayOrder: numeric(row.display_order), attemptCount: numeric(row.attempt_count), lastStatus: row.last_status as QuizAttemptStatus | null, lastPercentage: nullableNumeric(row.last_percentage), bestPercentage: nullableNumeric(row.best_percentage) }));
  });
}

export async function getQuizDetail(quizId: string, cacheContext?: PedagogicalCacheContext | null): Promise<QuizDetail | null> { return readPedagogicalLocalFirst(cacheContext, `quiz/${encodeURIComponent(quizId)}`, async () => { const { data, error } = await supabase.rpc("get_my_quiz_detail", { p_quiz_id: quizId }); if (error) throw new Error(message(error)); const row = one(data); if (!row) return null; const { data: version, error: versionError } = await supabase.rpc("get_my_quiz_content_version", { p_quiz_id: quizId }); if (versionError) throw new Error(message(versionError)); return { quizId: String(row.quiz_id), title: String(row.title), description: row.description as string | null ?? null, subjectName: String(row.subject_name), chapterTitle: String(row.chapter_title), lessonTitle: String(row.lesson_title), difficulty: row.difficulty as QuizDifficulty | null, durationMinutes: nullableNumeric(row.duration_minutes), contentVersion: version ? String(version) : null, questions: Array.isArray(row.questions) ? row.questions.map(questionFrom) : [] }; }); }
export async function startQuizAttempt(quizId: string, contentVersion: string | null) { if (await isInternetReachable()) { const { data, error } = await supabase.rpc("start_quiz_attempt", { p_quiz_id: quizId }); if (error) throw new Error(message(error)); const row = one(data); if (!row) throw new Error("La tentative n’a pas pu être créée."); return attemptFrom(row); } const local = await beginLocalLearningAttempt(await currentUserId(), "quiz", quizId, contentVersion); return { attemptId: local.id, quizId, status: "in_progress" as const, startedAt: local.startedAt, durationMinutes: null }; }
export async function submitQuizAttempt(attemptId: string, answers: Record<string, unknown>) { if (attemptId.startsWith("local-")) { const local = await submitLocalLearningAttempt(await currentUserId(), attemptId, answers); return { attemptId: local.id, quizId: local.resourceId, status: "submitted" as const, startedAt: local.startedAt, durationMinutes: null, submittedAt: local.submittedAt ?? undefined }; } const { data, error } = await supabase.rpc("submit_quiz_attempt", { p_attempt_id: attemptId, p_answers: answers }); if (error) throw new Error(message(error)); const row = one(data); if (!row) throw new Error("La soumission du quiz a échoué."); return attemptFrom(row); }
export async function getQuizResult(attemptId: string): Promise<QuizResult | null> { const { data, error } = await supabase.rpc("get_my_quiz_attempt_result", { p_attempt_id: attemptId }); if (error) throw new Error(message(error)); const row = one(data); if (!row) return null; const attempt = attemptFrom(row); return { ...attempt, title: String(row.title), questions: Array.isArray(row.questions) ? row.questions.map((question: any) => ({ ...questionFrom(question), answer: question.answer, isCorrect: typeof question.is_correct === "boolean" ? question.is_correct : null, correctOptionIds: stringArray(question.correct_option_ids), explanationMarkdown: question.explanation_markdown ?? null })) : [] }; }
export async function getMyQuizHistory(): Promise<QuizHistoryItem[]> { const { data, error } = await supabase.rpc("get_my_quiz_history"); if (error) throw new Error(message(error)); return (data ?? []).map((row: any) => ({ attemptId: String(row.attempt_id), quizId: String(row.quiz_id), title: String(row.title), status: row.status as QuizAttemptStatus, score: numeric(row.score), percentage: nullableNumeric(row.percentage), startedAt: String(row.started_at), submittedAt: row.submitted_at ?? null, bestPercentage: nullableNumeric(row.best_percentage), attemptCount: numeric(row.attempt_count) })); }

function filterKey(...values: Array<string | null | undefined>) { return values.map((value) => encodeURIComponent(value ?? "all")).join("/"); }
