REVOKE EXECUTE ON FUNCTION public.edutech_log_school_action(text,text,text,jsonb) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.edutech_touch_school_admin_updated_at() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.admin_create_school_year(text,date,date,text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_activate_school_year(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_close_school_year(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_archive_school_year(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.student_change_school_class(text,text,text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_review_class_change_request(uuid,boolean,text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_record_promotion_decision(uuid,uuid,text,text,text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.admin_set_student_account_status(uuid,boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_create_school_year(text,date,date,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_activate_school_year(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_close_school_year(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_archive_school_year(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.student_change_school_class(text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_review_class_change_request(uuid,boolean,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_record_promotion_decision(uuid,uuid,text,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_student_account_status(uuid,boolean) TO authenticated;
