import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { AppScreen } from "@/components/edutech/app-screen";
import { CourseEmpty, CourseError, CourseLoading, CourseRowIcon } from "@/components/edutech/course-feedback";
import { ProgressSummary } from "@/components/edutech/learning-progress";
import { PageHeader } from "@/components/edutech/page-header";
import { CourseChapter, CourseOffering, getChaptersForOffering, getCourseOffering } from "@/lib/courses/course-service";
import { useEduTheme } from "@/lib/edutech/theme-context";
import { pedagogicalCacheContextFromProfile } from "@/lib/offline/pedagogical-cache";
import { getLearningProgress, progressForChapter, progressForOffering, type LearningProgressDashboard } from "@/lib/progress/learning-progress-service";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";

const emptyDashboard: LearningProgressDashboard = { subjects: [], completedLessons: 0, totalLessons: 0, percentage: 0 };

export default function SubjectScreen() {
  const { offeringId } = useLocalSearchParams<{ offeringId: string }>(); const router = useRouter(); const { colors } = useEduTheme(); const { profile } = useSupabaseAuth(); const { id: profileId, school_level: schoolLevel, series: profileSeries, role: profileRole } = profile ?? {}; const cacheContext = useMemo(() => pedagogicalCacheContextFromProfile(profileId && schoolLevel && profileSeries && profileRole ? { id: profileId, school_level: schoolLevel, series: profileSeries, role: profileRole } : null), [profileId, schoolLevel, profileSeries, profileRole]);
  const [offering, setOffering] = useState<CourseOffering | null>(null); const [chapters, setChapters] = useState<CourseChapter[]>([]); const [dashboard, setDashboard] = useState<LearningProgressDashboard>(emptyDashboard); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const styles = useMemo(() => createStyles(colors), [colors]);
  const load = useCallback(async () => { if (!offeringId) return; setLoading(true); setError(null); try { const [nextOffering, nextChapters, progress] = await Promise.all([getCourseOffering(offeringId, { cacheContext }), getChaptersForOffering(offeringId, { cacheContext }), getLearningProgress()]); setOffering(nextOffering); setChapters(nextChapters); setDashboard(progress); } catch (cause) { setError(cause instanceof Error ? cause.message : "Une erreur inattendue est survenue."); } finally { setLoading(false); } }, [cacheContext, offeringId]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  if (loading) return <AppScreen><CourseLoading label="Chargement des chapitres" /></AppScreen>;
  if (error) return <AppScreen><CourseError message={error} onRetry={() => void load()} /></AppScreen>;
  if (!offering) return <AppScreen><CourseEmpty title="Matière indisponible" description="Cette matière n’est pas accessible avec votre profil scolaire actuel." /></AppScreen>;
  const subjectProgress = progressForOffering(dashboard, offering.id); const hasStarted = subjectProgress?.chapters.flatMap((chapter) => chapter.lessons).some((lesson) => lesson.status !== "not_started") ?? false;
  return <AppScreen withPadding={false}><FlatList data={chapters} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><PageHeader title={offering.subjectName} subtitle={offering.subjectDescription || "Chapitres disponibles pour votre parcours."} back />{subjectProgress?.totalLessons ? <View style={styles.overview}><ProgressSummary completed={subjectProgress.completedLessons} total={subjectProgress.totalLessons} percentage={subjectProgress.percentage} /><Pressable accessibilityRole="button" onPress={() => subjectProgress.resumeLessonId && router.push(`/course/lesson/${subjectProgress.resumeLessonId}`)} style={({ pressed }) => [styles.continueButton, pressed && styles.pressed]}><MaterialIcons name={hasStarted ? "play-arrow" : "play-circle-outline"} size={19} color={colors.surface} /><Text style={styles.continueLabel}>{hasStarted ? "Continuer le cours" : "Commencer"}</Text></Pressable></View> : <View style={styles.pending}><Text style={styles.pendingText}>Contenu à venir</Text></View>}<Text style={styles.section}>Chapitres</Text></View>} renderItem={({ item, index }) => { const chapterProgress = progressForChapter(dashboard, item.id); return <Pressable accessibilityRole="button" onPress={() => router.push(`/course/chapter/${item.id}`)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><CourseRowIcon index={index} /><View style={styles.copy}><Text style={styles.title}>{item.title}</Text><Text style={styles.description}>{item.description || "Ouvrir les leçons disponibles."}</Text>{chapterProgress?.totalLessons ? <ProgressSummary completed={chapterProgress.completedLessons} total={chapterProgress.totalLessons} percentage={chapterProgress.percentage} /> : <Text style={styles.pendingCard}>Contenu à venir</Text>}</View><MaterialIcons name="chevron-right" size={23} color={colors.muted} /></Pressable>; }} ListEmptyComponent={<CourseEmpty title="Aucun chapitre disponible" description="Les chapitres de cette matière seront ajoutés prochainement." />} /></AppScreen>;
}

const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 18, paddingBottom: 28, gap: 10 }, header: { marginBottom: 6 }, overview: { marginTop: 18, padding: 14, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 18 }, pending: { marginTop: 18, padding: 14, backgroundColor: colors.surfaceMuted, borderRadius: 16 }, pendingText: { color: colors.muted, fontSize: 13, fontWeight: "800" }, continueButton: { minHeight: 44, marginTop: 14, borderRadius: 13, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, paddingHorizontal: 14, backgroundColor: colors.primary }, continueLabel: { color: colors.surface, fontSize: 13, fontWeight: "900" }, section: { color: colors.text, fontSize: 16, lineHeight: 22, fontWeight: "800", marginTop: 24, marginBottom: 10 }, card: { minHeight: 74, padding: 14, flexDirection: "row", alignItems: "center", gap: 12, borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, pressed: { opacity: 0.72 }, copy: { flex: 1 }, title: { color: colors.text, fontSize: 16, lineHeight: 21, fontWeight: "800" }, description: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 3 }, pendingCard: { color: colors.muted, fontSize: 11, lineHeight: 15, fontWeight: "800", marginTop: 8 } });
