import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { CourseEmpty, CourseError, CourseLoading, CourseRowIcon } from "@/components/edutech/course-feedback";
import { PageHeader } from "@/components/edutech/page-header";
import { CourseChapter, CourseOffering, getChaptersForOffering, getCourseOffering } from "@/lib/courses/course-service";
import { useEduTheme } from "@/lib/edutech/theme-context";

export default function SubjectScreen() { const { offeringId } = useLocalSearchParams<{ offeringId: string }>(); const router = useRouter(); const { colors } = useEduTheme(); const [offering, setOffering] = useState<CourseOffering | null>(null); const [chapters, setChapters] = useState<CourseChapter[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const styles = useMemo(() => createStyles(colors), [colors]); const load = useCallback(async () => { if (!offeringId) return; setLoading(true); setError(null); try { const [nextOffering, nextChapters] = await Promise.all([getCourseOffering(offeringId), getChaptersForOffering(offeringId)]); setOffering(nextOffering); setChapters(nextChapters); } catch (cause) { setError(cause instanceof Error ? cause.message : "Une erreur inattendue est survenue."); } finally { setLoading(false); } }, [offeringId]); useEffect(() => { void load(); }, [load]); if (loading) return <AppScreen><CourseLoading label="Chargement des chapitres" /></AppScreen>; if (error) return <AppScreen><CourseError message={error} onRetry={() => void load()} /></AppScreen>; if (!offering) return <AppScreen><CourseEmpty title="Matière indisponible" description="Cette matière n’est pas accessible avec votre profil scolaire actuel." /></AppScreen>; return <AppScreen withPadding={false}><FlatList data={chapters} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><PageHeader title={offering.subjectName} subtitle={offering.subjectDescription || "Chapitres disponibles pour votre parcours."} back /><Text style={styles.section}>Chapitres</Text></View>} renderItem={({ item, index }) => <Pressable onPress={() => router.push(`/course/chapter/${item.id}`)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><CourseRowIcon index={index} /><View style={styles.copy}><Text style={styles.title}>{item.title}</Text><Text style={styles.description}>{item.description || "Ouvrir les leçons disponibles."}</Text></View><MaterialIcons name="chevron-right" size={23} color={colors.muted} /></Pressable>} ListEmptyComponent={<CourseEmpty title="Aucun chapitre disponible" description="Les chapitres de cette matière seront ajoutés prochainement." />} /></AppScreen>; }
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 18, paddingBottom: 28, gap: 10 }, header: { marginBottom: 6 }, section: { color: colors.text, fontSize: 16, lineHeight: 22, fontWeight: "800", marginTop: 24, marginBottom: 10 }, card: { minHeight: 74, padding: 14, flexDirection: "row", alignItems: "center", gap: 12, borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, pressed: { opacity: 0.72 }, copy: { flex: 1 }, title: { color: colors.text, fontSize: 16, lineHeight: 21, fontWeight: "800" }, description: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 3 } });
