import { describe, expect, it } from "vitest";
import { calculateSubjectAverage, calculateTermAverage, isValidSchoolYear, normalizedOutOfTwenty } from "../lib/bulletin/bulletin-model";

describe("modèle Bulletin", () => {
  it("calcule une moyenne de matière pondérée par les coefficients saisis pour les évaluations", () => { expect(calculateSubjectAverage([{ grade: 15, maxGrade: 20, assessmentCoefficient: 2, includeInAverage: true }, { grade: 12, maxGrade: 20, assessmentCoefficient: 1, includeInAverage: true }, { grade: 14, maxGrade: 20, assessmentCoefficient: 2, includeInAverage: true }])).toBe(14); expect(normalizedOutOfTwenty(24, 40)).toBe(12); });
  it("ne transforme jamais une matière sans note en zéro", () => { expect(calculateSubjectAverage([])).toBeNull(); expect(calculateSubjectAverage([{ grade: 10, maxGrade: 20, includeInAverage: false }])).toBeNull(); });
  it("applique la formule trimestrielle seulement aux coefficients vérifiés", () => { const result = calculateTermAverage([{ average: 10, coefficient: 2, coefficientVerified: true }, { average: 14, coefficient: 4, coefficientVerified: true }, { average: 19, coefficient: 5, coefficientVerified: false }, { average: null, coefficient: 3, coefficientVerified: true }]); expect(result.average).toBe(12.67); expect(result.includedSubjectCount).toBe(2); expect(result.excludedUnverifiedCoefficientCount).toBe(1); });
  it("applique ensuite les coefficients de matière A1 sans réutiliser les coefficients d’évaluation", () => { const result = calculateTermAverage([{ average: 14, coefficient: 4, coefficientVerified: true }, { average: 12, coefficient: 5, coefficientVerified: true }, { average: 10, coefficient: 4, coefficientVerified: true }, { average: 18, coefficient: null, coefficientVerified: false }]); expect(result.average).toBe(12); expect(result.includedSubjectCount).toBe(3); });
  it("conserve la validité d’une année scolaire consécutive", () => { expect(isValidSchoolYear("2026-2027")).toBe(true); expect(isValidSchoolYear("2026-2028")).toBe(false); });
});
