import { describe, expect, it } from "vitest";
import { calculateCoefficientMatrixTotal, calculateSubjectAverage, calculateTermAverage, isValidSchoolYear, normalizedOutOfTwenty } from "../lib/bulletin/bulletin-model";

describe("modèle Bulletin", () => {
  it("calcule une moyenne de matière pondérée par les coefficients saisis pour les évaluations", () => { expect(calculateSubjectAverage([{ grade: 15, maxGrade: 20, assessmentCoefficient: 2, includeInAverage: true }, { grade: 12, maxGrade: 20, assessmentCoefficient: 1, includeInAverage: true }, { grade: 14, maxGrade: 20, assessmentCoefficient: 2, includeInAverage: true }])).toBe(14); expect(normalizedOutOfTwenty(24, 40)).toBe(12); });
  it("ne transforme jamais une matière sans note en zéro", () => { expect(calculateSubjectAverage([])).toBeNull(); expect(calculateSubjectAverage([{ grade: 10, maxGrade: 20, includeInAverage: false }])).toBeNull(); });
  it("applique la formule trimestrielle seulement aux coefficients vérifiés", () => { const result = calculateTermAverage([{ average: 10, coefficient: 2, coefficientVerified: true }, { average: 14, coefficient: 4, coefficientVerified: true }, { average: 19, coefficient: 5, coefficientVerified: false }, { average: null, coefficient: 3, coefficientVerified: true }]); expect(result.average).toBe(12.67); expect(result.includedSubjectCount).toBe(2); expect(result.excludedUnverifiedCoefficientCount).toBe(1); });
  it("applique ensuite les coefficients de matière A1 sans réutiliser les coefficients d’évaluation", () => { const result = calculateTermAverage([{ average: 14, coefficient: 4, coefficientVerified: true }, { average: 12, coefficient: 5, coefficientVerified: true }, { average: 10, coefficient: 4, coefficientVerified: true }, { average: 18, coefficient: null, coefficientVerified: false }]); expect(result.average).toBe(12); expect(result.includedSubjectCount).toBe(3); });
  it("conserve la validité d’une année scolaire consécutive", () => { expect(isValidSchoolYear("2026-2027")).toBe(true); expect(isValidSchoolYear("2026-2028")).toBe(false); });
  it("calcule la moyenne Mathématiques Terminale C uniquement avec les coefficients d’évaluation", () => { expect(calculateSubjectAverage([{ grade: 15, maxGrade: 20, assessmentCoefficient: 2, includeInAverage: true }, { grade: 12, maxGrade: 20, assessmentCoefficient: 1, includeInAverage: true }])).toBe(14); });
  it("applique les coefficients Terminale C sans jamais utiliser ceux de Terminale D", () => { const result = calculateTermAverage([{ average: 14, coefficient: 5, coefficientVerified: true }, { average: 13, coefficient: 5, coefficientVerified: true }, { average: 12, coefficient: 2, coefficientVerified: true }, { average: 11, coefficient: 2, coefficientVerified: true }]); expect(result.average).toBe(12.93); expect(result.includedSubjectCount).toBe(4); });
  it("applique les coefficients Terminale D, dont Mathématiques 4, Physique-Chimie 4 et SVT 4", () => { const result = calculateTermAverage([{ average: 14, coefficient: 4, coefficientVerified: true }, { average: 13, coefficient: 4, coefficientVerified: true }, { average: 12, coefficient: 4, coefficientVerified: true }, { average: 11, coefficient: 3, coefficientVerified: true }, { average: 10, coefficient: 2, coefficientVerified: true }]); expect(result.average).toBe(12.29); expect(result.includedSubjectCount).toBe(5); });
  it("exclut une LV2 facultative non suivie et l’inclut uniquement lorsqu’elle possède une moyenne", () => { const withoutLv2 = calculateTermAverage([{ average: 14, coefficient: 5, coefficientVerified: true }, { average: null, coefficient: 1, coefficientVerified: true }]); const withLv2 = calculateTermAverage([{ average: 14, coefficient: 5, coefficientVerified: true }, { average: 10, coefficient: 1, coefficientVerified: true }]); expect(withoutLv2.average).toBe(14); expect(withoutLv2.includedSubjectCount).toBe(1); expect(withLv2.average).toBe(13.33); expect(withLv2.includedSubjectCount).toBe(2); });
  it("ne cumule jamais deux LV2, même si les deux langues sont présentes dans le catalogue", () => { const result = calculateTermAverage([{ average: 10, coefficient: 22, coefficientVerified: true }, { average: 14, coefficient: 3, coefficientVerified: true, isOptional: true }, { average: 18, coefficient: 3, coefficientVerified: true, isOptional: true }]); expect(result.average).toBe(10.48); expect(result.includedSubjectCount).toBe(2); });
  it("calcule un total de coefficients en retenant une seule LV2 vérifiée", () => { expect(calculateCoefficientMatrixTotal([{ coefficient: 22, coefficientVerified: true }, { coefficient: 3, coefficientVerified: true, isOptional: true }, { coefficient: 3, coefficientVerified: true, isOptional: true }])).toBe(25); });
});
