import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { AppScreen } from "@/components/edutech/app-screen";
import { CourseEmpty, CourseError, CourseLoading } from "@/components/edutech/course-feedback";
import { LessonMarkdown } from "@/components/edutech/lesson-markdown";
import { PageHeader } from "@/components/edutech/page-header";
import { ExerciseAttempt, ExerciseDetail, ExerciseQuestion, getExerciseDetail, humanDifficulty, humanExerciseType, startExerciseAttempt, submitExerciseAttempt } from "@/lib/exercises/exercise-service";
import { useEduTheme } from "@/lib/edutech/theme-context";

export default function ExerciseDetailScreen() {
  const { exerciseId } = useLocalSearchParams<{ exerciseId: string }>(); const router = useRouter(); const { colors } = useEduTheme(); const styles = useMemo(() => createStyles(colors), [colors]);
  const [exercise, setExercise] = useState<ExerciseDetail | null>(null); const [attempt, setAttempt] = useState<ExerciseAttempt | null>(null); const [answers, setAnswers] = useState<Record<string, string[]>>({}); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!exerciseId) return; setLoading(true); setError(null); try { setExercise(await getExerciseDetail(exerciseId)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Une erreur inattendue est survenue."); } finally { setLoading(false); } }, [exerciseId]); useEffect(() => { void load(); }, [load]);
  const begin = useCallback(async () => { if (!exercise) return; setSaving(true); setError(null); try { setAttempt(await startExerciseAttempt(exercise.exerciseId)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Le démarrage de l’exercice a échoué."); } finally { setSaving(false); } }, [exercise]);
  const submit = useCallback(async () => { if (!attempt) return; setSaving(true); setError(null); try { await submitExerciseAttempt(attempt.attemptId, answers); router.replace(`/exercise/result/${attempt.attemptId}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "La soumission a échoué."); } finally { setSaving(false); } }, [answers, attempt, router]);
  if (loading) return <AppScreen><CourseLoading label="Chargement de l’exercice" /></AppScreen>; if (error && !exercise) return <AppScreen><CourseError message={error} onRetry={() => void load()} /></AppScreen>; if (!exercise) return <AppScreen><CourseEmpty title="Exercice indisponible" description="Cet exercice n’est pas accessible avec votre profil scolaire actuel." /></AppScreen>;
  return <AppScreen withPadding={false}><ScrollView contentContainerStyle={styles.content}><View style={styles.inner}><PageHeader title={exercise.title} subtitle={`${exercise.subjectName} · ${exercise.chapterTitle}`} back /><View style={styles.meta}><Text style={styles.metaText}>{exercise.lessonTitle}</Text><Text style={styles.metaText}>{humanExerciseType(exercise.exerciseType)}</Text>{exercise.difficulty ? <Text style={styles.metaText}>{humanDifficulty(exercise.difficulty)}</Text> : null}{exercise.estimatedDurationMinutes ? <Text style={styles.metaText}>{exercise.estimatedDurationMinutes} min</Text> : null}</View><View style={styles.markdown}><LessonMarkdown content={exercise.statement} />{exercise.contentMarkdown ? <LessonMarkdown content={exercise.contentMarkdown} /> : null}</View>{error ? <Text style={styles.error}>{error}</Text> : null}{!attempt ? <Pressable accessibilityRole="button" disabled={saving || !exercise.questions.length} onPress={() => void begin()} style={({ pressed }) => [styles.primary, (saving || !exercise.questions.length) && styles.disabled, pressed && !saving && styles.pressed]}><MaterialIcons name="play-circle-outline" size={20} color={colors.surface} /><Text style={styles.primaryLabel}>{!exercise.questions.length ? "Questions à venir" : saving ? "Préparation…" : "Commencer l’exercice"}</Text></Pressable> : <View style={styles.questions}>{exercise.questions.map((question, index) => <QuestionCard key={question.id} question={question} index={index} answer={answers[question.id] ?? []} onChange={(value) => setAnswers((current) => ({ ...current, [question.id]: value }))} />)}<Pressable accessibilityRole="button" disabled={saving} onPress={() => void submit()} style={({ pressed }) => [styles.primary, saving && styles.disabled, pressed && !saving && styles.pressed]}><MaterialIcons name="task-alt" size={20} color={colors.surface} /><Text style={styles.primaryLabel}>{saving ? "Soumission…" : "Soumettre mes réponses"}</Text></Pressable></View>}</View></ScrollView></AppScreen>;
}

function QuestionCard({ question, index, answer, onChange }: { question: ExerciseQuestion; index: number; answer: string[]; onChange: (value: string[]) => void }) { const { colors } = useEduTheme(); const styles = useMemo(() => questionStyles(colors), [colors]); const choice = question.questionType === "single_choice" || question.questionType === "true_false"; const multiple = question.questionType === "multiple_choice"; return <View style={styles.card}><Text style={styles.number}>Question {index + 1}</Text><LessonMarkdown content={question.promptMarkdown} />{choice || multiple ? <View style={styles.options}>{question.options.map((option) => { const selected = answer.includes(option); return <Pressable key={option} accessibilityRole="button" onPress={() => onChange(multiple ? (selected ? answer.filter((item) => item !== option) : [...answer, option]) : [option])} style={({ pressed }) => [styles.option, selected && styles.optionSelected, pressed && styles.pressed]}><MaterialIcons name={multiple ? (selected ? "check-box" : "check-box-outline-blank") : (selected ? "radio-button-checked" : "radio-button-unchecked")} size={20} color={selected ? colors.primary : colors.muted} /><Text style={[styles.optionText, selected && styles.optionTextSelected]}>{option}</Text></Pressable>; })}</View> : <TextInput value={answer[0] ?? ""} onChangeText={(value) => onChange([value])} placeholder={question.questionType === "free_response" ? "Rédigez votre réponse" : "Saisissez votre réponse"} placeholderTextColor={colors.muted} multiline={question.questionType === "free_response"} style={[styles.input, question.questionType === "free_response" && styles.textarea]} />}</View>; }

const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { paddingTop: 18, paddingBottom: 30 }, inner: { paddingHorizontal: 20 }, meta: { flexDirection: "row", gap: 7, flexWrap: "wrap", marginTop: 15 }, metaText: { color: colors.primary, backgroundColor: colors.primarySoft, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8, fontSize: 10, fontWeight: "900" }, markdown: { gap: 16, padding: 17, borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, marginTop: 17 }, primary: { minHeight: 48, marginTop: 20, borderRadius: 14, backgroundColor: colors.primary, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, paddingHorizontal: 14 }, primaryLabel: { color: colors.surface, fontSize: 14, fontWeight: "900" }, questions: { gap: 14, marginTop: 20 }, error: { color: colors.error, fontSize: 12, lineHeight: 18, marginTop: 14, fontWeight: "700" }, disabled: { opacity: 0.55 }, pressed: { opacity: 0.72 } });
const questionStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ card: { gap: 14, padding: 16, borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, number: { color: colors.primary, fontSize: 12, fontWeight: "900" }, options: { gap: 9 }, option: { minHeight: 46, flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 12, borderRadius: 13, backgroundColor: colors.surfaceMuted }, optionSelected: { backgroundColor: colors.primarySoft, borderWidth: 1, borderColor: colors.primary }, optionText: { flex: 1, color: colors.text, fontSize: 14, lineHeight: 20, fontWeight: "700" }, optionTextSelected: { color: colors.primary, fontWeight: "900" }, input: { minHeight: 48, color: colors.text, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.background, borderRadius: 13, paddingHorizontal: 12, fontSize: 14 }, textarea: { minHeight: 120, paddingTop: 12, textAlignVertical: "top" }, pressed: { opacity: 0.72 } });
