import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useFocusEffect, useRouter } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { AppScreen } from "@/components/edutech/app-screen";
import { CourseEmpty, CourseError, CourseLoading } from "@/components/edutech/course-feedback";
import { PageHeader } from "@/components/edutech/page-header";
import { ExerciseHistoryItem, getMyExerciseHistory, resultLabel } from "@/lib/exercises/exercise-service";
import { useEduTheme } from "@/lib/edutech/theme-context";

export default function ExerciseHistoryScreen() { const router = useRouter(); const { colors } = useEduTheme(); const styles = useMemo(() => createStyles(colors), [colors]); const [items, setItems] = useState<ExerciseHistoryItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const load = useCallback(async () => { setLoading(true); setError(null); try { setItems(await getMyExerciseHistory()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Une erreur inattendue est survenue."); } finally { setLoading(false); } }, []); useFocusEffect(useCallback(() => { void load(); }, [load])); if (loading) return <AppScreen><CourseLoading label="Chargement de l’historique" /></AppScreen>; if (error) return <AppScreen><CourseError message={error} onRetry={() => void load()} /></AppScreen>; return <AppScreen withPadding={false}><FlatList data={items} keyExtractor={(item) => item.attemptId} contentContainerStyle={styles.content} ListHeaderComponent={<PageHeader title="Mon historique" subtitle="Vos exercices déjà soumis." back />} renderItem={({ item }) => <Pressable accessibilityRole="button" onPress={() => router.push(`/exercise/result/${item.attemptId}`)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.icon}><MaterialIcons name="assignment-turned-in" size={21} color={colors.primary} /></View><View style={styles.copy}><Text style={styles.title}>{item.title}</Text><Text style={styles.date}>{new Date(item.submittedAt ?? item.startedAt).toLocaleDateString("fr-FR")}</Text><Text style={styles.meta}>{resultLabel(item.status,item.percentage)} · meilleur score {item.bestPercentage === null ? "—" : `${Math.round(item.bestPercentage)} %`} · {item.attemptCount} tentative{item.attemptCount > 1 ? "s" : ""}</Text></View><MaterialIcons name="chevron-right" size={23} color={colors.muted} /></Pressable>} ListEmptyComponent={<CourseEmpty title="Aucun exercice réalisé" description="Vos exercices soumis et leurs résultats apparaîtront ici." />} /></AppScreen>; }
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 18, paddingBottom: 28, gap: 10 }, card: { minHeight: 76, padding: 14, borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, flexDirection: "row", alignItems: "center", gap: 11 }, icon: { width: 42, height: 42, borderRadius: 14, justifyContent: "center", alignItems: "center", backgroundColor: colors.primarySoft }, copy: { flex: 1 }, title: { color: colors.text, fontSize: 15, fontWeight: "900" }, date: { color: colors.muted, fontSize: 11, marginTop: 3 }, meta: { color: colors.primary, fontSize: 11, lineHeight: 16, fontWeight: "800", marginTop: 4 }, pressed: { opacity: 0.72 } });
