import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Redirect, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { AdminLoading, AdminNotice, AdminStatus, AdminToggle } from "@/components/edutech/admin-ui";
import { PageHeader } from "@/components/edutech/page-header";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { AdminOffering, AdminSubject, AdminTarget, getAdminOfferings, getAdminSubject, getAdminTargets, setOfferingPublication } from "@/lib/admin/course-admin-service";
import { useEduTheme } from "@/lib/edutech/theme-context";

export default function AdminOfferingScreen() {
  const { subjectId } = useLocalSearchParams<{ subjectId: string }>(); const { isAdmin } = useSupabaseAuth(); const { colors } = useEduTheme(); const styles = useMemo(() => createStyles(colors), [colors]); const [subject, setSubject] = useState<AdminSubject | null>(null); const [targets, setTargets] = useState<AdminTarget[]>([]); const [offerings, setOfferings] = useState<AdminOffering[]>([]); const [loading, setLoading] = useState(true); const [busyKey, setBusyKey] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setError(null); setLoading(true); try { const [item, nextTargets, nextOfferings] = await Promise.all([getAdminSubject(subjectId), getAdminTargets(), getAdminOfferings(subjectId)]); if (!item) { setError("Cette matière n’est plus disponible."); return; } setSubject(item); setTargets(nextTargets); setOfferings(nextOfferings); } catch (cause) { setError(cause instanceof Error ? cause.message : "Les associations n’ont pas pu être chargées."); } finally { setLoading(false); } }, [subjectId]);
  useEffect(() => { void load(); }, [load]);
  const change = async (target: AdminTarget, value: boolean) => { const key = `${target.levelId}-${target.seriesId}`; setBusyKey(key); setNotice(null); setError(null); try { await setOfferingPublication(subjectId, target, value); setOfferings(await getAdminOfferings(subjectId)); setNotice(value ? `${target.levelName} ${target.seriesName} est publié.` : `${target.levelName} ${target.seriesName} est dépublié.`); } catch (cause) { setError(cause instanceof Error ? cause.message : "La publication n’a pas pu être mise à jour."); } finally { setBusyKey(null); } };
  const grouped = useMemo(() => targets.reduce<Record<string, AdminTarget[]>>((result, target) => { (result[target.levelName] ??= []).push(target); return result; }, {}), [targets]);
  if (!isAdmin) return <Redirect href="/(tabs)" />;
  if (loading) return <AppScreen><AdminLoading label="Chargement des associations…" /></AppScreen>;
  return <AppScreen edges={["top", "bottom", "left", "right"]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><PageHeader title="Associations" subtitle={subject ? subject.name : "Matière"} back />{subject ? <View style={styles.subjectState}><View style={styles.subjectIcon}><MaterialIcons name="menu-book" size={20} color={colors.primary} /></View><View style={styles.subjectCopy}><Text style={styles.subjectName}>{subject.name}</Text><Text style={styles.subjectHint}>La publication d’une association cible réellement les élèves du niveau et de la série sélectionnés.</Text></View><AdminStatus active={subject.isActive} activeLabel="Matière active" inactiveLabel="Matière inactive" /></View> : null}{subject && !subject.isActive ? <AdminNotice tone="warning">La matière est inactive : même une association publiée restera masquée dans le parcours élève jusqu’à sa réactivation.</AdminNotice> : null}{notice ? <AdminNotice tone="success">{notice}</AdminNotice> : null}{error ? <AdminNotice tone="error">{error}</AdminNotice> : null}{Object.entries(grouped).map(([levelName, items]) => <View key={levelName} style={styles.group}><Text style={styles.groupTitle}>{levelName}</Text>{items.map((target) => { const offering = offerings.find((item) => item.levelId === target.levelId && item.seriesId === target.seriesId); const key = `${target.levelId}-${target.seriesId}`; return <AdminToggle key={key} label={`Série ${target.seriesName}`} description={offering?.isPublished ? "Association publiée dans Supabase." : "Association non publiée : invisible pour les élèves."} value={Boolean(offering?.isPublished)} onChange={(value) => void change(target, value)} disabled={busyKey === key} />; })}</View>)}</ScrollView></AppScreen>;
}
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { paddingTop: 18, paddingBottom: 28, gap: 13 }, subjectState: { flexDirection: "row", alignItems: "flex-start", gap: 10, padding: 13, borderRadius: 16, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, subjectIcon: { width: 39, height: 39, borderRadius: 13, justifyContent: "center", alignItems: "center", backgroundColor: colors.primarySoft }, subjectCopy: { flex: 1 }, subjectName: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: "800" }, subjectHint: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 2 }, group: { gap: 9, paddingTop: 7 }, groupTitle: { color: colors.text, fontSize: 16, lineHeight: 21, fontWeight: "800" } });
