import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { CourseEmpty, CourseError, CourseLoading } from "@/components/edutech/course-feedback";
import { PageHeader } from "@/components/edutech/page-header";
import { CourseLesson, getLesson, getLessonsForChapter } from "@/lib/courses/course-service";
import { useEduTheme } from "@/lib/edutech/theme-context";

export default function LessonReaderScreen() { const { lessonId } = useLocalSearchParams<{ lessonId: string }>(); const router = useRouter(); const { colors } = useEduTheme(); const [lesson, setLesson] = useState<CourseLesson | null>(null); const [chapterLessons, setChapterLessons] = useState<CourseLesson[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const styles = useMemo(() => createStyles(colors), [colors]); const load = useCallback(async () => { if (!lessonId) return; setLoading(true); setError(null); try { const nextLesson = await getLesson(lessonId); setLesson(nextLesson); setChapterLessons(nextLesson ? await getLessonsForChapter(nextLesson.chapterId) : []); } catch (cause) { setError(cause instanceof Error ? cause.message : "Une erreur inattendue est survenue."); } finally { setLoading(false); } }, [lessonId]); useEffect(() => { void load(); }, [load]); if (loading) return <AppScreen><CourseLoading label="Chargement de la leçon" /></AppScreen>; if (error) return <AppScreen><CourseError message={error} onRetry={() => void load()} /></AppScreen>; if (!lesson) return <AppScreen><CourseEmpty title="Leçon indisponible" description="Cette leçon n’est pas accessible avec votre profil scolaire actuel." /></AppScreen>; const currentIndex = chapterLessons.findIndex((item) => item.id === lesson.id); const previous = currentIndex > 0 ? chapterLessons[currentIndex - 1] : null; const next = currentIndex >= 0 ? chapterLessons[currentIndex + 1] : null; return <AppScreen withPadding={false}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><View style={styles.inner}><PageHeader title={lesson.title} subtitle={lesson.description || "Lecture de la leçon."} back /><View style={styles.reader}><Text style={styles.contentText}>{lesson.content || "Le contenu de cette leçon sera ajouté prochainement."}</Text></View><View style={styles.navigation}><NavButton direction="previous" label={previous ? "Leçon précédente" : "Début du chapitre"} disabled={!previous} onPress={() => previous && router.replace(`/course/lesson/${previous.id}`)} /><NavButton direction="next" label={next ? "Leçon suivante" : "Fin du chapitre"} disabled={!next} onPress={() => next && router.replace(`/course/lesson/${next.id}`)} /></View></View></ScrollView></AppScreen>; }
function NavButton({ direction, label, disabled, onPress }: { direction: "previous" | "next"; label: string; disabled: boolean; onPress: () => void }) { const { colors } = useEduTheme(); const styles = useMemo(() => navStyles(colors), [colors]); const icon = direction === "previous" ? "chevron-left" : "chevron-right"; return <Pressable disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.button, disabled && styles.disabled, pressed && !disabled && styles.pressed]}><MaterialIcons name={icon} size={20} color={disabled ? colors.muted : colors.primary} /><Text style={[styles.label, { color: disabled ? colors.muted : colors.primary }]}>{label}</Text></Pressable>; }
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { paddingTop: 18, paddingBottom: 30 }, inner: { paddingHorizontal: 20 }, reader: { marginTop: 23, backgroundColor: colors.surface, borderRadius: 20, borderWidth: 1, borderColor: colors.border, padding: 18 }, contentText: { color: colors.text, fontSize: 16, lineHeight: 26 }, navigation: { flexDirection: "row", gap: 10, marginTop: 18 } });
const navStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ button: { flex: 1, minHeight: 48, borderRadius: 15, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5, paddingHorizontal: 9 }, disabled: { backgroundColor: colors.background }, pressed: { opacity: 0.72 }, label: { fontSize: 12, fontWeight: "800", textAlign: "center" } });
