import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { PageHeader } from "@/components/edutech/page-header";
import { PrimaryButton } from "@/components/edutech/primary-button";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { useEduTheme } from "@/lib/edutech/theme-context";

export default function ForgotPasswordScreen() {
  const router = useRouter(); const { colors } = useEduTheme(); const { sendPasswordReset } = useSupabaseAuth(); const [email, setEmail] = useState(""); const [notice, setNotice] = useState<string | null>(null); const [isSubmitting, setIsSubmitting] = useState(false); const styles = useMemo(() => createStyles(colors), [colors]);
  const submit = async () => { if (!email.trim()) { setNotice("Renseignez votre adresse e-mail."); return; } setNotice(null); setIsSubmitting(true); const result = await sendPasswordReset(email); setIsSubmitting(false); setNotice(result.error ?? "Si cette adresse est associée à un compte, un lien de réinitialisation vient d’être envoyé."); };
  return <AppScreen edges={["top", "bottom", "left", "right"]}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.content}><View><PageHeader title="Mot de passe oublié" subtitle="Recevez un lien sécurisé de réinitialisation." back /><View style={styles.card}><Text style={styles.copy}>Indiquez l’adresse e-mail associée à votre compte EduTech School.</Text><Text style={styles.label}>Adresse e-mail</Text><TextInput value={email} onChangeText={setEmail} placeholder="vous@exemple.com" placeholderTextColor={colors.muted} autoCapitalize="none" autoComplete="email" keyboardType="email-address" editable={!isSubmitting} style={styles.input} />{notice ? <View style={styles.notice}><Text style={styles.noticeText}>{notice}</Text></View> : null}</View></View><View style={styles.actions}><PrimaryButton label="Envoyer le lien" onPress={submit} loading={isSubmitting} /><PrimaryButton label="Retour à la connexion" variant="secondary" onPress={() => router.replace("/auth/login")} /></View></KeyboardAvoidingView></AppScreen>;
}
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { flex: 1, justifyContent: "space-between", paddingVertical: 18 }, card: { padding: 17, borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, copy: { color: colors.muted, fontSize: 14, lineHeight: 20 }, label: { color: colors.text, fontSize: 13, lineHeight: 18, fontWeight: "800", marginTop: 20, marginBottom: 6 }, input: { height: 52, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.background, borderRadius: 15, paddingHorizontal: 14, color: colors.text, fontSize: 15 }, notice: { marginTop: 14, padding: 12, borderRadius: 13, backgroundColor: colors.warningSoft }, noticeText: { color: colors.warning, fontSize: 13, lineHeight: 19, fontWeight: "600" }, actions: { gap: 11 } });
