import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Link, useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { BrandMark } from "@/components/edutech/brand-mark";
import { PrimaryButton } from "@/components/edutech/primary-button";
import { getAuthAvailability } from "@/lib/auth/auth-service";
import { useEduTheme } from "@/lib/edutech/theme-context";
export default function LoginScreen() { const router = useRouter(); const { colors } = useEduTheme(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [notice, setNotice] = useState<string | null>(null); const styles = useMemo(() => createStyles(colors), [colors]); const availability = getAuthAvailability(); const handleSignIn = () => { if (!email.trim() || !password.trim()) { setNotice("Renseignez votre adresse e-mail et votre mot de passe pour poursuivre."); return; } setNotice(availability.message); }; return <AppScreen edges={["top", "bottom", "left", "right"]}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.flex}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled"><BrandMark /><View style={styles.heading}><Text style={styles.title}>Bienvenue</Text><Text style={styles.subtitle}>Connectez-vous pour retrouver votre parcours scolaire.</Text></View><View style={styles.form}><Text style={styles.label}>Adresse e-mail</Text><View style={styles.inputWrap}><MaterialIcons name="mail-outline" size={20} color={colors.muted} /><TextInput value={email} onChangeText={setEmail} placeholder="vous@exemple.com" placeholderTextColor={colors.muted} autoCapitalize="none" autoComplete="email" keyboardType="email-address" returnKeyType="next" style={styles.input} /></View><Text style={styles.label}>Mot de passe</Text><View style={styles.inputWrap}><MaterialIcons name="lock-outline" size={20} color={colors.muted} /><TextInput value={password} onChangeText={setPassword} placeholder="Votre mot de passe" placeholderTextColor={colors.muted} secureTextEntry autoComplete="password" returnKeyType="done" onSubmitEditing={handleSignIn} style={styles.input} /></View><Link href="/auth/forgot-password" style={styles.forgot}>Mot de passe oublié ?</Link>{notice ? <View style={styles.notice}><MaterialIcons name="info-outline" size={19} color={colors.warning} /><Text style={styles.noticeText}>{notice}</Text></View> : null}<PrimaryButton label="Se connecter" onPress={handleSignIn} icon={<MaterialIcons name="login" size={20} color={colors.surface} />} /><PrimaryButton label="Découvrir l’application" variant="secondary" onPress={() => router.replace("/(tabs)")} /></View><Text style={styles.bottomCopy}>Nouveau sur EduTech School ? <Link href="/auth/register" style={styles.link}>Créer un compte</Link></Text></ScrollView></KeyboardAvoidingView></AppScreen>; }
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ flex: { flex: 1 }, scroll: { flexGrow: 1, paddingVertical: 24 }, heading: { marginTop: 42, marginBottom: 28 }, title: { color: colors.text, fontSize: 30, lineHeight: 37, fontWeight: "800", letterSpacing: -0.7 }, subtitle: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 7 }, form: { gap: 11 }, label: { color: colors.text, fontSize: 13, lineHeight: 18, fontWeight: "800", marginTop: 3 }, inputWrap: { height: 52, flexDirection: "row", alignItems: "center", gap: 11, paddingHorizontal: 14, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: 15 }, input: { flex: 1, color: colors.text, fontSize: 15, lineHeight: 20, paddingVertical: 0 }, forgot: { color: colors.primary, fontSize: 13, lineHeight: 19, fontWeight: "800", textAlign: "right", marginTop: 1, marginBottom: 3 }, notice: { flexDirection: "row", alignItems: "flex-start", gap: 8, padding: 12, borderRadius: 13, backgroundColor: colors.warningSoft, marginBottom: 2 }, noticeText: { flex: 1, color: colors.warning, fontSize: 13, lineHeight: 18, fontWeight: "600" }, bottomCopy: { color: colors.muted, fontSize: 14, lineHeight: 20, textAlign: "center", marginTop: 25 }, link: { color: colors.primary, fontWeight: "800" } });
