import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { BrandMark } from "@/components/edutech/brand-mark";
import { PrimaryButton } from "@/components/edutech/primary-button";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { useEduTheme } from "@/lib/edutech/theme-context";

export default function RegisterScreen() {
  const router = useRouter(); const { colors } = useEduTheme(); const { signUp } = useSupabaseAuth(); const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [level, setLevel] = useState(""); const [series, setSeries] = useState(""); const [notice, setNotice] = useState<string | null>(null); const [isSubmitting, setIsSubmitting] = useState(false); const styles = useMemo(() => createStyles(colors), [colors]);
  const register = async () => { if (!firstName.trim() || !lastName.trim() || !email.trim() || !password || !level.trim()) { setNotice("Renseignez le prénom, le nom, l’e-mail, le mot de passe et le niveau scolaire."); return; } if (password.length < 8) { setNotice("Le mot de passe doit contenir au moins 8 caractères."); return; } setNotice(null); setIsSubmitting(true); const result = await signUp({ firstName, lastName, email, password, level, series }); setIsSubmitting(false); if (result.error) setNotice(result.error); else if (result.needsEmailConfirmation) setNotice("Votre compte a été créé. Consultez votre e-mail pour confirmer votre adresse avant de vous connecter."); };
  return <AppScreen edges={["top", "bottom", "left", "right"]}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.flex}><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><BrandMark /><View style={styles.heading}><Text style={styles.title}>Créer un compte</Text><Text style={styles.subtitle}>Préparez votre espace scolaire avec vos informations réelles.</Text></View><View style={styles.form}><Field label="Prénom" value={firstName} onChange={setFirstName} placeholder="Votre prénom" editable={!isSubmitting} /><Field label="Nom" value={lastName} onChange={setLastName} placeholder="Votre nom" editable={!isSubmitting} /><Field label="Adresse e-mail" value={email} onChange={setEmail} placeholder="vous@exemple.com" type="email" editable={!isSubmitting} /><Field label="Mot de passe" value={password} onChange={setPassword} placeholder="8 caractères minimum" secure editable={!isSubmitting} /><Field label="Niveau scolaire" value={level} onChange={setLevel} placeholder="Ex. Terminale" editable={!isSubmitting} /><Field label="Série (si applicable)" value={series} onChange={setSeries} placeholder="Ex. Scientifique" editable={!isSubmitting} />{notice ? <View style={styles.notice}><Text style={styles.noticeText}>{notice}</Text></View> : null}<PrimaryButton label="Créer mon compte" onPress={register} loading={isSubmitting} /></View><PrimaryButton label="J’ai déjà un compte" variant="text" onPress={() => router.replace("/auth/login")} style={styles.loginButton} /></ScrollView></KeyboardAvoidingView></AppScreen>;
}
function Field({ label, value, onChange, placeholder, editable, type, secure = false }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; editable: boolean; type?: "email"; secure?: boolean }) { const { colors } = useEduTheme(); const styles = useMemo(() => fieldStyles(colors), [colors]); return <View><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor={colors.muted} autoCapitalize={type === "email" ? "none" : "words"} autoComplete={type === "email" ? "email" : undefined} keyboardType={type === "email" ? "email-address" : "default"} secureTextEntry={secure} editable={editable} style={styles.input} /></View>; }
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ flex: { flex: 1 }, scroll: { flexGrow: 1, paddingVertical: 24 }, heading: { marginTop: 32, marginBottom: 24 }, title: { color: colors.text, fontSize: 29, lineHeight: 36, fontWeight: "800", letterSpacing: -0.6 }, subtitle: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 7 }, form: { gap: 12 }, notice: { padding: 12, borderRadius: 13, backgroundColor: colors.warningSoft }, noticeText: { color: colors.warning, fontSize: 13, lineHeight: 19, fontWeight: "600" }, loginButton: { marginTop: 18 } });
const fieldStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ label: { color: colors.text, fontSize: 13, lineHeight: 18, fontWeight: "800", marginBottom: 6 }, input: { height: 52, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: 15, paddingHorizontal: 14, color: colors.text, fontSize: 15 } });

