import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { BrandMark } from "@/components/edutech/brand-mark";
import { PrimaryButton } from "@/components/edutech/primary-button";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { useEduTheme } from "@/lib/edutech/theme-context";

const SCHOOL_LEVELS = ["Première", "Terminale"];
const SCHOOL_SERIES = ["A1", "A2", "C", "D"];

export default function RegisterScreen() {
  const router = useRouter(); const { colors } = useEduTheme(); const { signUp } = useSupabaseAuth(); const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [schoolLevel, setSchoolLevel] = useState(""); const [series, setSeries] = useState(""); const [notice, setNotice] = useState<string | null>(null); const [isSubmitting, setIsSubmitting] = useState(false); const styles = useMemo(() => createStyles(colors), [colors]);
  const register = async () => { if (!firstName.trim() || !lastName.trim() || !email.trim() || !password || !schoolLevel || !series) { setNotice("Renseignez le prénom, le nom, l’e-mail, le mot de passe, le niveau scolaire et la série."); return; } if (password.length < 8) { setNotice("Le mot de passe doit contenir au moins 8 caractères."); return; } setNotice(null); setIsSubmitting(true); const result = await signUp({ firstName, lastName, email, password, schoolLevel, series }); setIsSubmitting(false); if (result.error) setNotice(result.error); else if (result.needsEmailConfirmation) setNotice("Votre compte a été créé. Consultez votre e-mail pour confirmer votre adresse avant de vous connecter."); };
  return <AppScreen edges={["top", "bottom", "left", "right"]}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.flex}><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><BrandMark /><View style={styles.heading}><Text style={styles.title}>Créer un compte</Text><Text style={styles.subtitle}>Préparez votre espace scolaire avec vos informations réelles.</Text></View><View style={styles.form}><Field label="Prénom" value={firstName} onChange={setFirstName} placeholder="Votre prénom" editable={!isSubmitting} /><Field label="Nom" value={lastName} onChange={setLastName} placeholder="Votre nom" editable={!isSubmitting} /><Field label="Adresse e-mail" value={email} onChange={setEmail} placeholder="vous@exemple.com" type="email" editable={!isSubmitting} /><Field label="Mot de passe" value={password} onChange={setPassword} placeholder="8 caractères minimum" secure editable={!isSubmitting} /><ChoiceSelector label="Mon niveau scolaire" options={SCHOOL_LEVELS} value={schoolLevel} onChange={setSchoolLevel} disabled={isSubmitting} /><ChoiceSelector label="Ma série" options={SCHOOL_SERIES} value={series} onChange={setSeries} disabled={isSubmitting} />{notice ? <View style={styles.notice}><Text style={styles.noticeText}>{notice}</Text></View> : null}<PrimaryButton label="Créer mon compte" onPress={register} loading={isSubmitting} /></View><PrimaryButton label="J’ai déjà un compte" variant="text" onPress={() => router.replace("/auth/login")} style={styles.loginButton} /></ScrollView></KeyboardAvoidingView></AppScreen>;
}
function Field({ label, value, onChange, placeholder, editable, type, secure = false }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; editable: boolean; type?: "email"; secure?: boolean }) { const { colors } = useEduTheme(); const styles = useMemo(() => fieldStyles(colors), [colors]); return <View><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor={colors.muted} autoCapitalize={type === "email" ? "none" : "words"} autoComplete={type === "email" ? "email" : undefined} keyboardType={type === "email" ? "email-address" : "default"} secureTextEntry={secure} editable={editable} style={styles.input} /></View>; }
function ChoiceSelector({ label, options, value, onChange, disabled }: { label: string; options: readonly string[]; value: string; onChange: (value: string) => void; disabled: boolean }) { const { colors } = useEduTheme(); const styles = useMemo(() => choiceStyles(colors), [colors]); return <View><Text style={styles.label}>{label}</Text><View style={styles.options}>{options.map((option) => <Pressable key={option} accessibilityRole="radio" accessibilityState={{ checked: value === option, disabled }} onPress={() => onChange(option)} style={({ pressed }) => [styles.option, value === option && styles.optionSelected, pressed && !disabled && styles.optionPressed]} disabled={disabled}><Text style={[styles.optionText, value === option && styles.optionTextSelected]}>{option}</Text></Pressable>)}</View></View>; }
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ flex: { flex: 1 }, scroll: { flexGrow: 1, paddingVertical: 24 }, heading: { marginTop: 32, marginBottom: 24 }, title: { color: colors.text, fontSize: 29, lineHeight: 36, fontWeight: "800", letterSpacing: -0.6 }, subtitle: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 7 }, form: { gap: 12 }, notice: { padding: 12, borderRadius: 13, backgroundColor: colors.warningSoft }, noticeText: { color: colors.warning, fontSize: 13, lineHeight: 19, fontWeight: "600" }, loginButton: { marginTop: 18 } });
const fieldStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ label: { color: colors.text, fontSize: 13, lineHeight: 18, fontWeight: "800", marginBottom: 6 }, input: { height: 52, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: 15, paddingHorizontal: 14, color: colors.text, fontSize: 15 } });
const choiceStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ label: { color: colors.text, fontSize: 13, lineHeight: 18, fontWeight: "800", marginBottom: 7 }, options: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, option: { minHeight: 43, paddingHorizontal: 14, justifyContent: "center", borderRadius: 13, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, optionSelected: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, optionPressed: { opacity: 0.72 }, optionText: { color: colors.text, fontSize: 14, fontWeight: "700" }, optionTextSelected: { color: colors.primary } });
