import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { EmptyState } from "@/components/edutech/empty-state";
import { PageHeader } from "@/components/edutech/page-header";
import { PrimaryButton } from "@/components/edutech/primary-button";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { useEduTheme } from "@/lib/edutech/theme-context";

export default function ResetPasswordScreen() {
  const router = useRouter(); const { colors } = useEduTheme(); const { isPasswordRecovery, updatePassword } = useSupabaseAuth(); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [notice, setNotice] = useState<string | null>(null); const [isSubmitting, setIsSubmitting] = useState(false); const styles = useMemo(() => createStyles(colors), [colors]);
  const submit = async () => { if (password.length < 8) { setNotice("Le mot de passe doit contenir au moins 8 caractères."); return; } if (password !== confirmation) { setNotice("Les deux mots de passe ne correspondent pas."); return; } setNotice(null); setIsSubmitting(true); const result = await updatePassword(password); setIsSubmitting(false); if (result.error) setNotice(result.error); else { setNotice("Votre mot de passe a été mis à jour."); setTimeout(() => router.replace("/(tabs)"), 800); } };
  if (!isPasswordRecovery) return <AppScreen edges={["top", "bottom", "left", "right"]}><View style={styles.emptyContent}><View><PageHeader title="Réinitialiser le mot de passe" subtitle="Ouvrez le lien reçu par e-mail pour continuer." back /><EmptyState icon="verified-user" title="Lien sécurisé requis" description="Demandez un nouveau lien de réinitialisation si celui-ci a expiré." /></View><PrimaryButton label="Demander un nouveau lien" onPress={() => router.replace("/auth/forgot-password")} /></View></AppScreen>;
  return <AppScreen edges={["top", "bottom", "left", "right"]}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.content}><View><PageHeader title="Nouveau mot de passe" subtitle="Choisissez un mot de passe unique et sécurisé." back /><View style={styles.card}><LabelInput label="Nouveau mot de passe" value={password} onChange={setPassword} colors={colors} /><LabelInput label="Confirmer le mot de passe" value={confirmation} onChange={setConfirmation} colors={colors} />{notice ? <View style={styles.notice}><Text style={styles.noticeText}>{notice}</Text></View> : null}</View></View><PrimaryButton label="Mettre à jour le mot de passe" onPress={submit} loading={isSubmitting} /></KeyboardAvoidingView></AppScreen>;
}
function LabelInput({ label, value, onChange, colors }: { label: string; value: string; onChange: (value: string) => void; colors: ReturnType<typeof useEduTheme>["colors"] }) { return <View><Text style={[stylesLabel.label, { color: colors.text }]}>{label}</Text><TextInput value={value} onChangeText={onChange} secureTextEntry placeholder="8 caractères minimum" placeholderTextColor={colors.muted} style={[stylesLabel.input, { borderColor: colors.border, backgroundColor: colors.background, color: colors.text }]} /></View>; }
const stylesLabel = StyleSheet.create({ label: { fontSize: 13, lineHeight: 18, fontWeight: "800", marginTop: 14, marginBottom: 6 }, input: { height: 52, borderWidth: 1, borderRadius: 15, paddingHorizontal: 14, fontSize: 15 } });
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { flex: 1, justifyContent: "space-between", paddingVertical: 18 }, emptyContent: { flex: 1, justifyContent: "space-between", paddingVertical: 18 }, card: { padding: 17, borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, notice: { marginTop: 14, padding: 12, borderRadius: 13, backgroundColor: colors.warningSoft }, noticeText: { color: colors.warning, fontSize: 13, lineHeight: 19, fontWeight: "600" } });
