import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Redirect, useRouter } from "expo-router";
import { useMemo } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { PageHeader } from "@/components/edutech/page-header";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { useEduTheme } from "@/lib/edutech/theme-context";

export default function AdministrationScreen() {
  const router = useRouter(); const { isAdmin, profile } = useSupabaseAuth(); const { colors } = useEduTheme(); const styles = useMemo(() => createStyles(colors), [colors]);
  if (!isAdmin) return <Redirect href="/(tabs)" />;
  const sections = [{ title: "Matières", description: "Catalogue, ordre, statut et associations niveau-série.", icon: "menu-book", route: "/administration/subjects" }, { title: "Chapitres", description: "Chapitres liés aux matières publiées, ordre et brouillon.", icon: "format-list-numbered", route: "/administration/chapters" }, { title: "Leçons", description: "Éditeur simple de leçons, contenu, ordre et publication.", icon: "article", route: "/administration/lessons" }] as const;
  return <AppScreen edges={["top", "bottom", "left", "right"]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}><PageHeader title="Administration" subtitle="Gestion pédagogique sécurisée" back /><View style={styles.identity}><MaterialIcons name="verified-user" size={21} color={colors.primary} /><View style={styles.identityCopy}><Text style={styles.identityTitle}>Rôle administrateur vérifié</Text><Text style={styles.identityBody}>{profile?.full_name ?? "Administrateur"} — les autorisations sont contrôlées par Supabase.</Text></View></View><Text style={styles.sectionTitle}>Gérer le contenu</Text><View style={styles.list}>{sections.map((section) => <Pressable key={section.title} accessibilityRole="button" accessibilityLabel={`Ouvrir ${section.title}`} onPress={() => router.push(section.route as any)} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.icon}><MaterialIcons name={section.icon} size={23} color={colors.primary} /></View><View style={styles.cardCopy}><Text style={styles.cardTitle}>{section.title}</Text><Text style={styles.cardDescription}>{section.description}</Text></View><MaterialIcons name="chevron-right" size={24} color={colors.muted} /></Pressable>)}</View><View style={styles.note}><MaterialIcons name="info-outline" size={19} color={colors.warning} /><Text style={styles.noteText}>Les modifications sont enregistrées dans Supabase. Une matière ou leçon inactive reste visible ici, mais n’est pas affichée aux élèves.</Text></View></ScrollView></AppScreen>;
}
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ scroll: { paddingTop: 18, paddingBottom: 28 }, identity: { flexDirection: "row", gap: 12, padding: 14, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.primarySoft, borderRadius: 17, marginBottom: 24 }, identityCopy: { flex: 1 }, identityTitle: { color: colors.text, fontSize: 14, lineHeight: 19, fontWeight: "800" }, identityBody: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 2 }, sectionTitle: { color: colors.text, fontSize: 16, lineHeight: 21, fontWeight: "800", marginBottom: 10 }, list: { gap: 10 }, card: { minHeight: 94, flexDirection: "row", alignItems: "center", gap: 13, padding: 14, borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, icon: { width: 46, height: 46, borderRadius: 15, backgroundColor: colors.primarySoft, justifyContent: "center", alignItems: "center" }, cardCopy: { flex: 1 }, cardTitle: { color: colors.text, fontSize: 16, lineHeight: 21, fontWeight: "800" }, cardDescription: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 3 }, note: { marginTop: 18, flexDirection: "row", alignItems: "flex-start", gap: 9, borderRadius: 16, padding: 13, backgroundColor: colors.warningSoft }, noteText: { flex: 1, color: colors.warning, fontSize: 12, lineHeight: 18, fontWeight: "700" }, pressed: { opacity: 0.7, transform: [{ scale: 0.99 }] } });
