import { useRouter } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useMemo } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { AppScreen } from "@/components/edutech/app-screen";
import { EmptyState } from "@/components/edutech/empty-state";
import { PageHeader } from "@/components/edutech/page-header";
import { useEduTheme } from "@/lib/edutech/theme-context";
import { useNotificationInbox } from "@/lib/notifications/notification-sync-context";

function dateLabel(value: string) { return new Intl.DateTimeFormat("fr-CI", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }

export default function NotificationsScreen() {
  const router = useRouter(); const { colors } = useEduTheme(); const { inbox, isLoading, isOffline, error, refresh, markRead, deleteLocal } = useNotificationInbox(); const styles = useMemo(() => createStyles(colors), [colors]);
  const open = async (id: string, route: string | null) => { await markRead(id); if (route?.startsWith("/")) router.push(route as any); };
  return <AppScreen edges={["top", "bottom", "left", "right"]}><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}><PageHeader title="Notifications" subtitle={isOffline ? "Mode hors connexion — contenu local disponible" : "Informations qui concernent votre parcours"} back /><View style={styles.status}><MaterialIcons name={isOffline ? "cloud-off" : "cloud-done"} color={isOffline ? colors.warning : colors.success} size={18} /><Text style={[styles.statusText, { color: isOffline ? colors.warning : colors.success }]}>{isOffline ? "Synchronisation en attente du réseau" : inbox.pendingReadIds.length ? "Lectures en attente de synchronisation" : "Synchronisé"}</Text></View>{isLoading && !inbox.items.length ? <View style={styles.loading}><ActivityIndicator color={colors.primary} /><Text style={styles.muted}>Chargement de vos notifications…</Text></View> : null}{error ? <View style={styles.error}><Text style={styles.errorText}>{error}</Text><Pressable accessibilityRole="button" onPress={() => void refresh()} style={({ pressed }) => [styles.retry, pressed && styles.pressed]}><Text style={styles.retryText}>Réessayer</Text></Pressable></View> : null}{!isLoading && !inbox.items.length ? <EmptyState icon="notifications-none" title="Aucune notification" description="Les publications et informations ciblées pour votre classe apparaîtront ici." /> : <View style={styles.list}>{inbox.items.map((item) => <Pressable key={item.id} accessibilityRole="button" accessibilityLabel={`Notification ${item.title}`} onPress={() => void open(item.id, item.route)} style={({ pressed }) => [styles.card, !item.readAt && styles.unread, pressed && styles.pressed]}><View style={styles.cardTop}><View style={styles.icon}><MaterialIcons name={item.priority === "high" ? "priority-high" : "notifications"} size={20} color={colors.primary} /></View><View style={styles.copy}><Text style={styles.title}>{item.title}</Text><Text style={styles.date}>{dateLabel(item.createdAt)}</Text></View>{!item.readAt ? <View style={styles.dot} /> : null}</View><Text style={styles.body}>{item.body}</Text><View style={styles.actions}><Text style={styles.actionText}>{item.route ? "Ouvrir le contenu" : item.readAt ? "Lu" : "Marquer comme lu"}</Text><Pressable accessibilityRole="button" accessibilityLabel={`Masquer ${item.title} de cet appareil`} onPress={() => void deleteLocal(item.id)} hitSlop={8} style={({ pressed }) => pressed && styles.pressed}><MaterialIcons name="close" size={19} color={colors.muted} /></Pressable></View></Pressable>)}</View>}</ScrollView></AppScreen>;
}

const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ scroll: { paddingBottom: 26 }, status: { flexDirection: "row", gap: 8, alignItems: "center", borderRadius: 13, padding: 11, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, marginBottom: 16 }, statusText: { fontSize: 12, lineHeight: 17, fontWeight: "800" }, loading: { paddingVertical: 44, alignItems: "center", gap: 10 }, muted: { color: colors.muted, fontSize: 13, fontWeight: "700" }, error: { backgroundColor: colors.surfaceMuted, borderRadius: 14, padding: 12, gap: 9, marginBottom: 12 }, errorText: { color: colors.error, fontSize: 12, lineHeight: 18, fontWeight: "700" }, retry: { alignSelf: "flex-start", paddingHorizontal: 10, paddingVertical: 7, borderRadius: 9, backgroundColor: colors.surface }, retryText: { color: colors.primary, fontSize: 12, fontWeight: "900" }, list: { gap: 10 }, card: { padding: 14, borderRadius: 18, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, unread: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, cardTop: { flexDirection: "row", alignItems: "center", gap: 10 }, icon: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: colors.surface }, copy: { flex: 1 }, title: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: "900" }, date: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 1 }, dot: { width: 9, height: 9, borderRadius: 5, backgroundColor: colors.primary }, body: { color: colors.text, fontSize: 13, lineHeight: 19, marginTop: 11 }, actions: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 12 }, actionText: { color: colors.primary, fontSize: 12, fontWeight: "800" }, pressed: { opacity: 0.7, transform: [{ scale: 0.99 }] } });
