import { useRouter } from "expo-router";
import { useMemo } from "react";
import { Alert, ScrollView, StyleSheet, Switch, Text, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { PageHeader } from "@/components/edutech/page-header";
import { SettingsRow } from "@/components/edutech/settings-row";
import { useEduTheme } from "@/lib/edutech/theme-context";
export default function SettingsScreen() { const router = useRouter(); const { colors, mode, setMode } = useEduTheme(); const styles = useMemo(() => createStyles(colors), [colors]); const explain = (title: string, message: string) => Alert.alert(title, message, [{ text: "Compris" }]); return <AppScreen withPadding={false} edges={["top", "bottom", "left", "right"]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}><View style={styles.content}><PageHeader title="Paramètres" subtitle="Personnalisez votre expérience EduTech School." back /><Text style={styles.section}>Préférences</Text><View style={styles.group}><SettingsRow icon={mode === "dark" ? "dark-mode" : "light-mode"} title="Thème sombre" subtitle="Préférence enregistrée sur cet appareil" onPress={() => setMode(mode === "dark" ? "light" : "dark")} accessory={<Switch value={mode === "dark"} onValueChange={(value) => setMode(value ? "dark" : "light")} trackColor={{ false: colors.border, true: colors.primary }} thumbColor={colors.surface} />} /><SettingsRow icon="notifications-none" title="Notifications" subtitle="Préparation pour les rappels scolaires" onPress={() => explain("Notifications", "Les notifications seront configurables quand le service associé sera activé.")} /><SettingsRow icon="language" title="Langue" subtitle="Français" onPress={() => explain("Langue", "Le français est la langue de départ. La sélection de langues sera ajoutée ultérieurement.")} /></View><Text style={styles.section}>Informations</Text><View style={styles.group}><SettingsRow icon="privacy-tip" title="Confidentialité" onPress={() => router.push("/privacy")} /><SettingsRow icon="gavel" title="Conditions d’utilisation" onPress={() => router.push("/terms")} /><SettingsRow icon="info-outline" title="À propos" onPress={() => router.push("/about")} /></View><Text style={styles.section}>Session</Text><View style={styles.group}><SettingsRow icon="logout" title="Déconnexion" subtitle="Retourne vers l’écran de connexion" danger onPress={() => router.replace("/auth/login")} /></View></View></ScrollView></AppScreen>; }
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ scroll: { paddingBottom: 26 }, content: { paddingHorizontal: 20, paddingTop: 20 }, section: { color: colors.text, fontSize: 16, lineHeight: 21, fontWeight: "800", marginBottom: 9, marginTop: 21 }, group: { overflow: "hidden", borderRadius: 18, borderWidth: 1, borderColor: colors.border } });
