import { useRouter } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { PageHeader } from "@/components/edutech/page-header";
import { PrimaryButton } from "@/components/edutech/primary-button";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { useEduTheme } from "@/lib/edutech/theme-context";

export default function EditProfileScreen() {
  const router = useRouter(); const { colors } = useEduTheme(); const { profile, updateProfile } = useSupabaseAuth(); const [firstName, setFirstName] = useState(""); const [lastName, setLastName] = useState(""); const [level, setLevel] = useState(""); const [series, setSeries] = useState(""); const [avatarUrl, setAvatarUrl] = useState(""); const [notice, setNotice] = useState<string | null>(null); const [isSubmitting, setIsSubmitting] = useState(false); const styles = useMemo(() => createStyles(colors), [colors]);
  useEffect(() => { if (!profile) return; setFirstName(profile.first_name ?? ""); setLastName(profile.last_name ?? ""); setLevel(profile.level ?? ""); setSeries(profile.series ?? ""); setAvatarUrl(profile.avatar_url ?? ""); }, [profile]);
  const save = async () => { setNotice(null); setIsSubmitting(true); const result = await updateProfile({ firstName, lastName, level, series, avatarUrl }); setIsSubmitting(false); if (result.error) setNotice(result.error); else { setNotice("Profil enregistré avec succès."); setTimeout(() => router.back(), 650); } };
  return <AppScreen edges={["top", "bottom", "left", "right"]}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.flex}><ScrollView showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled" contentContainerStyle={styles.scroll}><PageHeader title="Modifier mon profil" subtitle="Mettez à jour vos informations scolaires." back /><View style={styles.form}><Field label="Prénom" value={firstName} onChange={setFirstName} colors={colors} /><Field label="Nom" value={lastName} onChange={setLastName} colors={colors} /><Field label="Niveau scolaire" value={level} onChange={setLevel} colors={colors} /><Field label="Série (si applicable)" value={series} onChange={setSeries} colors={colors} required={false} /><Field label="URL de votre avatar (facultatif)" value={avatarUrl} onChange={setAvatarUrl} colors={colors} required={false} type="url" />{notice ? <View style={styles.notice}><Text style={styles.noticeText}>{notice}</Text></View> : null}<PrimaryButton label="Enregistrer les modifications" onPress={save} loading={isSubmitting} /></View></ScrollView></KeyboardAvoidingView></AppScreen>;
}
function Field({ label, value, onChange, colors, required = true, type }: { label: string; value: string; onChange: (value: string) => void; colors: ReturnType<typeof useEduTheme>["colors"]; required?: boolean; type?: "url" }) { return <View><Text style={[fieldStyles.label, { color: colors.text }]}>{label}{required ? " *" : ""}</Text><TextInput value={value} onChangeText={onChange} placeholder={label} placeholderTextColor={colors.muted} autoCapitalize="words" keyboardType={type === "url" ? "url" : "default"} style={[fieldStyles.input, { color: colors.text, borderColor: colors.border, backgroundColor: colors.surface }]} /></View>; }
const fieldStyles = StyleSheet.create({ label: { fontSize: 13, lineHeight: 18, fontWeight: "800", marginBottom: 6 }, input: { height: 52, borderWidth: 1, borderRadius: 15, paddingHorizontal: 14, fontSize: 15 } });
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ flex: { flex: 1 }, scroll: { flexGrow: 1, paddingTop: 18, paddingBottom: 26 }, form: { gap: 13 }, notice: { padding: 12, borderRadius: 13, backgroundColor: colors.primarySoft }, noticeText: { color: colors.primary, fontSize: 13, lineHeight: 19, fontWeight: "700" } });
