import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { EmptyState } from "@/components/edutech/empty-state";
import { PageHeader } from "@/components/edutech/page-header";
import { PrimaryButton } from "@/components/edutech/primary-button";
import { getActiveSchoolYear, getMySchoolHistory, requestMyClassChange, type SchoolHistory, type SchoolYear } from "@/lib/admin/school-administration-service";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { useEduTheme } from "@/lib/edutech/theme-context";

const levels = ["Première", "Terminale"] as const;
const series = ["A1", "A2", "C", "D"] as const;

export default function MySchoolHistoryScreen() {
  const { profile, refreshProfile } = useSupabaseAuth(); const { colors } = useEduTheme(); const styles = useMemo(() => makeStyles(colors), [colors]);
  const [history, setHistory] = useState<SchoolHistory[]>([]); const [activeYear, setActiveYear] = useState<SchoolYear | null>(null); const [selectedLevel, setSelectedLevel] = useState<string>(profile?.school_level ?? "Première"); const [selectedSeries, setSelectedSeries] = useState<string>(profile?.series ?? "A1"); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const [records, year] = await Promise.all([getMySchoolHistory(), getActiveSchoolYear()]); setHistory(records); setActiveYear(year); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Chargement impossible."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (profile?.school_level) setSelectedLevel(profile.school_level); if (profile?.series) setSelectedSeries(profile.series); }, [profile?.school_level, profile?.series]);
  const submit = async () => { setNotice(null); setError(null); try { setSubmitting(true); const result = await requestMyClassChange(selectedLevel, selectedSeries); if (result === "applied") { await refreshProfile(); setNotice("Votre première modification de classe pour l’année active a été enregistrée."); } else { setNotice("Votre demande a été transmise à l’administration pour validation."); } await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Demande impossible."); } finally { setSubmitting(false); } };
  if (!profile) return <AppScreen><PageHeader title="Parcours scolaire" back /><EmptyState icon="person-off" title="Profil indisponible" description="Reconnectez-vous puis réessayez." /></AppScreen>;
  return <AppScreen withPadding={false}><ScrollView contentContainerStyle={styles.content}><PageHeader title="Parcours scolaire" subtitle="Historique annuel et changement de classe encadré" back /><View style={styles.card}><Text style={styles.heading}>Situation actuelle</Text><Line label="Année scolaire" value={profile.school_year ?? activeYear?.name ?? "Non renseignée"} /><Line label="Niveau" value={profile.school_level ?? "Non renseigné"} /><Line label="Série" value={profile.series ?? "Non renseignée"} /><Line label="LV2" value={profile.lv2_choice ?? "Non renseignée"} /></View><View style={styles.card}><Text style={styles.heading}>Modifier ma classe</Text><Text style={styles.description}>La première modification pendant l’année scolaire active est appliquée immédiatement. Toute demande ultérieure est envoyée à l’administration et l’historique scolaire est conservé.</Text><Text style={styles.label}>Niveau demandé</Text><View style={styles.choices}>{levels.map((level) => <Choice key={level} label={level} selected={selectedLevel === level} onPress={() => setSelectedLevel(level)} />)}</View><Text style={styles.label}>Série demandée</Text><View style={styles.choices}>{series.map((item) => <Choice key={item} label={item} selected={selectedSeries === item} onPress={() => setSelectedSeries(item)} />)}</View>{notice ? <Text style={styles.notice}>{notice}</Text> : null}{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton label="Demander la modification" disabled={submitting || !activeYear || (selectedLevel === profile.school_level && selectedSeries === profile.series)} loading={submitting} onPress={() => void submit()} /></View><Text style={styles.section}>Historique des années scolaires</Text>{loading ? <ActivityIndicator color={colors.primary} /> : history.length ? history.map((item) => <View key={item.id} style={styles.history}><Text style={styles.historyTitle}>{item.schoolYear} · {item.schoolLevel} {item.series}</Text><Text style={styles.historyText}>LV2 : {item.lv2Choice ?? "Non renseignée"} · Moyenne annuelle : {item.annualAverage === null ? "Non évaluée" : `${item.annualAverage}/20`}</Text><Text style={styles.historyText}>T1 {item.t1Average ?? "—"} · T2 {item.t2Average ?? "—"} · T3 {item.t3Average ?? "—"} · {item.promotionDecision === "admitted" ? "Admis" : item.promotionDecision === "repeat" ? "Redouble" : "Décision en attente"}</Text></View>) : <Text style={styles.empty}>Aucun historique scolaire n’est encore enregistré. Il sera conservé dès la première opération annuelle ou décision administrative.</Text>}</ScrollView></AppScreen>;
}
function Choice({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { const { colors } = useEduTheme(); return <Text onPress={onPress} accessibilityRole="button" style={{ borderRadius: 11, paddingHorizontal: 12, paddingVertical: 9, backgroundColor: selected ? colors.primary : colors.primarySoft, color: selected ? colors.surface : colors.primary, fontSize: 12, fontWeight: "900", overflow: "hidden" }}>{label}</Text>; }
function Line({ label, value }: { label: string; value: string }) { const { colors } = useEduTheme(); return <View style={{ flexDirection: "row", justifyContent: "space-between", gap: 12, paddingTop: 9, marginTop: 9, borderTopWidth: 1, borderTopColor: colors.border }}><Text style={{ color: colors.muted, fontSize: 12, fontWeight: "700" }}>{label}</Text><Text style={{ color: colors.text, fontSize: 12, fontWeight: "900", textAlign: "right", flex: 1 }}>{value}</Text></View>; }
const makeStyles = (c: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { padding: 20, paddingTop: 18, paddingBottom: 34, gap: 12 }, card: { padding: 14, borderRadius: 18, borderWidth: 1, borderColor: c.border, backgroundColor: c.surface, gap: 8 }, heading: { color: c.text, fontSize: 15, fontWeight: "900" }, description: { color: c.muted, fontSize: 12, lineHeight: 18, fontWeight: "700" }, label: { color: c.text, fontSize: 12, fontWeight: "800", marginTop: 4 }, choices: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, notice: { color: c.primary, backgroundColor: c.primarySoft, borderRadius: 11, padding: 10, fontSize: 12, lineHeight: 17, fontWeight: "700" }, error: { color: c.error, backgroundColor: `${c.error}12`, borderRadius: 11, padding: 10, fontSize: 12, lineHeight: 17, fontWeight: "700" }, section: { color: c.text, fontSize: 16, fontWeight: "900", marginTop: 10 }, history: { padding: 13, borderRadius: 16, borderWidth: 1, borderColor: c.border, backgroundColor: c.surface, gap: 4 }, historyTitle: { color: c.text, fontSize: 13, fontWeight: "900" }, historyText: { color: c.muted, fontSize: 11, lineHeight: 16, fontWeight: "700" }, empty: { color: c.muted, textAlign: "center", fontSize: 12, lineHeight: 18, fontWeight: "700", padding: 14 } });
