import { ReactNode, useMemo } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { useEduTheme } from "@/lib/edutech/theme-context";

export function AdminNotice({ children, tone = "info" }: { children: ReactNode; tone?: "info" | "error" | "warning" | "success" }) { const { colors } = useEduTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); const palette = tone === "error" ? [colors.error, colors.surfaceMuted] : tone === "warning" ? [colors.warning, colors.warningSoft] : tone === "success" ? [colors.success, colors.primarySoft] : [colors.primary, colors.primarySoft]; return <View style={[styles.notice, { backgroundColor: palette[1], borderColor: palette[0] }]}><Text style={[styles.noticeText, { color: palette[0] }]}>{children}</Text></View>; }

export function AdminField({ label, value, onChange, placeholder, multiline = false, keyboardType = "default", required = true }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; multiline?: boolean; keyboardType?: "default" | "numeric"; required?: boolean }) { const { colors } = useEduTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <View><Text style={styles.label}>{label}{required ? " *" : ""}</Text><TextInput value={value} onChangeText={onChange} placeholder={placeholder ?? label} placeholderTextColor={colors.muted} autoCapitalize="sentences" keyboardType={keyboardType} multiline={multiline} textAlignVertical={multiline ? "top" : "center"} style={[styles.input, multiline && styles.multiline]} /></View>; }

export function AdminToggle({ label, description, value, onChange, disabled = false }: { label: string; description: string; value: boolean; onChange: (value: boolean) => void; disabled?: boolean }) { const { colors } = useEduTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <View style={[styles.toggleCard, disabled && styles.disabled]}><View style={styles.toggleText}><Text style={styles.toggleTitle}>{label}</Text><Text style={styles.toggleDescription}>{description}</Text></View><Switch value={value} onValueChange={onChange} disabled={disabled} trackColor={{ false: colors.border, true: colors.primary }} thumbColor={colors.surface} /></View>; }

export function AdminStatus({ active, activeLabel = "Publié", inactiveLabel = "Brouillon" }: { active: boolean; activeLabel?: string; inactiveLabel?: string }) { const { colors } = useEduTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <View style={[styles.status, { backgroundColor: active ? colors.primarySoft : colors.warningSoft }]}><Text style={{ color: active ? colors.primary : colors.warning, fontWeight: "800", fontSize: 12 }}>{active ? activeLabel : inactiveLabel}</Text></View>; }

export function AdminChoice({ label, selected, onPress }: { label: string; selected: boolean; onPress: () => void }) { const { colors } = useEduTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <Pressable accessibilityRole="button" accessibilityState={{ selected }} onPress={onPress} style={({ pressed }) => [styles.choice, { borderColor: selected ? colors.primary : colors.border, backgroundColor: selected ? colors.primarySoft : colors.surface }, pressed && styles.pressed]}><Text style={{ color: selected ? colors.primary : colors.muted, fontWeight: "800", fontSize: 13 }}>{label}</Text></Pressable>; }

export function AdminLoading({ label = "Chargement…" }: { label?: string }) { const { colors } = useEduTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); return <View style={styles.loading}><ActivityIndicator color={colors.primary} /><Text style={styles.loadingText}>{label}</Text></View>; }

const makeStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ notice: { borderWidth: 1, borderRadius: 15, padding: 13 }, noticeText: { fontSize: 13, lineHeight: 19, fontWeight: "700" }, label: { color: colors.text, fontSize: 13, lineHeight: 18, fontWeight: "800", marginBottom: 6 }, input: { minHeight: 52, borderWidth: 1, borderColor: colors.border, color: colors.text, backgroundColor: colors.surface, borderRadius: 15, paddingHorizontal: 14, fontSize: 15, lineHeight: 20 }, multiline: { minHeight: 132, paddingVertical: 13 }, toggleCard: { flexDirection: "row", gap: 12, alignItems: "center", padding: 14, borderRadius: 16, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, toggleText: { flex: 1 }, toggleTitle: { color: colors.text, fontSize: 14, lineHeight: 19, fontWeight: "800" }, toggleDescription: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 2 }, disabled: { opacity: 0.65 }, status: { alignSelf: "flex-start", paddingHorizontal: 9, paddingVertical: 5, borderRadius: 20 }, choice: { minHeight: 42, paddingHorizontal: 13, borderRadius: 13, borderWidth: 1, alignItems: "center", justifyContent: "center" }, pressed: { opacity: 0.7 }, loading: { flex: 1, justifyContent: "center", alignItems: "center", gap: 10, padding: 30 }, loadingText: { color: colors.muted, fontSize: 14, fontWeight: "700" } });
