import { useMemo } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { AdminChoice } from "@/components/edutech/admin-ui";
import { AdminOfferingOption } from "@/lib/admin/course-admin-service";
import { useEduTheme } from "@/lib/edutech/theme-context";

type StatusFilter = "all" | "active" | "inactive";
export function AdminCatalogFilters({ offerings, selectedOfferingId, onSelectOffering, status, onSelectStatus }: { offerings: AdminOfferingOption[]; selectedOfferingId: string | null; onSelectOffering: (id: string) => void; status: StatusFilter; onSelectStatus: (value: StatusFilter) => void }) { const { colors } = useEduTheme(); const styles = useMemo(() => createStyles(colors), [colors]); const levels = [...new Set(offerings.map((item) => item.levelName))]; const activeOffering = offerings.find((item) => item.id === selectedOfferingId); const sameLevel = activeOffering ? offerings.filter((item) => item.levelName === activeOffering.levelName) : offerings; return <View style={styles.root}><Text style={styles.label}>Niveau, série et matière</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.choices}>{levels.map((level) => <AdminChoice key={level} label={level} selected={activeOffering?.levelName === level} onPress={() => onSelectOffering((offerings.find((item) => item.levelName === level) ?? offerings[0])?.id ?? "")} />)}</ScrollView>{activeOffering ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.choices}>{sameLevel.map((item) => <AdminChoice key={item.id} label={`${item.seriesName} · ${item.subjectName}`} selected={item.id === selectedOfferingId} onPress={() => onSelectOffering(item.id)} />)}</ScrollView> : null}<Text style={styles.label}>État</Text><View style={styles.statuses}><AdminChoice label="Tous" selected={status === "all"} onPress={() => onSelectStatus("all")} /><AdminChoice label="Actifs" selected={status === "active"} onPress={() => onSelectStatus("active")} /><AdminChoice label="Brouillons" selected={status === "inactive"} onPress={() => onSelectStatus("inactive")} /></View></View>; }
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ root: { gap: 8 }, label: { color: colors.muted, fontSize: 12, lineHeight: 17, fontWeight: "800", marginTop: 4 }, choices: { gap: 8, paddingRight: 20 }, statuses: { flexDirection: "row", flexWrap: "wrap", gap: 8 } });
