import { supabase } from "@/lib/supabase/client";

export type AdminCoefficientOffering = { id: string; subjectName: string; levelName: string; seriesName: string; coefficientId: string | null; coefficient: number | null; isVerified: boolean; sourceName: string | null; sourceDocument: string | null; sourceReference: string | null; sourceVersion: string | null; sourceUrl: string | null };
export type AdminCoefficientInput = { offeringId: string; coefficient: string; isVerified: boolean; sourceName: string; sourceDocument: string; sourceReference: string; sourceVersion: string; sourceUrl: string };
const message = (error: unknown) => typeof error === "object" && error && "message" in error && typeof error.message === "string" ? error.message : "Une erreur de données est survenue.";
const one = <T,>(value: T | T[] | null) => Array.isArray(value) ? value[0] ?? null : value;

export async function getAdminCoefficientOfferings(): Promise<AdminCoefficientOffering[]> {
  const [{ data: offerings, error: offeringsError }, { data: coefficients, error: coefficientsError }] = await Promise.all([supabase.from("course_subject_offerings").select("id,subject:subjects!inner(name),level:levels!inner(name),series:series!inner(name)").order("display_order", { ascending: true }), supabase.from("edutech_coefficients").select("id,subject_offering_id,coefficient,is_verified,source_name,source_document,source_reference,source_version,source_url")]);
  if (offeringsError) throw new Error(message(offeringsError)); if (coefficientsError) throw new Error(message(coefficientsError)); const byOffering = new Map((coefficients ?? []).filter((row: any) => row.subject_offering_id).map((row: any) => [row.subject_offering_id, row]));
  return (offerings ?? []).flatMap((row: any) => { const subject = one<{ name: string }>(row.subject); const level = one<{ name: string }>(row.level); const series = one<{ name: string }>(row.series); if (!subject || !level || !series) return []; const coefficient = byOffering.get(row.id) as any; return [{ id: String(row.id), subjectName: subject.name, levelName: level.name, seriesName: series.name, coefficientId: coefficient?.id ?? null, coefficient: coefficient?.coefficient === null || coefficient?.coefficient === undefined ? null : Number(coefficient.coefficient), isVerified: Boolean(coefficient?.is_verified), sourceName: coefficient?.source_name ?? null, sourceDocument: coefficient?.source_document ?? null, sourceReference: coefficient?.source_reference ?? null, sourceVersion: coefficient?.source_version ?? null, sourceUrl: coefficient?.source_url ?? null }]; });
}

export async function saveAdminCoefficient(input: AdminCoefficientInput) {
  const offerings = await getAdminCoefficientOfferings(); const offering = offerings.find((item) => item.id === input.offeringId); if (!offering) throw new Error("La matière sélectionnée est introuvable."); const parsedCoefficient = input.coefficient.trim() ? Number(input.coefficient.replace(",", ".")) : null;
  if (parsedCoefficient !== null && (!(parsedCoefficient > 0) || !Number.isFinite(parsedCoefficient))) throw new Error("Le coefficient doit être un nombre strictement positif.");
  if (input.isVerified && (!parsedCoefficient || !input.sourceName.trim() || !input.sourceDocument.trim() || !input.sourceReference.trim() || !input.sourceVersion.trim())) throw new Error("Un coefficient vérifié exige une valeur, une source, un document, une référence et une version officiels.");
  const payload = { subject_offering_id: offering.id, level: offering.levelName, series: offering.seriesName, subject: offering.subjectName, assessment_type: "bulletin_subject", term: "*", coefficient: parsedCoefficient, is_verified: input.isVerified, source_name: input.sourceName.trim() || null, source_document: input.sourceDocument.trim() || null, source_reference: input.sourceReference.trim() || null, source_version: input.sourceVersion.trim() || null, source_url: input.sourceUrl.trim() || null };
  const { error } = offering.coefficientId ? await supabase.from("edutech_coefficients").update(payload).eq("id", offering.coefficientId) : await supabase.from("edutech_coefficients").insert(payload); if (error) throw new Error(message(error));
}
export async function deleteAdminCoefficient(coefficientId: string) { const { error } = await supabase.from("edutech_coefficients").delete().eq("id", coefficientId); if (error) throw new Error(message(error)); }
