import { supabase } from "@/lib/supabase/client";
import { QuizDifficulty, QuizQuestionType } from "@/lib/quizzes/quiz-model";
import { AdminChapter, AdminLesson, AdminOfferingOption, getAdminChapters, getAdminLessons, getAdminOfferingOptions } from "./course-admin-service";

export type AdminQuiz = { id: string; subjectId: string; levelId: string; seriesId: string; subjectOfferingId: string | null; chapterId: string; lessonId: string; title: string; description: string | null; difficulty: QuizDifficulty | null; durationMinutes: number | null; displayOrder: number; isPublished: boolean; isActive: boolean; isTestData: boolean; subjectName: string; chapterTitle: string; lessonTitle: string; questionCount: number; attemptCount: number; createdAt: string; updatedAt: string };
export type AdminQuizAnswer = { id: string; answer: string; isCorrect: boolean; displayOrder: number };
export type AdminQuizQuestion = { id: string; quizId: string; questionType: QuizQuestionType; promptMarkdown: string; explanationMarkdown: string | null; displayOrder: number; points: number; answers: AdminQuizAnswer[] };
export type AdminQuizInput = { offering: AdminOfferingOption; chapter: AdminChapter; lesson: AdminLesson; title: string; description: string; difficulty: QuizDifficulty | null; durationMinutes: number | null; displayOrder: number };
export type AdminQuizQuestionInput = { questionType: QuizQuestionType; promptMarkdown: string; options: string[]; correctAnswers: string[]; explanationMarkdown: string; displayOrder: number; points: number };
export type AdminQuizOverview = { studentsWithAttempts: number; submittedAttempts: number; averagePercentage: number | null; quizCount: number };
type Relation<T> = T | T[] | null;

const message = (error: unknown) => typeof error === "object" && error && "message" in error && typeof error.message === "string" ? error.message : "Une erreur Supabase est survenue.";
const one = <T,>(value: Relation<T>) => Array.isArray(value) ? value[0] ?? null : value;
const numberOrNull = (value: unknown) => value === null || value === undefined ? null : Number(value);

function from(row: any): AdminQuiz { const subject = one<{ name: string }>(row.subject); const chapter = one<{ title: string }>(row.chapter); const lesson = one<{ title: string }>(row.lesson); const questions = Array.isArray(row.quiz_questions) ? row.quiz_questions : []; const attempts = Array.isArray(row.quiz_attempts) ? row.quiz_attempts : []; return { id: String(row.id), subjectId: String(row.subject_id), levelId: String(row.level_id), seriesId: String(row.series_id), subjectOfferingId: row.subject_offering_id ?? null, chapterId: String(row.chapter_id), lessonId: String(row.lesson_id), title: String(row.title), description: row.description ?? null, difficulty: row.difficulty as QuizDifficulty | null, durationMinutes: numberOrNull(row.duration_minutes), displayOrder: Number(row.display_order ?? 0), isPublished: Boolean(row.is_published), isActive: Boolean(row.is_active), isTestData: Boolean(row.is_test_data), subjectName: subject?.name ?? "Matière", chapterTitle: chapter?.title ?? "Chapitre", lessonTitle: lesson?.title ?? "Leçon", questionCount: questions.length, attemptCount: attempts.length, createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
const selectQuiz = "id,subject_id,level_id,series_id,subject_offering_id,chapter_id,lesson_id,title,description,difficulty,duration_minutes,display_order,is_published,is_active,is_test_data,created_at,updated_at,subject:subjects(name),chapter:chapters(title),lesson:lessons(title),quiz_questions(id),quiz_attempts(id)";

export async function getAdminQuizTargets() { return getAdminOfferingOptions(); }
export async function getAdminQuizChapters(offeringId: string) { return getAdminChapters(offeringId); }
export async function getAdminQuizLessons(chapterId: string) { return getAdminLessons(chapterId); }
export async function getAdminQuizOverview(): Promise<AdminQuizOverview> { const { data, error } = await supabase.rpc("get_admin_quiz_overview"); if (error) throw new Error(message(error)); const row = Array.isArray(data) ? data[0] : data; return { studentsWithAttempts: Number(row?.students_with_attempts ?? 0), submittedAttempts: Number(row?.submitted_attempts ?? 0), averagePercentage: row?.average_percentage === null || row?.average_percentage === undefined ? null : Number(row.average_percentage), quizCount: Number(row?.quiz_count ?? 0) }; }
export async function getAdminQuizzes(): Promise<AdminQuiz[]> { const { data, error } = await supabase.from("quizzes").select(selectQuiz).order("updated_at", { ascending: false }); if (error) throw new Error(message(error)); return (data ?? []).map(from); }
export async function getAdminQuiz(quizId: string): Promise<AdminQuiz | null> { const { data, error } = await supabase.from("quizzes").select(selectQuiz).eq("id", quizId).maybeSingle(); if (error) throw new Error(message(error)); return data ? from(data) : null; }
export async function getAdminQuizQuestions(quizId: string): Promise<AdminQuizQuestion[]> { const { data, error } = await supabase.from("quiz_questions").select("id,quiz_id,question,explanation,question_type,display_order,points,quiz_answers(id,answer,is_correct,display_order)").eq("quiz_id", quizId).order("display_order", { ascending: true }); if (error) throw new Error(message(error)); return (data ?? []).map((row: any) => ({ id: String(row.id), quizId: String(row.quiz_id), questionType: row.question_type as QuizQuestionType, promptMarkdown: String(row.question ?? ""), explanationMarkdown: row.explanation ?? null, displayOrder: Number(row.display_order ?? 0), points: Number(row.points ?? 1), answers: (row.quiz_answers ?? []).sort((a: any, b: any) => Number(a.display_order ?? 0) - Number(b.display_order ?? 0)).map((answer: any) => ({ id: String(answer.id), answer: String(answer.answer), isCorrect: Boolean(answer.is_correct), displayOrder: Number(answer.display_order ?? 0) })) })); }
async function nextQuizOrder(lessonId: string) { const { data, error } = await supabase.from("quizzes").select("display_order").eq("lesson_id", lessonId).order("display_order", { ascending: false }).limit(1); if (error) throw new Error(message(error)); return Number(data?.[0]?.display_order ?? 0) + 10; }

export async function saveAdminQuiz(input: AdminQuizInput, quizId?: string) { const title = input.title.trim(); if (!title) throw new Error("Le titre du quiz est obligatoire."); const order = Number.isFinite(input.displayOrder) && input.displayOrder > 0 ? input.displayOrder : await nextQuizOrder(input.lesson.id); const basePayload = { subject_id: input.offering.subjectId, level_id: input.offering.levelId, series_id: input.offering.seriesId, subject_offering_id: input.offering.id, chapter_id: input.chapter.id, lesson_id: input.lesson.id, title, description: input.description.trim() || null, difficulty: input.difficulty, duration_minutes: input.durationMinutes, display_order: order }; const request = quizId ? supabase.from("quizzes").update(basePayload).eq("id", quizId) : supabase.from("quizzes").insert({ ...basePayload, is_published: false, is_active: false }); const { data, error } = await request.select("id").single(); if (error) throw new Error(message(error)); const quiz = await getAdminQuiz(data.id); if (!quiz) throw new Error("Le quiz enregistré est introuvable."); return quiz; }
export async function setAdminQuizAvailability(quiz: AdminQuiz, values: { isPublished: boolean; isActive: boolean }) { if (values.isPublished && quiz.questionCount === 0) throw new Error("Ajoutez au moins une question avant de publier ce quiz."); const { error } = await supabase.from("quizzes").update({ is_published: values.isPublished, is_active: values.isActive }).eq("id", quiz.id); if (error) throw new Error(message(error)); }
function validateQuestion(input: AdminQuizQuestionInput) { const prompt = input.promptMarkdown.trim(); if (!prompt) throw new Error("L’énoncé de la question est obligatoire."); if (!Number.isFinite(input.points) || input.points <= 0) throw new Error("Le nombre de points doit être supérieur à zéro."); const automatic = input.questionType === "single_choice" || input.questionType === "multiple_choice" || input.questionType === "true_false"; const optionSet = new Set(input.options); if (automatic && (input.options.length < 2 || !input.correctAnswers.length)) throw new Error("Au moins deux options et une réponse correcte sont obligatoires pour ce type de question."); if (optionSet.size !== input.options.length) throw new Error("Les options d’une question doivent être distinctes."); if (input.correctAnswers.some((answer) => automatic && !optionSet.has(answer))) throw new Error("Chaque réponse correcte doit correspondre à une option proposée."); }
async function nextQuestionOrder(quizId: string) { const { data, error } = await supabase.from("quiz_questions").select("display_order").eq("quiz_id", quizId).order("display_order", { ascending: false }).limit(1); if (error) throw new Error(message(error)); return Number(data?.[0]?.display_order ?? 0) + 10; }
export async function saveAdminQuizQuestion(quizId: string, input: AdminQuizQuestionInput, questionId?: string) { validateQuestion(input); const order = Number.isFinite(input.displayOrder) && input.displayOrder > 0 ? input.displayOrder : await nextQuestionOrder(quizId); const payload = { quiz_id: quizId, question: input.promptMarkdown.trim(), explanation: input.explanationMarkdown.trim() || null, question_type: input.questionType, display_order: order, points: input.points, is_active: true }; const request = questionId ? supabase.from("quiz_questions").update(payload).eq("id", questionId) : supabase.from("quiz_questions").insert(payload); const { data, error } = await request.select("id").single(); if (error) throw new Error(message(error)); const questionIdToSave = String(data.id); if (questionId) { const { error: deleteError } = await supabase.from("quiz_answers").delete().eq("question_id", questionIdToSave); if (deleteError) throw new Error(message(deleteError)); } const answers = input.options.map((answer, index) => ({ question_id: questionIdToSave, answer, is_correct: input.correctAnswers.includes(answer), display_order: (index + 1) * 10 })); if (answers.length) { const { error: answerError } = await supabase.from("quiz_answers").insert(answers); if (answerError) throw new Error(message(answerError)); } }
export async function deleteAdminQuizQuestion(questionId: string) { const { error } = await supabase.from("quiz_questions").delete().eq("id", questionId); if (error) throw new Error(message(error)); }
export async function deleteAdminQuiz(quiz: AdminQuiz) { if (quiz.isTestData) throw new Error("Un quiz de test protégé ne peut pas être supprimé."); if (quiz.attemptCount > 0) throw new Error("Ce quiz possède des tentatives. Désactivez-le plutôt que de le supprimer."); const { error } = await supabase.from("quizzes").delete().eq("id", quiz.id); if (error) throw new Error(message(error)); }
