import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Redirect, useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { AppScreen } from "@/components/edutech/app-screen";
import { CourseEmpty, CourseError, CourseLoading } from "@/components/edutech/course-feedback";
import { PageHeader } from "@/components/edutech/page-header";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { BulletinGrade, getBulletinSubjectGrades } from "@/lib/bulletin/bulletin-service";
import { BulletinTerm, assessmentTypeLabel, calculateSubjectAverage, formatAverage, termLabel } from "@/lib/bulletin/bulletin-model";
import { useEduTheme } from "@/lib/edutech/theme-context";

const isTerm = (value: string | undefined): value is BulletinTerm => value === "T1" || value === "T2" || value === "T3";
export default function BulletinSubjectScreen() {
  const router = useRouter(); const { offeringId, schoolYear: rawYear, term: rawTerm } = useLocalSearchParams<{ offeringId: string; schoolYear?: string; term?: string }>(); const schoolYear = rawYear ?? "2026-2027"; const term: BulletinTerm = isTerm(rawTerm) ? rawTerm : "T1"; const { isAuthenticated, profile } = useSupabaseAuth(); const { colors } = useEduTheme(); const styles = useMemo(() => createStyles(colors), [colors]); const [subjectName, setSubjectName] = useState(""); const [grades, setGrades] = useState<BulletinGrade[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!profile || !offeringId) return; setLoading(true); setError(null); try { const result = await getBulletinSubjectGrades(profile, offeringId, schoolYear, term); setSubjectName(result.subjectName); setGrades(result.grades); } catch (cause) { setError(cause instanceof Error ? cause.message : "Les notes n’ont pas pu être chargées."); } finally { setLoading(false); } }, [offeringId, profile, schoolYear, term]); useFocusEffect(useCallback(() => { void load(); }, [load]));
  if (!isAuthenticated) return <Redirect href="/auth/login" />; if (loading) return <AppScreen><CourseLoading label="Chargement des notes" /></AppScreen>; if (error) return <AppScreen><CourseError message={error} onRetry={() => void load()} /></AppScreen>;
  const average = calculateSubjectAverage(grades.map((grade) => ({ grade: grade.grade, maxGrade: grade.maxGrade, assessmentCoefficient: grade.assessmentCoefficient, includeInAverage: grade.includeInAverage })));
  return <AppScreen withPadding={false}><ScrollView contentContainerStyle={styles.content}><View style={styles.inner}><PageHeader title={subjectName || "Matière"} subtitle={`${schoolYear} · ${termLabel(term)}`} back /><View style={styles.average}><Text style={styles.averageLabel}>MOYENNE DE LA MATIÈRE</Text><Text style={styles.averageValue}>{formatAverage(average)}</Text><Text style={styles.averageMeta}>{grades.length ? `${grades.length} note${grades.length > 1 ? "s" : ""} renseignée${grades.length > 1 ? "s" : ""}` : "Aucune note renseignée"}</Text></View><Pressable accessibilityRole="button" onPress={() => router.push(`/bulletin/note/new?offeringId=${offeringId}&schoolYear=${schoolYear}&term=${term}` as any)} style={({ pressed }) => [styles.addButton, pressed && styles.pressed]}><MaterialIcons name="add" size={20} color={colors.surface} /><Text style={styles.addLabel}>Ajouter une note</Text></Pressable>{grades.length ? <View style={styles.list}>{grades.map((grade) => <Pressable key={grade.id} accessibilityRole="button" onPress={() => router.push(`/bulletin/note/${grade.id}?offeringId=${offeringId}&schoolYear=${schoolYear}&term=${term}` as any)} style={({ pressed }) => [styles.gradeCard, pressed && styles.pressed]}><View style={styles.gradeIcon}><MaterialIcons name="assignment" size={19} color={colors.primary} /></View><View style={styles.gradeCopy}><Text style={styles.gradeType}>{assessmentTypeLabel(grade.assessmentType)}</Text><Text style={styles.gradeDate}>{new Date(`${grade.assessmentDate}T12:00:00`).toLocaleDateString("fr-FR", { day: "numeric", month: "long", year: "numeric" })}</Text>{grade.comment ? <Text style={styles.gradeComment} numberOfLines={1}>{grade.comment}</Text> : null}</View><View style={styles.gradeScore}><Text style={styles.gradeValue}>{grade.grade}/{grade.maxGrade}</Text><Text style={styles.normalized}>Coef. éval. {grade.assessmentCoefficient}</Text><Text style={styles.normalized}>{grade.normalizedGrade}/20</Text></View><MaterialIcons name="chevron-right" size={20} color={colors.muted} /></Pressable>)}</View> : <CourseEmpty title="Aucune note renseignée" description="Ajoutez une note réelle obtenue à l’école pour calculer la moyenne de cette matière." actionLabel="Ajouter une note" onAction={() => router.push(`/bulletin/note/new?offeringId=${offeringId}&schoolYear=${schoolYear}&term=${term}` as any)} />}</View></ScrollView></AppScreen>;
}
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { paddingTop: 18, paddingBottom: 32 }, inner: { paddingHorizontal: 20, gap: 15 }, average: { padding: 18, borderRadius: 19, backgroundColor: colors.primarySoft }, averageLabel: { color: colors.primary, fontSize: 10, letterSpacing: 1, fontWeight: "900" }, averageValue: { color: colors.text, fontSize: 27, lineHeight: 33, fontWeight: "900", marginTop: 4 }, averageMeta: { color: colors.muted, fontSize: 11, fontWeight: "700", marginTop: 3 }, addButton: { minHeight: 47, borderRadius: 14, backgroundColor: colors.primary, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, addLabel: { color: colors.surface, fontSize: 14, fontWeight: "900" }, list: { gap: 10 }, gradeCard: { minHeight: 78, padding: 13, borderRadius: 17, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, flexDirection: "row", alignItems: "center", gap: 10 }, gradeIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: colors.primarySoft, justifyContent: "center", alignItems: "center" }, gradeCopy: { flex: 1 }, gradeType: { color: colors.text, fontSize: 13, fontWeight: "900" }, gradeDate: { color: colors.muted, fontSize: 11, marginTop: 3 }, gradeComment: { color: colors.muted, fontSize: 10, marginTop: 2 }, gradeScore: { alignItems: "flex-end" }, gradeValue: { color: colors.primary, fontSize: 14, fontWeight: "900" }, normalized: { color: colors.muted, fontSize: 10, fontWeight: "700", marginTop: 2 }, pressed: { opacity: 0.72, transform: [{ scale: 0.99 }] } });
