import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useFocusEffect, useLocalSearchParams, useRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { AppScreen } from "@/components/edutech/app-screen";
import { CourseEmpty, CourseError, CourseLoading } from "@/components/edutech/course-feedback";
import { PageHeader } from "@/components/edutech/page-header";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { ExerciseCatalogItem, ExerciseDifficulty, getExerciseCatalog, humanDifficulty, humanExerciseType, resultLabel, visibleCatalogItems } from "@/lib/exercises/exercise-service";
import { useEduTheme } from "@/lib/edutech/theme-context";
import { pedagogicalCacheContextFromProfile } from "@/lib/offline/pedagogical-cache";

type FilterState = { subjectId: string | null; chapterId: string | null; lessonId: string | null; difficulty: ExerciseDifficulty | null };
const emptyFilters: FilterState = { subjectId: null, chapterId: null, lessonId: null, difficulty: null };

export default function ExercisesScreen() {
  const router = useRouter(); const { lessonId: requestedLessonId } = useLocalSearchParams<{ lessonId?: string }>(); const { colors } = useEduTheme(); const { profile } = useSupabaseAuth(); const { id: profileId, school_level: schoolLevel, series: profileSeries, role: profileRole } = profile ?? {}; const cacheContext = useMemo(() => pedagogicalCacheContextFromProfile(profileId && schoolLevel && profileSeries && profileRole ? { id: profileId, school_level: schoolLevel, series: profileSeries, role: profileRole } : null), [profileId, schoolLevel, profileSeries, profileRole]); const styles = useMemo(() => createStyles(colors), [colors]);
  const [items, setItems] = useState<ExerciseCatalogItem[]>([]); const [filters, setFilters] = useState<FilterState>(emptyFilters); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setItems(await getExerciseCatalog({ cacheContext })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Une erreur inattendue est survenue."); } finally { setLoading(false); } }, [cacheContext]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  useEffect(() => { if (requestedLessonId) setFilters((current) => ({ ...current, lessonId: requestedLessonId })); }, [requestedLessonId]);
  const filtered = useMemo(() => visibleCatalogItems(items, filters), [filters, items]);
  const subjects = unique(items.map((item) => ({ id: item.subjectId!, label: item.subjectName }))); const chapters = unique(items.filter((item) => !filters.subjectId || item.subjectId === filters.subjectId).map((item) => ({ id: item.chapterId!, label: item.chapterTitle }))); const lessons = unique(items.filter((item) => (!filters.subjectId || item.subjectId === filters.subjectId) && (!filters.chapterId || item.chapterId === filters.chapterId)).map((item) => ({ id: item.lessonId!, label: item.lessonTitle }))); const difficulties = Array.from(new Set(items.map((item) => item.difficulty).filter((value): value is ExerciseDifficulty => Boolean(value))));
  if (loading) return <AppScreen><CourseLoading label="Chargement des exercices" /></AppScreen>;
  if (error) return <AppScreen><CourseError message={error} onRetry={() => void load()} /></AppScreen>;
  return <AppScreen withPadding={false}><FlatList data={filtered} keyExtractor={(item) => item.exerciseId} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><PageHeader title="Exercices" subtitle="Entraînez-vous avec les contenus disponibles pour votre parcours." /><Pressable accessibilityRole="button" onPress={() => router.push("/exercise/history")} style={({ pressed }) => [styles.historyButton, pressed && styles.pressed]}><MaterialIcons name="history" size={18} color={colors.primary} /><Text style={styles.historyLabel}>Mon historique</Text></Pressable>{items.length > 0 ? <Filters subjects={subjects} chapters={chapters} lessons={lessons} difficulties={difficulties} value={filters} onChange={setFilters} /> : null}{items.length > 0 ? <Text style={styles.section}>{filtered.length} exercice{filtered.length > 1 ? "s" : ""} disponible{filtered.length > 1 ? "s" : ""}</Text> : null}</View>} renderItem={({ item }) => <ExerciseCard item={item} onPress={() => router.push(`/exercise/${item.exerciseId}`)} />} ListEmptyComponent={<CourseEmpty title={items.length ? "Aucun exercice avec ces filtres" : "Aucun exercice disponible pour le moment."} description={items.length ? "Modifiez ou réinitialisez les filtres pour consulter les autres exercices disponibles." : "Les exercices publiés et actifs associés à vos leçons apparaîtront ici."} actionLabel={items.length ? "Réinitialiser les filtres" : undefined} onAction={items.length ? () => setFilters(emptyFilters) : undefined} />} /></AppScreen>;
}

function unique(values: { id: string; label: string }[]) { return Array.from(new Map(values.map((value) => [value.id, value])).values()); }
function Filters({ subjects, chapters, lessons, difficulties, value, onChange }: { subjects: { id: string; label: string }[]; chapters: { id: string; label: string }[]; lessons: { id: string; label: string }[]; difficulties: ExerciseDifficulty[]; value: FilterState; onChange: (value: FilterState) => void }) { const { colors } = useEduTheme(); const styles = useMemo(() => filterStyles(colors), [colors]); const row = (label: string, choices: { id: string; label: string }[], selected: string | null, onSelect: (id: string | null) => void) => choices.length > 1 ? <View style={styles.group}><Text style={styles.label}>{label}</Text><FlatList horizontal showsHorizontalScrollIndicator={false} data={[{ id: "", label: "Tous" }, ...choices]} keyExtractor={(item) => item.id || "all"} contentContainerStyle={styles.chips} renderItem={({ item }) => <Pressable onPress={() => onSelect(item.id || null)} style={({ pressed }) => [styles.chip, selected === (item.id || null) && styles.chipSelected, pressed && styles.pressed]}><Text style={[styles.chipText, selected === (item.id || null) && styles.chipTextSelected]} numberOfLines={1}>{item.label}</Text></Pressable>} /></View> : null; return <View style={styles.wrap}>{row("Matière", subjects, value.subjectId, (subjectId) => onChange({ subjectId, chapterId: null, lessonId: null, difficulty: value.difficulty }))}{row("Chapitre", chapters, value.chapterId, (chapterId) => onChange({ ...value, chapterId, lessonId: null }))}{row("Leçon", lessons, value.lessonId, (lessonId) => onChange({ ...value, lessonId }))}{difficulties.length > 1 ? row("Difficulté", difficulties.map((item) => ({ id: item, label: humanDifficulty(item) ?? item })), value.difficulty, (difficulty) => onChange({ ...value, difficulty: difficulty as ExerciseDifficulty | null })) : null}</View>; }
function ExerciseCard({ item, onPress }: { item: ExerciseCatalogItem; onPress: () => void }) { const { colors } = useEduTheme(); const styles = useMemo(() => cardStyles(colors), [colors]); return <Pressable accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.top}><View style={styles.icon}><MaterialIcons name="edit-note" size={22} color={colors.primary} /></View><View style={styles.copy}><Text style={styles.subject}>{item.subjectName} · {item.chapterTitle}</Text><Text style={styles.title}>{item.title}</Text><Text style={styles.lesson}>{item.lessonTitle}</Text></View><MaterialIcons name="chevron-right" size={23} color={colors.muted} /></View><View style={styles.meta}>{item.difficulty ? <Text style={styles.metaText}>{humanDifficulty(item.difficulty)}</Text> : null}<Text style={styles.metaText}>{humanExerciseType(item.exerciseType)}</Text>{item.estimatedDurationMinutes ? <Text style={styles.metaText}>{item.estimatedDurationMinutes} min</Text> : null}</View><View style={styles.status}><Text style={styles.statusLabel}>{resultLabel(item.lastStatus, item.lastPercentage)}</Text>{item.attemptCount ? <Text style={styles.attempts}>{item.attemptCount} tentative{item.attemptCount > 1 ? "s" : ""}</Text> : null}</View></Pressable>; }

const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 18, paddingBottom: 28, gap: 10 }, header: { marginBottom: 8 }, historyButton: { alignSelf: "flex-start", minHeight: 40, marginTop: 14, paddingHorizontal: 12, borderRadius: 12, backgroundColor: colors.primarySoft, flexDirection: "row", alignItems: "center", gap: 7 }, historyLabel: { color: colors.primary, fontSize: 12, fontWeight: "900" }, section: { color: colors.text, marginTop: 23, fontSize: 15, fontWeight: "900" }, pressed: { opacity: 0.72 } });
const filterStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ wrap: { gap: 13, marginTop: 18 }, group: { gap: 7 }, label: { color: colors.text, fontSize: 12, fontWeight: "900" }, chips: { gap: 8, paddingRight: 20 }, chip: { maxWidth: 180, minHeight: 34, justifyContent: "center", paddingHorizontal: 11, borderRadius: 99, backgroundColor: colors.surfaceMuted }, chipSelected: { backgroundColor: colors.primary }, chipText: { color: colors.muted, fontSize: 12, fontWeight: "800" }, chipTextSelected: { color: colors.surface }, pressed: { opacity: 0.72 } });
const cardStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ card: { padding: 14, borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, gap: 12 }, top: { flexDirection: "row", alignItems: "center", gap: 11 }, icon: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" }, copy: { flex: 1 }, subject: { color: colors.muted, fontSize: 11, lineHeight: 15, fontWeight: "800" }, title: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: "900", marginTop: 2 }, lesson: { color: colors.muted, fontSize: 11, lineHeight: 15, marginTop: 2 }, meta: { flexDirection: "row", gap: 7, flexWrap: "wrap" }, metaText: { color: colors.primary, backgroundColor: colors.primarySoft, borderRadius: 8, overflow: "hidden", paddingHorizontal: 7, paddingVertical: 4, fontSize: 10, lineHeight: 13, fontWeight: "900" }, status: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 10 }, statusLabel: { color: colors.success, fontSize: 12, fontWeight: "900" }, attempts: { color: colors.muted, fontSize: 11, fontWeight: "700" }, pressed: { opacity: 0.72 } });
