import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useMemo } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { PageHeader } from "@/components/edutech/page-header";
import { PrimaryButton } from "@/components/edutech/primary-button";
import { SettingsRow } from "@/components/edutech/settings-row";
import { useEduTheme } from "@/lib/edutech/theme-context";
export default function ProfileScreen() { const router = useRouter(); const { colors } = useEduTheme(); const styles = useMemo(() => createStyles(colors), [colors]); return <AppScreen withPadding={false}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}><View style={styles.content}><PageHeader title="Profil" subtitle="Vos informations seront synchronisées après connexion." /><View style={styles.profileCard}><View style={styles.avatar}><MaterialIcons name="person-outline" size={32} color={colors.primary} /></View><View style={styles.profileCopy}><Text style={styles.profileTitle}>Profil en attente</Text><Text style={styles.profileSub}>Connexion nécessaire pour afficher votre nom et votre adresse e-mail.</Text></View></View><Text style={styles.section}>Parcours scolaire</Text><View style={styles.details}><DetailRow icon="school" label="Niveau scolaire" value="À renseigner après connexion" /><DetailRow icon="account-tree" label="Série" value="À renseigner après connexion" /><DetailRow icon="insights" label="Progression" value="Aucune activité enregistrée" /></View><Text style={styles.section}>Compte</Text><View style={styles.rows}><SettingsRow icon="settings" title="Paramètres" subtitle="Thème et informations de l’application" onPress={() => router.push("/settings")} /><SettingsRow icon="admin-panel-settings" title="Administration" subtitle="Espace préparé pour une prochaine étape" onPress={() => router.push("/administration")} /></View><PrimaryButton label="Déconnexion" variant="danger" icon={<MaterialIcons name="logout" size={19} color={colors.surface} />} onPress={() => router.replace("/auth/login")} style={styles.logout} /></View></ScrollView></AppScreen>; }
function DetailRow({ icon, label, value }: { icon: "school" | "account-tree" | "insights"; label: string; value: string }) { const { colors } = useEduTheme(); const styles = useMemo(() => detailStyles(colors), [colors]); return <View style={styles.row}><MaterialIcons name={icon} size={20} color={colors.primary} /><View style={styles.copy}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View></View>; }
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ scroll: { paddingBottom: 30 }, content: { paddingHorizontal: 20, paddingTop: 20 }, profileCard: { flexDirection: "row", gap: 14, borderRadius: 20, backgroundColor: colors.primarySoft, padding: 17, alignItems: "center" }, avatar: { width: 58, height: 58, borderRadius: 20, alignItems: "center", justifyContent: "center", backgroundColor: colors.surface }, profileCopy: { flex: 1 }, profileTitle: { color: colors.text, fontSize: 17, lineHeight: 22, fontWeight: "800" }, profileSub: { color: colors.muted, fontSize: 13, lineHeight: 18, marginTop: 3 }, section: { color: colors.text, fontSize: 16, lineHeight: 21, fontWeight: "800", marginTop: 27, marginBottom: 10 }, details: { borderRadius: 18, overflow: "hidden", borderWidth: 1, borderColor: colors.border }, rows: { borderRadius: 18, overflow: "hidden", borderWidth: 1, borderColor: colors.border }, logout: { marginTop: 27 } });
const detailStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ row: { minHeight: 64, flexDirection: "row", alignItems: "center", gap: 12, padding: 13, backgroundColor: colors.surface, borderBottomWidth: 1, borderBottomColor: colors.border }, copy: { flex: 1 }, label: { color: colors.text, fontSize: 14, lineHeight: 19, fontWeight: "700" }, value: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 1 } });
