import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useMemo } from "react";
import { ActivityIndicator, Image, ScrollView, StyleSheet, Text, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { EmptyState } from "@/components/edutech/empty-state";
import { PageHeader } from "@/components/edutech/page-header";
import { PrimaryButton } from "@/components/edutech/primary-button";
import { SettingsRow } from "@/components/edutech/settings-row";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { useEduTheme } from "@/lib/edutech/theme-context";
import { useNotificationInbox } from "@/lib/notifications/notification-sync-context";

export default function ProfileScreen() {
  const router = useRouter(); const { colors } = useEduTheme(); const { user, profile, isAdmin, isProfileLoading, profileError, refreshProfile, signOut } = useSupabaseAuth(); const { unreadCount } = useNotificationInbox(); const styles = useMemo(() => createStyles(colors), [colors]);
  const logout = async () => { await signOut(); };
  if (isProfileLoading && !profile) return <AppScreen><View style={styles.loading}><ActivityIndicator color={colors.primary} /><Text style={styles.loadingText}>Chargement de votre profil</Text></View></AppScreen>;
  if (!profile) { const isError = Boolean(profileError); return <AppScreen edges={["top", "bottom", "left", "right"]}><View style={styles.emptyScreen}><View><PageHeader title="Profil" subtitle="Vos informations personnelles et scolaires." /><EmptyState icon="person-outline" title={isError ? "Erreur de chargement" : "Profil en cours de création"} description={profileError ?? "Votre profil n’est pas encore disponible. Réessayez dans quelques instants."} /></View><PrimaryButton label={isError ? "Réessayer" : "Actualiser"} onPress={() => void refreshProfile()} /></View></AppScreen>; }
  const displayName = profile.full_name || [profile.first_name, profile.last_name].filter(Boolean).join(" ") || "Élève";
  return <AppScreen withPadding={false}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scroll}><View style={styles.content}><PageHeader title="Profil" subtitle="Vos informations personnelles et scolaires." /><View style={styles.profileCard}><View style={styles.avatar}>{profile.avatar_url ? <Image source={{ uri: profile.avatar_url }} style={styles.avatarImage} /> : <MaterialIcons name="person-outline" size={32} color={colors.primary} />}</View><View style={styles.profileCopy}><Text style={styles.profileTitle}>{displayName}</Text><Text style={styles.profileSub}>{user?.email ?? profile.email}</Text></View></View><PrimaryButton label="Modifier mon profil" variant="secondary" icon={<MaterialIcons name="edit" size={18} color={colors.primary} />} onPress={() => router.push("/profile/edit")} style={styles.editButton} /><Text style={styles.section}>Parcours scolaire</Text><View style={styles.details}><DetailRow icon="school" label="Niveau scolaire" value={profile.school_level || "Non renseigné"} /><DetailRow icon="account-tree" label="Série" value={profile.series || "Non renseignée"} /><DetailRow icon="insights" label="Progression" value="Aucune activité enregistrée" /></View><Text style={styles.section}>Compte</Text><View style={styles.rows}><SettingsRow icon="notifications-none" title="Notifications" subtitle={unreadCount ? `${unreadCount} notification${unreadCount > 1 ? "s" : ""} non lue${unreadCount > 1 ? "s" : ""}` : "Aucune notification non lue"} onPress={() => router.push("/notifications")} /><SettingsRow icon="settings" title="Paramètres" subtitle="Thème et informations de l’application" onPress={() => router.push("/settings")} />{isAdmin ? <SettingsRow icon="admin-panel-settings" title="Administration" subtitle="Espace réservé aux administrateurs" onPress={() => router.push("/administration")} /> : null}</View><PrimaryButton label="Déconnexion" variant="danger" icon={<MaterialIcons name="logout" size={19} color={colors.surface} />} onPress={logout} style={styles.logout} /></View></ScrollView></AppScreen>;
}
function DetailRow({ icon, label, value }: { icon: "school" | "account-tree" | "insights"; label: string; value: string }) { const { colors } = useEduTheme(); const styles = useMemo(() => detailStyles(colors), [colors]); return <View style={styles.row}><MaterialIcons name={icon} size={20} color={colors.primary} /><View style={styles.copy}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View></View>; }
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ scroll: { paddingBottom: 30 }, content: { paddingHorizontal: 20, paddingTop: 20 }, loading: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12 }, loadingText: { color: colors.muted, fontSize: 14, fontWeight: "700" }, emptyScreen: { flex: 1, justifyContent: "space-between", paddingVertical: 18 }, profileCard: { flexDirection: "row", gap: 14, borderRadius: 20, backgroundColor: colors.primarySoft, padding: 17, alignItems: "center" }, avatar: { width: 58, height: 58, borderRadius: 20, overflow: "hidden", alignItems: "center", justifyContent: "center", backgroundColor: colors.surface }, avatarImage: { width: "100%", height: "100%" }, profileCopy: { flex: 1 }, profileTitle: { color: colors.text, fontSize: 17, lineHeight: 22, fontWeight: "800" }, profileSub: { color: colors.muted, fontSize: 13, lineHeight: 18, marginTop: 3 }, editButton: { marginTop: 13 }, section: { color: colors.text, fontSize: 16, lineHeight: 21, fontWeight: "800", marginTop: 27, marginBottom: 10 }, details: { borderRadius: 18, overflow: "hidden", borderWidth: 1, borderColor: colors.border }, rows: { borderRadius: 18, overflow: "hidden", borderWidth: 1, borderColor: colors.border }, logout: { marginTop: 27 } });
const detailStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ row: { minHeight: 64, flexDirection: "row", alignItems: "center", gap: 12, padding: 13, backgroundColor: colors.surface, borderBottomWidth: 1, borderBottomColor: colors.border }, copy: { flex: 1 }, label: { color: colors.text, fontSize: 14, lineHeight: 19, fontWeight: "700" }, value: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 1 } });
