import { Redirect, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { EmptyState } from "@/components/edutech/empty-state";
import { PageHeader } from "@/components/edutech/page-header";
import { getAdminStudents, getStudentSchoolHistory, type AdminStudent, type SchoolHistory } from "@/lib/admin/school-administration-service";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { useEduTheme } from "@/lib/edutech/theme-context";

export default function AdminStudentDetailScreen() {
  const { studentId } = useLocalSearchParams<{ studentId: string }>(); const { isAdmin } = useSupabaseAuth(); const { colors } = useEduTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); const [student, setStudent] = useState<AdminStudent | null>(null); const [history, setHistory] = useState<SchoolHistory[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!studentId) return; setLoading(true); try { const [users, records] = await Promise.all([getAdminStudents(), getStudentSchoolHistory(studentId)]); setStudent(users.find((item) => item.id === studentId) ?? null); setHistory(records); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Chargement impossible."); } finally { setLoading(false); } }, [studentId]);
  useEffect(() => { void load(); }, [load]);
  if (!isAdmin) return <Redirect href="/(tabs)" />; if (loading) return <AppScreen><ActivityIndicator color={colors.primary} /></AppScreen>; if (!student) return <AppScreen><PageHeader title="Utilisateur" back /><EmptyState icon="person-off" title="Utilisateur indisponible" description={error ?? "Le compte demandé n’est pas accessible."} /></AppScreen>;
  return <AppScreen withPadding={false}><ScrollView contentContainerStyle={styles.content}><PageHeader title="Fiche utilisateur" subtitle="Données nécessaires à la gestion scolaire" back /><View style={styles.card}><Text style={styles.name}>{student.fullName}</Text><Text style={styles.email}>{student.email}</Text><Line label="Rôle" value={student.role === "admin" ? "Administrateur" : "Élève"} /><Line label="Statut" value={student.isActive ? "Actif" : "Inactif"} /><Line label="Année scolaire" value={student.schoolYear ?? "Non renseignée"} /><Line label="Niveau / série" value={`${student.schoolLevel ?? "Non renseigné"} ${student.series ?? ""}`} /><Line label="LV2" value={student.lv2Choice ?? "Non renseignée"} /><Line label="Moyenne T1" value={student.t1Average === null ? "Non évaluée" : `${student.t1Average}/20`} /><Line label="Moyenne T2" value={student.t2Average === null ? "Non évaluée" : `${student.t2Average}/20`} /><Line label="Moyenne T3" value={student.t3Average === null ? "Non évaluée" : `${student.t3Average}/20`} /><Line label="Moyenne annuelle" value={student.annualAverage === null ? "Non évaluée" : `${student.annualAverage}/20`} /><Line label="Décision" value={student.promotionDecision === "admitted" ? "Admis" : student.promotionDecision === "repeat" ? "Redouble" : "Décision en attente"} /></View><Text style={styles.heading}>Historique scolaire</Text>{history.length ? history.map((item) => <View key={item.id} style={styles.history}><Text style={styles.historyTitle}>{item.schoolYear} · {item.schoolLevel} {item.series}</Text><Text style={styles.historyText}>LV2 : {item.lv2Choice ?? "Non renseignée"} · Moyenne annuelle : {item.annualAverage === null ? "Non évaluée" : `${item.annualAverage}/20`}</Text><Text style={styles.historyText}>Décision : {item.promotionDecision === "admitted" ? "Admis" : item.promotionDecision === "repeat" ? "Redouble" : "En attente"}</Text></View>) : <Text style={styles.empty}>Aucun historique scolaire n’est encore enregistré.</Text>}</ScrollView></AppScreen>;
}
function Line({ label, value }: { label: string; value: string }) { const { colors } = useEduTheme(); return <View style={{ flexDirection: "row", justifyContent: "space-between", gap: 12, paddingVertical: 9, borderTopWidth: 1, borderTopColor: colors.border }}><Text style={{ color: colors.muted, fontSize: 12, fontWeight: "700" }}>{label}</Text><Text style={{ color: colors.text, fontSize: 12, fontWeight: "800", textAlign: "right", flex: 1 }}>{value}</Text></View>; }
const makeStyles = (c: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { padding: 20, paddingTop: 18, paddingBottom: 34, gap: 12 }, card: { borderWidth: 1, borderColor: c.border, backgroundColor: c.surface, borderRadius: 18, padding: 14 }, name: { color: c.text, fontSize: 18, fontWeight: "900" }, email: { color: c.muted, fontSize: 12, marginTop: 3, marginBottom: 10 }, heading: { color: c.text, fontSize: 16, fontWeight: "900", marginTop: 8 }, history: { borderWidth: 1, borderColor: c.border, backgroundColor: c.surface, borderRadius: 16, padding: 13, gap: 4 }, historyTitle: { color: c.text, fontSize: 13, fontWeight: "900" }, historyText: { color: c.muted, fontSize: 11, lineHeight: 16, fontWeight: "700" }, empty: { color: c.muted, fontSize: 12, fontWeight: "700", padding: 14, textAlign: "center" } });
