import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Redirect, useLocalSearchParams, useRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { AdminField, AdminLoading, AdminNotice, AdminToggle } from "@/components/edutech/admin-ui";
import { PageHeader } from "@/components/edutech/page-header";
import { PrimaryButton } from "@/components/edutech/primary-button";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { AdminChapter, AdminOfferingOption, deleteAdminChapter, getAdminChapter, getAdminOfferingOptions, getChapterDependencySummary, saveAdminChapter } from "@/lib/admin/course-admin-service";
import { useEduTheme } from "@/lib/edutech/theme-context";

export default function AdminChapterEditor() { const { chapterId, offeringId } = useLocalSearchParams<{ chapterId: string; offeringId?: string }>(); const router = useRouter(); const { isAdmin } = useSupabaseAuth(); const { colors } = useEduTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); const creating = chapterId === "new"; const [chapter, setChapter] = useState<AdminChapter | null>(null); const [offering, setOffering] = useState<AdminOfferingOption | null>(null); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [displayOrder, setDisplayOrder] = useState("0"); const [isActive, setIsActive] = useState(true); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const allOfferings = await getAdminOfferingOptions(); if (creating) { const selected = allOfferings.find((item) => item.id === offeringId); if (!selected) { setError("Sélectionnez d’abord une offre de matière pour créer un chapitre."); return; } setOffering(selected); return; } const item = await getAdminChapter(chapterId); if (!item) { setError("Ce chapitre n’est plus disponible."); return; } const selected = allOfferings.find((entry) => entry.id === item.subjectOfferingId); if (!selected) { setError("L’offre associée à ce chapitre est indisponible."); return; } setChapter(item); setOffering(selected); setTitle(item.title); setDescription(item.description ?? ""); setDisplayOrder(String(item.displayOrder)); setIsActive(item.isActive); } catch (cause) { setError(cause instanceof Error ? cause.message : "Le chapitre n’a pas pu être chargé."); } finally { setLoading(false); } }, [chapterId, creating, offeringId]);
  useEffect(() => { void load(); }, [load]); const persist = async (nextActive = isActive) => { if (!offering) return; setSaving(true); setError(null); setNotice(null); try { const saved = await saveAdminChapter({ offering, title, description, displayOrder: Number(displayOrder) || 0, isActive: nextActive }, creating ? undefined : chapterId); setChapter(saved); setIsActive(saved.isActive); setNotice("Chapitre enregistré dans Supabase."); if (creating) router.replace(`/administration/chapters/${saved.id}` as any); } catch (cause) { setError(cause instanceof Error ? cause.message : "Le chapitre n’a pas pu être enregistré."); } finally { setSaving(false); } };
  const remove = async () => { if (!chapter) return; try { const { lessons } = await getChapterDependencySummary(chapter.id); if (chapter.isTestData) { setError("Le chapitre de test est protégé contre la suppression."); return; } if (lessons) { Alert.alert("Suppression sécurisée", `Ce chapitre contient ${lessons} leçon(s). Désactivez-le plutôt pour préserver son contenu.`, [{ text: "Annuler", style: "cancel" }, { text: "Désactiver", onPress: () => void persist(false) }]); return; } Alert.alert("Supprimer ce chapitre ?", "Cette action est irréversible.", [{ text: "Annuler", style: "cancel" }, { text: "Supprimer", style: "destructive", onPress: async () => { try { await deleteAdminChapter(chapter); router.replace("/administration/chapters" as any); } catch (cause) { setError(cause instanceof Error ? cause.message : "La suppression a échoué."); } } }]); } catch (cause) { setError(cause instanceof Error ? cause.message : "Les dépendances n’ont pas pu être vérifiées."); } };
  if (!isAdmin) return <Redirect href="/(tabs)" />; if (loading) return <AppScreen><AdminLoading label="Chargement du chapitre…" /></AppScreen>;
  return <AppScreen edges={["top", "bottom", "left", "right"]}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === "ios" ? "padding" : undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><PageHeader title={creating ? "Nouveau chapitre" : "Modifier le chapitre"} subtitle={offering?.label ?? "Offre de matière"} back /><View style={styles.form}>{offering ? <View style={styles.target}><MaterialIcons name="account-tree" size={19} color={colors.primary} /><Text style={styles.targetText}>Rattaché à {offering.label}</Text></View> : null}<AdminField label="Titre" value={title} onChange={setTitle} placeholder="Ex. La justice" /><AdminField label="Description" value={description} onChange={setDescription} multiline required={false} placeholder="Présentation du chapitre" /><AdminField label="Ordre d’affichage" value={displayOrder} onChange={setDisplayOrder} keyboardType="numeric" placeholder="0 = prochain ordre disponible" /><AdminToggle label="Chapitre actif" description="Un chapitre inactif est visible ici uniquement." value={isActive} onChange={setIsActive} />{chapter?.isTestData ? <AdminNotice tone="warning">Les données de test du moteur de cours restent protégées.</AdminNotice> : null}{notice ? <AdminNotice tone="success">{notice}</AdminNotice> : null}{error ? <AdminNotice tone="error">{error}</AdminNotice> : null}<PrimaryButton label={creating ? "Créer le chapitre" : "Enregistrer les modifications"} onPress={() => void persist()} loading={saving} icon={<MaterialIcons name="save" size={19} color={colors.surface} />} />{!creating && chapter && !chapter.isTestData ? <PrimaryButton label="Supprimer ou désactiver" variant="danger" onPress={() => void remove()} icon={<MaterialIcons name="delete-outline" size={19} color={colors.surface} />} /> : null}<Text style={styles.help}>Un ordre déjà utilisé dans cette matière doit être ajusté avant sauvegarde. Utilisez un nombre distinct pour préserver l’ordre élève.</Text></View></ScrollView></KeyboardAvoidingView></AppScreen>; }
const makeStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ flex: { flex: 1 }, content: { paddingTop: 18, paddingBottom: 28 }, form: { gap: 13 }, target: { flexDirection: "row", gap: 9, alignItems: "center", borderRadius: 15, padding: 13, backgroundColor: colors.primarySoft }, targetText: { flex: 1, color: colors.primary, fontSize: 13, lineHeight: 18, fontWeight: "800" }, help: { color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: "center", paddingHorizontal: 8 } });
