import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Redirect, useRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { AdminCatalogFilters } from "@/components/edutech/admin-filter-bar";
import { AdminLoading, AdminNotice, AdminStatus } from "@/components/edutech/admin-ui";
import { EmptyState } from "@/components/edutech/empty-state";
import { PageHeader } from "@/components/edutech/page-header";
import { PrimaryButton } from "@/components/edutech/primary-button";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { AdminChapter, AdminOfferingOption, getAdminChapters, getAdminOfferingOptions } from "@/lib/admin/course-admin-service";
import { useEduTheme } from "@/lib/edutech/theme-context";

type StatusFilter = "all" | "active" | "inactive";
export default function AdminChaptersScreen() { const router = useRouter(); const { isAdmin } = useSupabaseAuth(); const { colors } = useEduTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); const [offerings, setOfferings] = useState<AdminOfferingOption[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [chapters, setChapters] = useState<AdminChapter[]>([]); const [status, setStatus] = useState<StatusFilter>("all"); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const loadOfferings = useCallback(async () => { try { const next = await getAdminOfferingOptions(); setOfferings(next); setSelectedId((current) => current && next.some((item) => item.id === current) ? current : next[0]?.id ?? null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Les offres n’ont pas pu être chargées."); } finally { setLoading(false); } }, []);
  const loadChapters = useCallback(async () => { if (!selectedId) { setChapters([]); return; } try { setError(null); setChapters(await getAdminChapters(selectedId)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Les chapitres n’ont pas pu être chargés."); } }, [selectedId]);
  useEffect(() => { void loadOfferings(); }, [loadOfferings]); useEffect(() => { void loadChapters(); }, [loadChapters]); const selected = offerings.find((item) => item.id === selectedId); const visible = useMemo(() => chapters.filter((item) => status === "all" || status === "active" ? item.isActive : !item.isActive), [chapters, status]);
  if (!isAdmin) return <Redirect href="/(tabs)" />; if (loading) return <AppScreen><AdminLoading label="Chargement des chapitres…" /></AppScreen>;
  return <AppScreen edges={["top", "bottom", "left", "right"]} withPadding={false}><FlatList data={visible} keyExtractor={(item) => item.id} refreshControl={<RefreshControl refreshing={loading} onRefresh={() => { setLoading(true); void loadOfferings().then(loadChapters); }} tintColor={colors.primary} />} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><PageHeader title="Chapitres" subtitle="Contenus rattachés à une offre précise" back /><AdminCatalogFilters offerings={offerings} selectedOfferingId={selectedId} onSelectOffering={setSelectedId} status={status} onSelectStatus={setStatus} />{selected ? <PrimaryButton label="Nouveau chapitre" onPress={() => router.push({ pathname: "/administration/chapters/new" as any, params: { offeringId: selected.id } })} icon={<MaterialIcons name="add" size={20} color={colors.surface} />} /> : null}{error ? <AdminNotice tone="error">{error}</AdminNotice> : null}</View>} renderItem={({ item }) => <Pressable accessibilityRole="button" accessibilityLabel={`Modifier ${item.title}`} onPress={() => router.push(`/administration/chapters/${item.id}` as any)} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={styles.number}><Text style={styles.numberText}>{item.displayOrder}</Text></View><View style={styles.copy}><Text style={styles.title}>{item.title}</Text><Text style={styles.description} numberOfLines={2}>{item.description || "Aucune description"}</Text><View style={styles.meta}><AdminStatus active={item.isActive} /><Text style={styles.order}>Ordre {item.displayOrder}</Text>{item.isTestData ? <Text style={styles.test}>Donnée de test</Text> : null}</View></View><MaterialIcons name="chevron-right" size={24} color={colors.muted} /></Pressable>} ListEmptyComponent={<EmptyState icon="format-list-numbered" title="Aucun chapitre" description={selected ? "Créez le premier chapitre ou modifiez les filtres." : "Sélectionnez une offre de matière."} />} /></AppScreen>; }
const makeStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { padding: 20, paddingTop: 18, paddingBottom: 30, gap: 10, flexGrow: 1 }, header: { gap: 13, marginBottom: 4 }, row: { flexDirection: "row", alignItems: "center", gap: 12, padding: 13, borderRadius: 17, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, number: { width: 40, height: 40, borderRadius: 13, justifyContent: "center", alignItems: "center", backgroundColor: colors.primarySoft }, numberText: { color: colors.primary, fontSize: 13, fontWeight: "900" }, copy: { flex: 1 }, title: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: "800" }, description: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 2 }, meta: { flexDirection: "row", gap: 7, alignItems: "center", flexWrap: "wrap", marginTop: 8 }, order: { color: colors.muted, fontSize: 11, fontWeight: "700" }, test: { color: colors.warning, fontSize: 11, fontWeight: "800" }, pressed: { opacity: 0.7 } });
