import { Redirect } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, FlatList, StyleSheet, Text, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { EmptyState } from "@/components/edutech/empty-state";
import { PageHeader } from "@/components/edutech/page-header";
import { PrimaryButton } from "@/components/edutech/primary-button";
import { getClassChangeRequests, reviewClassChangeRequest, type ClassChangeRequest } from "@/lib/admin/school-administration-service";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { useEduTheme } from "@/lib/edutech/theme-context";

export default function AdminClassRequestsScreen() {
  const { isAdmin } = useSupabaseAuth(); const { colors } = useEduTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); const [requests, setRequests] = useState<ClassChangeRequest[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { setRequests(await getClassChangeRequests("all")); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Chargement impossible."); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  const review = (request: ClassChangeRequest, accept: boolean) => Alert.alert(accept ? "Accepter la demande ?" : "Refuser la demande ?", accept ? "Le profil scolaire sera mis à jour et l’historique sera conservé." : "Le profil de l’élève ne sera pas modifié. La demande restera dans l’historique.", [{ text: "Annuler", style: "cancel" }, { text: "Confirmer", style: accept ? "default" : "destructive", onPress: () => { void (async () => { try { setBusy(request.id); await reviewClassChangeRequest(request.id, accept); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Action impossible."); } finally { setBusy(null); } })(); } }]);
  if (!isAdmin) return <Redirect href="/(tabs)" />; return <AppScreen withPadding={false}><FlatList data={requests} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><PageHeader title="Demandes de classe" subtitle="Validation des demandes après la première modification annuelle" back />{error ? <Text style={styles.error}>{error}</Text> : null}</View>} ListEmptyComponent={loading ? <Text style={styles.muted}>Chargement des demandes…</Text> : <EmptyState icon="swap-horiz" title="Aucune demande" description="Les demandes de changement de classe des élèves apparaîtront ici." />} renderItem={({ item }) => <View style={styles.card}><Text style={styles.year}>{item.schoolYear} · {item.status === "pending" ? "En attente" : item.status === "accepted" ? "Acceptée" : item.status === "rejected" ? "Refusée" : "Approuvée automatiquement"}</Text><Text style={styles.change}>{item.oldSchoolLevel} {item.oldSeries} → {item.newSchoolLevel} {item.newSeries}</Text><Text style={styles.meta}>Élève : {item.studentName ?? "Nom indisponible"}{item.studentEmail ? ` · ${item.studentEmail}` : ""}</Text><Text style={styles.meta}>Motif : {item.reason ?? "Non renseigné"}</Text>{item.status === "pending" ? <View style={styles.actions}><PrimaryButton label="Refuser" variant="danger" disabled={busy === item.id} onPress={() => review(item, false)} style={styles.action} /><PrimaryButton label="Accepter" disabled={busy === item.id} onPress={() => review(item, true)} style={styles.action} /></View> : null}</View>} /></AppScreen>;
}
const makeStyles = (c: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { padding: 20, paddingTop: 18, paddingBottom: 34, gap: 10, flexGrow: 1 }, header: { gap: 10, marginBottom: 4 }, error: { color: c.error, padding: 10, borderRadius: 12, backgroundColor: `${c.error}12`, fontSize: 12, fontWeight: "700" }, muted: { color: c.muted, textAlign: "center", paddingVertical: 50, fontWeight: "700" }, card: { padding: 14, borderWidth: 1, borderColor: c.border, backgroundColor: c.surface, borderRadius: 18, gap: 6 }, year: { color: c.primary, fontSize: 11, fontWeight: "900" }, change: { color: c.text, fontSize: 15, fontWeight: "900" }, meta: { color: c.muted, fontSize: 11, lineHeight: 16, fontWeight: "700" }, actions: { flexDirection: "row", gap: 8, marginTop: 4 }, action: { flex: 1, minHeight: 42, paddingHorizontal: 8 } });
