import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Redirect } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { PageHeader } from "@/components/edutech/page-header";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { useEduTheme } from "@/lib/edutech/theme-context";
import { getMentorSettings, saveMentorSettings, testActiveMentorKey, testPendingMentorKey, type MentorSettingsSummary } from "@/lib/mentor/mentor-service";

const labelFor = (status: MentorSettingsSummary["status"]) => status === "valid" ? "Clé valide et service disponible" : status === "quota" ? "Quota temporairement atteint" : status === "invalid" ? "Clé invalide" : status === "unavailable" ? "Service indisponible" : "Non vérifiée";
const errorText = (error: unknown) => error instanceof Error ? error.message : "La demande a échoué.";

export default function MentorAdministrationScreen() {
  const { isAdmin, isReady } = useSupabaseAuth(); const { colors } = useEduTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); const [settings, setSettings] = useState<MentorSettingsSummary | null>(null); const [key, setKey] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<"test" | "save" | "active" | null>(null); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async () => { setLoading(true); try { setSettings(await getMentorSettings()); setError(null); } catch (cause) { setError(errorText(cause)); } finally { setLoading(false); } }, []);
  useEffect(() => { if (isAdmin) void refresh(); }, [isAdmin, refresh]);
  if (!isReady) return <AppScreen><View style={styles.center}><ActivityIndicator color={colors.primary} /></View></AppScreen>;
  if (!isAdmin) return <Redirect href="/(tabs)/profile" />;
  const testNew = async () => { if (!key.trim()) { setError("Saisissez une clé Gemini avant de la tester."); return; } setBusy("test"); setNotice(null); setError(null); try { setNotice((await testPendingMentorKey(key.trim())).message); } catch (cause) { setError(errorText(cause)); } finally { setBusy(null); } };
  const save = async () => { if (!key.trim()) { setError("Saisissez une clé Gemini avant de l’enregistrer."); return; } setBusy("save"); setNotice(null); setError(null); try { setSettings(await saveMentorSettings(key.trim())); setKey(""); setNotice("Clé enregistrée de manière sécurisée. Seul son suffixe masqué est affiché."); } catch (cause) { setError(errorText(cause)); } finally { setBusy(null); } };
  const testActive = async () => { setBusy("active"); setNotice(null); setError(null); try { setNotice((await testActiveMentorKey()).message); await refresh(); } catch (cause) { setError(errorText(cause)); await refresh(); } finally { setBusy(null); } };
  const state = settings?.status ?? "unknown";
  return <AppScreen withPadding={false}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.scroll}><View style={styles.inner}><PageHeader title="Paramètres Mentor IA" subtitle="Administration · Google Gemini" back />{loading ? <View style={styles.center}><ActivityIndicator color={colors.primary} /></View> : <><View style={styles.card}><Text style={styles.label}>Fournisseur</Text><Text style={styles.value}>Google Gemini</Text><Text style={styles.label}>Modèle</Text><Text style={styles.value}>gemini-2.5-flash-lite</Text><Text style={styles.label}>Clé active</Text><Text style={styles.value}>{settings?.keyMask ?? "Aucune clé configurée"}</Text><View style={styles.status}><View style={[styles.dot, { backgroundColor: state === "valid" ? colors.success : state === "quota" ? colors.warning : state === "invalid" || state === "unavailable" ? colors.error : colors.muted }]} /><Text style={styles.statusText}>{labelFor(state)}</Text></View><Text style={styles.help}>{settings?.lastCheckedAt ? `Dernière vérification : ${new Date(settings.lastCheckedAt).toLocaleString("fr-FR")}` : "Aucune vérification enregistrée."}</Text></View><View style={styles.card}><Text style={styles.title}>Remplacer la clé active</Text><Text style={styles.help}>La clé est envoyée uniquement au backend sécurisé, chiffrée puis jamais renvoyée à l’application.</Text><TextInput value={key} onChangeText={setKey} placeholder="Clé API Gemini" placeholderTextColor={colors.muted} secureTextEntry autoCapitalize="none" autoCorrect={false} style={styles.input} /><View style={styles.row}><Pressable onPress={() => void testNew()} disabled={busy !== null} style={[styles.secondary, busy !== null && styles.disabled]}>{busy === "test" ? <ActivityIndicator color={colors.primary} /> : <Text style={styles.secondaryText}>Tester la connexion</Text>}</Pressable><Pressable onPress={() => void save()} disabled={busy !== null} style={[styles.primary, busy !== null && styles.disabled]}>{busy === "save" ? <ActivityIndicator color={colors.surface} /> : <Text style={styles.primaryText}>Enregistrer</Text>}</Pressable></View></View><Pressable onPress={() => void testActive()} disabled={!settings?.configured || busy !== null} style={[styles.activeTest, (!settings?.configured || busy !== null) && styles.disabled]}>{busy === "active" ? <ActivityIndicator color={colors.primary} /> : <MaterialIcons name="health-and-safety" size={19} color={colors.primary} />}<Text style={styles.activeTestText}>Tester la clé active</Text></Pressable>{notice ? <View style={styles.notice}><MaterialIcons name="check-circle-outline" size={18} color={colors.success} /><Text style={[styles.noticeText, { color: colors.success }]}>{notice}</Text></View> : null}{error ? <View style={styles.notice}><MaterialIcons name="error-outline" size={18} color={colors.error} /><Text style={[styles.noticeText, { color: colors.error }]}>{error}</Text></View> : null}</>}</View></ScrollView></AppScreen>;
}

const makeStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ scroll: { paddingTop: 18, paddingBottom: 30 }, inner: { paddingHorizontal: 20, gap: 14 }, center: { flex: 1, minHeight: 180, alignItems: "center", justifyContent: "center" }, card: { gap: 7, padding: 16, borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, title: { color: colors.text, fontSize: 15, fontWeight: "900" }, label: { color: colors.muted, fontSize: 10, fontWeight: "900", textTransform: "uppercase", marginTop: 3 }, value: { color: colors.text, fontSize: 14, fontWeight: "800" }, status: { flexDirection: "row", alignItems: "center", gap: 7, marginTop: 4 }, dot: { width: 8, height: 8, borderRadius: 4 }, statusText: { color: colors.text, fontSize: 12, fontWeight: "800" }, help: { color: colors.muted, fontSize: 12, lineHeight: 18 }, input: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: 13, paddingHorizontal: 12, color: colors.text, backgroundColor: colors.background, marginTop: 4 }, row: { flexDirection: "row", gap: 10, marginTop: 4 }, secondary: { flex: 1, minHeight: 45, borderRadius: 13, borderWidth: 1, borderColor: colors.primary, alignItems: "center", justifyContent: "center" }, secondaryText: { color: colors.primary, fontSize: 12, fontWeight: "900" }, primary: { flex: 1, minHeight: 45, borderRadius: 13, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" }, primaryText: { color: colors.surface, fontSize: 12, fontWeight: "900" }, activeTest: { minHeight: 50, flexDirection: "row", gap: 8, borderRadius: 14, borderWidth: 1, borderColor: colors.primary, alignItems: "center", justifyContent: "center" }, activeTestText: { color: colors.primary, fontSize: 13, fontWeight: "900" }, notice: { flexDirection: "row", gap: 8, padding: 12, borderRadius: 14, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, noticeText: { flex: 1, fontSize: 12, lineHeight: 18, fontWeight: "700" }, disabled: { opacity: 0.45 } });
