import { Redirect } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, FlatList, StyleSheet, Text, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { EmptyState } from "@/components/edutech/empty-state";
import { PageHeader } from "@/components/edutech/page-header";
import { PrimaryButton } from "@/components/edutech/primary-button";
import { getAdminStudents, getSchoolYears, recordPromotionDecision, type AdminStudent, type SchoolYear } from "@/lib/admin/school-administration-service";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { useEduTheme } from "@/lib/edutech/theme-context";

export default function AdminPromotionsScreen() {
  const { isAdmin } = useSupabaseAuth(); const { colors } = useEduTheme(); const styles = useMemo(() => makeStyles(colors), [colors]); const [students, setStudents] = useState<AdminStudent[]>([]); const [years, setYears] = useState<SchoolYear[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const [allStudents, allYears] = await Promise.all([getAdminStudents({ role: "student" }), getSchoolYears()]); setStudents(allStudents); setYears(allYears); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Chargement impossible."); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  const decide = (student: AdminStudent, decision: "pending" | "repeat" | "admitted") => { const source = years.find((year) => year.name === student.schoolYear); if (!source) { setError("L’année scolaire de cet élève doit être renseignée avant d’enregistrer une décision."); return; } const promote = decision === "admitted" && student.schoolLevel === "Première"; Alert.alert(decision === "admitted" ? "Enregistrer l’admission ?" : decision === "repeat" ? "Enregistrer le redoublement ?" : "Mettre en attente ?", promote ? "Le passage proposé vers Terminale conservera la décision dans l’historique. La nouvelle année scolaire doit déjà être active." : "Cette décision est administrative et n’est jamais calculée automatiquement à partir de la moyenne.", [{ text: "Annuler", style: "cancel" }, { text: "Confirmer", style: decision === "repeat" ? "destructive" : "default", onPress: () => { void (async () => { try { setBusy(student.id); await recordPromotionDecision({ studentId: student.id, schoolYearId: source.id, decision, nextSchoolLevel: promote ? "Terminale" : null, nextSeries: promote ? student.series : null }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Décision impossible."); } finally { setBusy(null); } })(); } }]); };
  if (!isAdmin) return <Redirect href="/(tabs)" />; return <AppScreen withPadding={false}><FlatList data={students} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><PageHeader title="Décisions de passage" subtitle="La moyenne est une information ; la décision finale appartient à l’administration" back />{error ? <Text style={styles.error}>{error}</Text> : null}</View>} ListEmptyComponent={loading ? <Text style={styles.muted}>Chargement des dossiers élèves…</Text> : <EmptyState icon="school" title="Aucun élève disponible" description="Les dossiers scolaires apparaîtront ici." />} renderItem={({ item }) => <View style={styles.card}><Text style={styles.name}>{item.fullName}</Text><Text style={styles.meta}>{item.schoolYear ?? "Année non renseignée"} · {item.schoolLevel ?? "Niveau non renseigné"} {item.series ?? ""}</Text><Text style={styles.meta}>Moyenne annuelle : {item.annualAverage === null ? "Non évaluée" : `${item.annualAverage}/20`} · Décision : {item.promotionDecision === "admitted" ? "Admis" : item.promotionDecision === "repeat" ? "Redouble" : "En attente"}</Text><View style={styles.actions}><PrimaryButton label="En attente" variant="secondary" disabled={busy === item.id} onPress={() => decide(item, "pending")} style={styles.action} /><PrimaryButton label="Redouble" variant="danger" disabled={busy === item.id} onPress={() => decide(item, "repeat")} style={styles.action} /><PrimaryButton label="Admis" disabled={busy === item.id} onPress={() => decide(item, "admitted")} style={styles.action} /></View></View>} /></AppScreen>;
}
const makeStyles = (c: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { padding: 20, paddingTop: 18, paddingBottom: 34, gap: 10, flexGrow: 1 }, header: { gap: 10, marginBottom: 4 }, error: { color: c.error, padding: 10, borderRadius: 12, backgroundColor: `${c.error}12`, fontSize: 12, fontWeight: "700" }, muted: { color: c.muted, textAlign: "center", paddingVertical: 50, fontWeight: "700" }, card: { padding: 14, borderWidth: 1, borderColor: c.border, backgroundColor: c.surface, borderRadius: 18, gap: 6 }, name: { color: c.text, fontSize: 15, fontWeight: "900" }, meta: { color: c.muted, fontSize: 11, lineHeight: 16, fontWeight: "700" }, actions: { flexDirection: "row", gap: 6, marginTop: 4 }, action: { flex: 1, minHeight: 40, paddingHorizontal: 5 } });
