import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Redirect, useFocusEffect, useRouter } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { AppScreen } from "@/components/edutech/app-screen";
import { CourseEmpty, CourseError, CourseLoading } from "@/components/edutech/course-feedback";
import { PageHeader } from "@/components/edutech/page-header";
import { AdminQuiz, deleteAdminQuiz, getAdminQuizzes, setAdminQuizAvailability } from "@/lib/admin/quiz-admin-service";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { useEduTheme } from "@/lib/edutech/theme-context";
import { humanQuizDifficulty } from "@/lib/quizzes/quiz-service";

export default function AdminQuizzesScreen() {
  const router = useRouter(); const { isAdmin } = useSupabaseAuth(); const { colors } = useEduTheme(); const styles = useMemo(() => createStyles(colors), [colors]); const [items, setItems] = useState<AdminQuiz[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busyId, setBusyId] = useState<string | null>(null);
  const load = useCallback(async () => { if (!isAdmin) return; setLoading(true); setError(null); try { setItems(await getAdminQuizzes()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Les quiz n’ont pas pu être chargés."); } finally { setLoading(false); } }, [isAdmin]); useFocusEffect(useCallback(() => { void load(); }, [load]));
  const changeAvailability = useCallback(async (item: AdminQuiz, values: { isPublished: boolean; isActive: boolean }) => { setBusyId(item.id); try { await setAdminQuizAvailability(item, values); await load(); } catch (cause) { Alert.alert("Modification impossible", cause instanceof Error ? cause.message : "Une erreur est survenue."); } finally { setBusyId(null); } }, [load]);
  const remove = useCallback((item: AdminQuiz) => Alert.alert("Supprimer ce quiz ?", "Cette action est définitive pour le quiz et ses questions. Les tentatives existantes empêchent la suppression.", [{ text: "Annuler", style: "cancel" }, { text: "Supprimer", style: "destructive", onPress: () => { void (async () => { setBusyId(item.id); try { await deleteAdminQuiz(item); await load(); } catch (cause) { Alert.alert("Suppression impossible", cause instanceof Error ? cause.message : "Une erreur est survenue."); } finally { setBusyId(null); } })(); } }]), [load]);
  if (!isAdmin) return <Redirect href="/(tabs)" />; if (loading) return <AppScreen><CourseLoading label="Chargement des quiz" /></AppScreen>; if (error) return <AppScreen><CourseError message={error} onRetry={() => void load()} /></AppScreen>;
  return <AppScreen withPadding={false}><FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><PageHeader title="Quiz" subtitle="Brouillons, questions, chronomètre, publication et visibilité élève." back /><Pressable accessibilityRole="button" onPress={() => router.push("/administration/quizzes/new" as any)} style={({ pressed }) => [styles.newButton, pressed && styles.pressed]}><MaterialIcons name="add" size={20} color={colors.surface} /><Text style={styles.newLabel}>Créer un quiz</Text></Pressable></View>} renderItem={({ item }) => <QuizRow item={item} busy={busyId === item.id} onEdit={() => router.push(`/administration/quizzes/${item.id}` as any)} onPublish={() => void changeAvailability(item, { isPublished: !item.isPublished, isActive: item.isActive })} onActivate={() => void changeAvailability(item, { isPublished: item.isPublished, isActive: !item.isActive })} onDelete={() => remove(item)} />} ListEmptyComponent={<CourseEmpty title="Aucun quiz créé" description="Créez un quiz en brouillon, rattachez-le à une leçon puis ajoutez ses questions avant de le publier." actionLabel="Créer un quiz" onAction={() => router.push("/administration/quizzes/new" as any)} />} /></AppScreen>;
}

function QuizRow({ item, busy, onEdit, onPublish, onActivate, onDelete }: { item: AdminQuiz; busy: boolean; onEdit: () => void; onPublish: () => void; onActivate: () => void; onDelete: () => void }) { const { colors } = useEduTheme(); const styles = useMemo(() => rowStyles(colors), [colors]); return <View style={styles.card}><Pressable accessibilityRole="button" onPress={onEdit} style={({ pressed }) => [styles.main, pressed && styles.pressed]}><View style={styles.icon}><MaterialIcons name="quiz" size={22} color={colors.primary} /></View><View style={styles.copy}><Text style={styles.target}>{item.subjectName} · {item.lessonTitle}</Text><Text style={styles.title}>{item.title}</Text><Text style={styles.details}>{item.questionCount} question{item.questionCount > 1 ? "s" : ""}{item.durationMinutes ? ` · ${item.durationMinutes} min` : ""}{item.difficulty ? ` · ${humanQuizDifficulty(item.difficulty)}` : ""}</Text></View><MaterialIcons name="chevron-right" size={23} color={colors.muted} /></Pressable><View style={styles.badges}><Badge label={item.isPublished ? "Publié" : "Brouillon"} active={item.isPublished} /><Badge label={item.isActive ? "Actif" : "Inactif"} active={item.isActive} /><Text style={styles.attempts}>{item.attemptCount} tentative{item.attemptCount > 1 ? "s" : ""}</Text></View><View style={styles.actions}><Action icon={item.isPublished ? "unpublished" : "publish"} label={item.isPublished ? "Dépublier" : "Publier"} disabled={busy} onPress={onPublish} /><Action icon={item.isActive ? "visibility-off" : "visibility"} label={item.isActive ? "Désactiver" : "Activer"} disabled={busy || !item.isPublished} onPress={onActivate} /><Action icon="delete-outline" label="Supprimer" disabled={busy} destructive onPress={onDelete} /></View></View>; }
function Badge({ label, active }: { label: string; active: boolean }) { const { colors } = useEduTheme(); return <Text style={{ color: active ? colors.success : colors.muted, backgroundColor: active ? colors.primarySoft : colors.surfaceMuted, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, fontSize: 10, fontWeight: "900" }}>{label}</Text>; }
function Action({ icon, label, disabled, destructive, onPress }: { icon: any; label: string; disabled: boolean; destructive?: boolean; onPress: () => void }) { const { colors } = useEduTheme(); const styles = useMemo(() => actionStyles(colors), [colors]); const color = destructive ? colors.error : colors.primary; return <Pressable disabled={disabled} accessibilityRole="button" onPress={onPress} style={({ pressed }) => [styles.button, disabled && styles.disabled, pressed && !disabled && styles.pressed]}><MaterialIcons name={icon} size={16} color={disabled ? colors.muted : color} /><Text style={[styles.label, { color: disabled ? colors.muted : color }]}>{label}</Text></Pressable>; }
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 18, paddingBottom: 28, gap: 11 }, header: { gap: 15, marginBottom: 4 }, newButton: { minHeight: 46, borderRadius: 14, backgroundColor: colors.primary, flexDirection: "row", justifyContent: "center", alignItems: "center", gap: 8 }, newLabel: { color: colors.surface, fontSize: 14, fontWeight: "900" }, pressed: { opacity: 0.72 } });
const rowStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ card: { padding: 14, borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, gap: 12 }, main: { flexDirection: "row", alignItems: "center", gap: 11 }, icon: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.primarySoft, justifyContent: "center", alignItems: "center" }, copy: { flex: 1 }, target: { color: colors.muted, fontSize: 10, fontWeight: "800" }, title: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: "900", marginTop: 2 }, details: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 2 }, badges: { flexDirection: "row", alignItems: "center", gap: 7, flexWrap: "wrap" }, attempts: { color: colors.muted, fontSize: 10, fontWeight: "700" }, actions: { flexDirection: "row", flexWrap: "wrap", gap: 8, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 10 }, pressed: { opacity: 0.72 } });
const actionStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ button: { minHeight: 34, paddingHorizontal: 9, borderRadius: 10, backgroundColor: colors.primarySoft, flexDirection: "row", alignItems: "center", gap: 5 }, label: { fontSize: 10, fontWeight: "900" }, disabled: { opacity: 0.55 }, pressed: { opacity: 0.72 } });
