import { Redirect } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, FlatList, StyleSheet, Text, TextInput, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { EmptyState } from "@/components/edutech/empty-state";
import { PageHeader } from "@/components/edutech/page-header";
import { PrimaryButton } from "@/components/edutech/primary-button";
import { archiveSchoolYear, closeSchoolYear, createSchoolYear, activateSchoolYear, getSchoolYears, type SchoolYear } from "@/lib/admin/school-administration-service";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { useEduTheme } from "@/lib/edutech/theme-context";

const statusLabel: Record<SchoolYear["status"], string> = { draft: "Préparation", active: "Active", closed: "Clôturée", archived: "Archivée" };

export default function AdminSchoolYearsScreen() {
  const { isAdmin } = useSupabaseAuth(); const { colors } = useEduTheme(); const styles = useMemo(() => makeStyles(colors), [colors]);
  const [years, setYears] = useState<SchoolYear[]>([]); const [name, setName] = useState(""); const [notes, setNotes] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { setYears(await getSchoolYears()); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Chargement impossible."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const create = async () => { try { setBusy("create"); await createSchoolYear({ name, notes }); setName(""); setNotes(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Création impossible."); } finally { setBusy(null); } };
  const confirmAction = (year: SchoolYear, action: "activate" | "close" | "archive") => Alert.alert(action === "activate" ? "Activer cette année ?" : action === "close" ? "Clôturer cette année ?" : "Archiver cette année ?", action === "activate" ? "L’activation est exclusive : une seule année peut être active." : action === "close" ? "Les données seront conservées et l’année ne sera plus modifiable normalement." : "L’archivage conserve toutes les données mais bloque les modifications courantes.", [{ text: "Annuler", style: "cancel" }, { text: "Confirmer", style: action === "activate" ? "default" : "destructive", onPress: () => { void (async () => { try { setBusy(year.id); if (action === "activate") await activateSchoolYear(year.id); if (action === "close") await closeSchoolYear(year.id); if (action === "archive") await archiveSchoolYear(year.id); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Action impossible."); } finally { setBusy(null); } })(); } }]);
  if (!isAdmin) return <Redirect href="/(tabs)" />;
  return <AppScreen withPadding={false}><FlatList data={years} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><PageHeader title="Années scolaires" subtitle="Activation, clôture et archivage sans suppression de données" back /><View style={styles.form}><Text style={styles.formTitle}>Créer une année en préparation</Text><TextInput value={name} onChangeText={setName} placeholder="Ex. 2027-2028" placeholderTextColor={colors.muted} style={styles.input} /><TextInput value={notes} onChangeText={setNotes} placeholder="Note administrative (facultative)" placeholderTextColor={colors.muted} style={styles.input} /><PrimaryButton label="Créer l’année" disabled={!/^\d{4}-\d{4}$/.test(name) || busy !== null} loading={busy === "create"} onPress={() => void create()} /></View>{error ? <Text style={styles.error}>{error}</Text> : null}</View>} ListEmptyComponent={loading ? <Text style={styles.muted}>Chargement des années scolaires…</Text> : <EmptyState icon="calendar-month" title="Aucune année scolaire" description="Créez la première année scolaire en préparation." />} renderItem={({ item }) => <View style={styles.card}><View style={styles.cardTop}><View><Text style={styles.title}>{item.name}</Text><Text style={styles.meta}>{statusLabel[item.status]}{item.notes ? ` · ${item.notes}` : ""}</Text></View><View style={[styles.badge, item.status === "active" && styles.activeBadge]}><Text style={[styles.badgeText, item.status === "active" && styles.activeBadgeText]}>{statusLabel[item.status]}</Text></View></View>{item.status === "draft" ? <PrimaryButton label="Activer" variant="secondary" disabled={busy !== null} onPress={() => confirmAction(item, "activate")} /> : null}{item.status === "active" ? <PrimaryButton label="Clôturer l’année" variant="danger" disabled={busy !== null} onPress={() => confirmAction(item, "close")} /> : null}{item.status === "closed" ? <PrimaryButton label="Archiver l’année" variant="secondary" disabled={busy !== null} onPress={() => confirmAction(item, "archive")} /> : null}</View>} /></AppScreen>;
}
const makeStyles = (c: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { padding: 20, paddingTop: 18, paddingBottom: 34, gap: 10, flexGrow: 1 }, header: { gap: 14, marginBottom: 4 }, form: { padding: 14, borderRadius: 18, borderWidth: 1, borderColor: c.border, backgroundColor: c.surface, gap: 10 }, formTitle: { color: c.text, fontSize: 14, fontWeight: "800" }, input: { minHeight: 46, borderWidth: 1, borderColor: c.border, borderRadius: 13, paddingHorizontal: 12, color: c.text, backgroundColor: c.background, fontSize: 13 }, error: { color: c.error, fontSize: 12, fontWeight: "700", padding: 10, backgroundColor: `${c.error}12`, borderRadius: 12 }, muted: { color: c.muted, textAlign: "center", paddingVertical: 50, fontWeight: "700" }, card: { padding: 14, borderRadius: 18, borderWidth: 1, borderColor: c.border, backgroundColor: c.surface, gap: 12 }, cardTop: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, title: { color: c.text, fontSize: 16, fontWeight: "900" }, meta: { color: c.muted, fontSize: 12, marginTop: 3, maxWidth: 220 }, badge: { alignSelf: "flex-start", borderRadius: 10, paddingHorizontal: 9, paddingVertical: 6, backgroundColor: c.warningSoft }, activeBadge: { backgroundColor: c.primarySoft }, badgeText: { color: c.warning, fontSize: 11, fontWeight: "900" }, activeBadgeText: { color: c.primary } });
