import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Redirect, useRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { AdminChoice, AdminLoading, AdminNotice, AdminStatus } from "@/components/edutech/admin-ui";
import { EmptyState } from "@/components/edutech/empty-state";
import { PageHeader } from "@/components/edutech/page-header";
import { PrimaryButton } from "@/components/edutech/primary-button";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { AdminSubject, getAdminSubjects } from "@/lib/admin/course-admin-service";
import { useEduTheme } from "@/lib/edutech/theme-context";

type StatusFilter = "all" | "active" | "inactive";
export default function AdminSubjectsScreen() {
  const router = useRouter(); const { isAdmin } = useSupabaseAuth(); const { colors } = useEduTheme(); const styles = useMemo(() => createStyles(colors), [colors]); const [subjects, setSubjects] = useState<AdminSubject[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState<StatusFilter>("all"); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setError(null); try { setSubjects(await getAdminSubjects()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Le catalogue n’a pas pu être chargé."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => subjects.filter((subject) => subject.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()) && (status === "all" || status === "active" ? subject.isActive : !subject.isActive)), [subjects, search, status]);
  if (!isAdmin) return <Redirect href="/(tabs)" />;
  if (loading) return <AppScreen><AdminLoading label="Chargement des matières…" /></AppScreen>;
  return <AppScreen edges={["top", "bottom", "left", "right"]} withPadding={false}><FlatList data={filtered} keyExtractor={(item) => item.id} refreshControl={<RefreshControl refreshing={loading} onRefresh={() => { setLoading(true); void load(); }} tintColor={colors.primary} />} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><PageHeader title="Matières" subtitle="Catalogue et associations pédagogiques" back /><PrimaryButton label="Nouvelle matière" onPress={() => router.push("/administration/subjects/new" as any)} icon={<MaterialIcons name="add" size={20} color={colors.surface} />} /><View style={styles.search}><MaterialIcons name="search" size={20} color={colors.muted} /><TextInput value={search} onChangeText={setSearch} placeholder="Rechercher une matière" placeholderTextColor={colors.muted} style={styles.searchInput} /></View><View style={styles.filters}><AdminChoice label="Toutes" selected={status === "all"} onPress={() => setStatus("all")} /><AdminChoice label="Actives" selected={status === "active"} onPress={() => setStatus("active")} /><AdminChoice label="Brouillons" selected={status === "inactive"} onPress={() => setStatus("inactive")} /></View>{error ? <AdminNotice tone="error">{error}</AdminNotice> : null}</View>} renderItem={({ item }) => <Pressable accessibilityRole="button" accessibilityLabel={`Modifier ${item.name}`} onPress={() => router.push(`/administration/subjects/${item.id}` as any)} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><View style={styles.rowIcon}><MaterialIcons name="menu-book" size={21} color={colors.primary} /></View><View style={styles.rowCopy}><Text style={styles.rowTitle}>{item.name}</Text><Text style={styles.rowDescription} numberOfLines={2}>{item.description || "Aucune description"}</Text><View style={styles.metadata}><AdminStatus active={item.isActive} activeLabel="Active" inactiveLabel="Inactive" /><Text style={styles.order}>Ordre {item.displayOrder}</Text>{item.isTestData ? <Text style={styles.test}>Donnée de test</Text> : null}</View></View><MaterialIcons name="chevron-right" size={24} color={colors.muted} /></Pressable>} ListEmptyComponent={<EmptyState icon="menu-book" title="Aucune matière trouvée" description="Modifiez la recherche ou créez une nouvelle matière." />} /> </AppScreen>;
}
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ content: { padding: 20, paddingTop: 18, paddingBottom: 30, gap: 10, flexGrow: 1 }, header: { gap: 12, marginBottom: 4 }, search: { minHeight: 50, borderRadius: 15, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, flexDirection: "row", alignItems: "center", gap: 9, paddingHorizontal: 13 }, searchInput: { flex: 1, color: colors.text, fontSize: 15, paddingVertical: 10 }, filters: { flexDirection: "row", gap: 8, flexWrap: "wrap" }, row: { flexDirection: "row", alignItems: "center", gap: 12, padding: 13, borderRadius: 17, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, rowIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" }, rowCopy: { flex: 1 }, rowTitle: { color: colors.text, fontSize: 15, lineHeight: 20, fontWeight: "800" }, rowDescription: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 2 }, metadata: { flexDirection: "row", gap: 7, alignItems: "center", flexWrap: "wrap", marginTop: 8 }, order: { color: colors.muted, fontSize: 11, fontWeight: "700" }, test: { color: colors.warning, fontSize: 11, fontWeight: "800" }, pressed: { opacity: 0.7 } });
