-- Physique-Chimie Terminale C/D : chimie organique commune, brouillons uniquement.
do $physics_chemistry_cd_organic$
declare target record; target_chapter_id uuid; target_lesson_id uuid; offering_count integer;
  lesson_0_exercise_a uuid; lesson_0_exercise_b uuid; lesson_0_quiz_a uuid; lesson_0_quiz_b uuid;
  lesson_1_exercise_a uuid; lesson_1_exercise_b uuid; lesson_1_quiz_a uuid; lesson_1_quiz_b uuid;
  lesson_2_exercise_a uuid; lesson_2_exercise_b uuid; lesson_2_quiz_a uuid; lesson_2_quiz_b uuid;
begin
  select count(*) into offering_count from public.course_subject_offerings o join public.series se on se.id=o.series_id join public.subjects su on su.id=o.subject_id join public.levels lv on lv.id=o.level_id where se.name in ('C','D') and lv.name ilike '%Terminale%' and su.name ilike '%PHYSIQUE%CHIMIE%' and not o.is_test_data;
  if offering_count<>2 then raise exception 'Les deux offres officielles Physique-Chimie Terminale C et D sont requises.'; end if;
  for target in select o.id as offering_id,o.subject_id,o.level_id,o.series_id,se.name as series_name from public.course_subject_offerings o join public.series se on se.id=o.series_id join public.subjects su on su.id=o.subject_id join public.levels lv on lv.id=o.level_id where se.name in ('C','D') and lv.name ilike '%Terminale%' and su.name ilike '%PHYSIQUE%CHIMIE%' and not o.is_test_data order by se.name loop
    if target.series_name='C' then
      select c.id into target_chapter_id from public.chapters c where c.subject_offering_id=target.offering_id and c.title ilike '%CHIMIE ORGANIQUE%' and not c.is_test_data limit 1;
      if target_chapter_id is null then raise exception 'Le chapitre Chimie organique de Terminale C est requis.'; end if;
      if not exists (select 1 from public.lessons l where l.chapter_id=target_chapter_id and l.title=$pc_cd_organic$Les amines$pc_cd_organic$ and not l.is_test_data) then
        insert into public.lessons (chapter_id,title,description,content,display_order,is_active,is_test_data) values (target_chapter_id,$pc_cd_organic$Les amines$pc_cd_organic$,$pc_cd_organic$Identifier, classer et nommer les amines ; expliquer leur caractère basique et nucléophile.$pc_cd_organic$,'',50,false,false);
      end if;
    end if;
select c.id,l.id into target_chapter_id,target_lesson_id from public.chapters c join public.lessons l on l.chapter_id=c.id where c.subject_offering_id=target.offering_id and c.title ilike '%CHIMIE ORGANIQUE%' and l.title=$pc_cd_organic$Les alcools$pc_cd_organic$ and not c.is_test_data and not l.is_test_data limit 1;
if target_lesson_id is null then raise exception 'La leçon % est requise pour la Terminale %.',$pc_cd_organic$Les alcools$pc_cd_organic$,target.series_name; end if;
if exists (select 1 from public.lessons l where l.id=target_lesson_id and coalesce(btrim(l.content),'')<>'') then raise exception 'La leçon % de Terminale % contient déjà un cours : écrasement interdit.',$pc_cd_organic$Les alcools$pc_cd_organic$,target.series_name; end if;
if exists (select 1 from public.exercises e where e.lesson_id=target_lesson_id and not e.is_test_data) or exists (select 1 from public.quizzes q where q.lesson_id=target_lesson_id and not q.is_test_data) then raise exception 'La leçon % de Terminale % possède déjà des évaluations : duplication interdite.',$pc_cd_organic$Les alcools$pc_cd_organic$,target.series_name; end if;
update public.lessons set description=$pc_cd_organic$Identifier, nommer, classer, préparer et transformer les alcools ; relier leur structure aux produits de leurs réactions.$pc_cd_organic$,content=$pc_cd_organic$# Les alcools

## Objectif

Cette leçon aide à reconnaître un alcool, à le nommer et à prévoir les grandes transformations étudiées. Les mêmes repères sont utiles en Terminale C et D : **structure → classe → propriété chimique → produit formé**.

## 1. Reconnaître la fonction alcool

Un alcool est un composé organique portant un groupe hydroxyle **–OH** fixé sur un carbone tétraédrique. Ce carbone est appelé **carbone fonctionnel**.

| Écriture | Signification |
|---|---|
| **R–OH** | Formule générale : **R** représente un groupe alkyle. |
| **CₙH₂ₙ₊₂O** | Formule brute d’un alcool saturé monofonctionnel, avec **n ≥ 1**. |
| **–OH** | Groupe hydroxyle caractéristique de la fonction alcool. |

> **Vigilance :** le groupe **–OH** doit être fixé sur un carbone de la chaîne étudiée. Pour classer un alcool, on observe le carbone qui porte ce groupe, et non le nombre total de carbones de la molécule.

## 2. Nommer et classer

Pour nommer un alcool, on choisit la chaîne principale contenant le carbone fonctionnel, on numérote pour donner au groupe **–OH** l’indice le plus petit puis on remplace le « e » final de l’alcane par **-ol**.

| Exemple | Nom | Classe | Raisonnement |
|---|---|---|---|
| **CH₃–CH₂–OH** | éthanol | primaire | Le carbone fonctionnel est lié à un seul groupe alkyle. |
| **CH₃–CHOH–CH₃** | propan-2-ol | secondaire | Il est lié à deux groupes alkyles. |
| **(CH₃)₃C–OH** | 2-méthylpropan-2-ol | tertiaire | Il est lié à trois groupes alkyles. |

Une classe n’est pas un jugement de difficulté : elle sert surtout à anticiper l’oxydation ménagée.

## 3. Préparer un alcool

Le PDF étudie deux voies. La fermentation transforme un sucre fermentescible sous l’action des levures ; la forme équilibrée de la fermentation du glucose est :

**C₆H₁₂O₆ → 2 C₂H₅OH + 2 CO₂**.

L’hydratation d’un alcène ajoute les éléments de l’eau sur la double liaison. Dans le cas présenté, l’hydratation du propène conduit majoritairement au propan-2-ol. Le support relie ce résultat à la règle de Markovnikov : l’hydrogène s’ajoute au carbone de la double liaison qui porte déjà le plus d’atomes d’hydrogène.

## 4. Réactions caractéristiques

| Transformation | Idée essentielle | Produit ou observation attendu |
|---|---|---|
| Action du sodium | L’alcool forme un alcoolate et libère du dihydrogène. | **2 R–OH + 2 Na → 2 R–O⁻Na⁺ + H₂** |
| Déshydratation intramoléculaire | Une même molécule perd de l’eau. | Formation d’un alcène. |
| Déshydratation intermoléculaire | Deux molécules d’alcool réagissent. | Formation d’un étheroxyde et d’eau. |
| Combustion complète | L’alcool réagit avec le dioxygène. | **CₙH₂ₙ₊₁OH + 3n/2 O₂ → n CO₂ + (n+1) H₂O** |

## 5. Oxydation ménagée : le rôle de la classe

| Alcool de départ | Avec oxydant en défaut | Avec oxydant en excès | À retenir |
|---|---|---|---|
| Primaire **R–CH₂OH** | Aldéhyde | Acide carboxylique | La chaîne conserve le même nombre de carbones. |
| Secondaire **R₁–CHOH–R₂** | Cétone | Cétone dans le cadre du cours | Le groupe carbonyle se forme sur le carbone fonctionnel. |
| Tertiaire | Pas d’oxydation ménagée dans les conditions du support | — | La classe explique l’absence de produit carbonylé attendu. |

Le support illustre l’éthanol oxydé en éthanal ou en acide éthanoïque selon la quantité d’oxydant, ainsi que le propan-2-ol oxydé en propanone. Avant d’écrire une équation, identifie donc d’abord la classe de l’alcool et le milieu précisé.

## 6. Polyols et méthode de résolution

Un **polyol** possède plusieurs groupes hydroxyles ; le glycol et le glycérol sont les exemples cités. Pour résoudre un problème d’identification, procède dans cet ordre : déterminer la formule brute à partir des données, lister les isomères possibles, utiliser la classe révélée par l’oxydation, puis vérifier la cohérence du produit obtenu.

> **Synthèse :** savoir nommer et classer un alcool permet de prévoir une partie décisive de sa réactivité. Ne choisis jamais le produit d’oxydation avant d’avoir déterminé la classe de l’alcool.

| Vocabulaire | Sens utile |
|---|---|
| Carbone fonctionnel | Carbone portant le groupe **–OH**. |
| Alcoolate | Espèce obtenue lorsque l’alcool perd l’hydrogène de son groupe hydroxyle. |
| Déshydratation | Élimination d’une molécule d’eau. |
| Oxydation ménagée | Transformation contrôlée qui conduit à un produit organique précis. |
| Polyol | Alcool portant plusieurs groupes hydroxyles. |$pc_cd_organic$,is_active=false where id=target_lesson_id and coalesce(btrim(content),'')='';
insert into public.exercises (subject_id,level_id,series_id,chapter_id,lesson_id,title,statement,solution,exercise_type,difficulty,content_markdown,correction_markdown,is_published,is_active,estimated_duration_minutes,display_order,is_test_data) values (target.subject_id,target.level_id,target.series_id,target_chapter_id,target_lesson_id,$pc_cd_organic$Exercice d’application — Les alcools$pc_cd_organic$,$pc_cd_organic$Réponds aux questions en t’appuyant sur les définitions, tableaux et méthodes de la leçon.$pc_cd_organic$,$pc_cd_organic$La correction explique la notion ou le raisonnement mobilisé pour chaque réponse.$pc_cd_organic$,'single_choice','medium',$pc_cd_organic$Choisis la proposition scientifiquement cohérente avec le cours.$pc_cd_organic$,$pc_cd_organic$Relis l’explication détaillée après chaque réponse.$pc_cd_organic$,false,false,18,110,false) returning id into lesson_0_exercise_a;
insert into public.exercise_questions (exercise_id,question_type,prompt_markdown,options,correct_answers,explanation_markdown,display_order) values (lesson_0_exercise_a,'single_choice',$pc_cd_organic$Quelle propriété détermine la classe d’un alcool ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$Le nombre de groupes alkyles liés au carbone fonctionnel$pc_cd_organic$,$pc_cd_organic$Le nombre total d’atomes d’oxygène$pc_cd_organic$,$pc_cd_organic$La masse molaire seulement$pc_cd_organic$),jsonb_build_array($pc_cd_organic$Le nombre de groupes alkyles liés au carbone fonctionnel$pc_cd_organic$),$pc_cd_organic$La classe primaire, secondaire ou tertiaire dépend de l’environnement du carbone portant `–OH`.$pc_cd_organic$,10),(lesson_0_exercise_a,'single_choice',$pc_cd_organic$Quel produit obtient-on par oxydation ménagée d’un alcool secondaire selon le support ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$Une cétone$pc_cd_organic$,$pc_cd_organic$Un aldéhyde$pc_cd_organic$,$pc_cd_organic$Un acide carboxylique directement$pc_cd_organic$),jsonb_build_array($pc_cd_organic$Une cétone$pc_cd_organic$),$pc_cd_organic$Un alcool secondaire conduit à une cétone dans le cadre étudié.$pc_cd_organic$,20),(lesson_0_exercise_a,'single_choice',$pc_cd_organic$Quelle voie transforme le propène en propan-2-ol dans le PDF ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$L’hydratation de l’alcène$pc_cd_organic$,$pc_cd_organic$La combustion$pc_cd_organic$,$pc_cd_organic$La réaction avec le sodium$pc_cd_organic$),jsonb_build_array($pc_cd_organic$L’hydratation de l’alcène$pc_cd_organic$),$pc_cd_organic$L’eau s’ajoute sur la double liaison lors de l’hydratation.$pc_cd_organic$,30),(lesson_0_exercise_a,'single_choice',$pc_cd_organic$Quelle formule correspond à un alcool saturé monofonctionnel ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$CₙH₂ₙ₊₂O$pc_cd_organic$,$pc_cd_organic$CₙH₂ₙO$pc_cd_organic$,$pc_cd_organic$CₙH₂ₙ₊₃N$pc_cd_organic$),jsonb_build_array($pc_cd_organic$CₙH₂ₙ₊₂O$pc_cd_organic$),$pc_cd_organic$Les deux autres formules servent ici respectivement aux composés carbonylés et aux amines saturées.$pc_cd_organic$,40);
insert into public.exercises (subject_id,level_id,series_id,chapter_id,lesson_id,title,statement,solution,exercise_type,difficulty,content_markdown,correction_markdown,is_published,is_active,estimated_duration_minutes,display_order,is_test_data) values (target.subject_id,target.level_id,target.series_id,target_chapter_id,target_lesson_id,$pc_cd_organic$Exercice de consolidation — Les alcools$pc_cd_organic$,$pc_cd_organic$Réinvestis la méthode dans une situation équivalente puis consulte la correction détaillée.$pc_cd_organic$,$pc_cd_organic$La correction relie chaque réponse à la structure ou à la transformation étudiée.$pc_cd_organic$,'single_choice','medium',$pc_cd_organic$Analyse chaque indice avant de choisir une réponse.$pc_cd_organic$,$pc_cd_organic$Vérifie notamment la famille chimique, le groupe fonctionnel et le lien logique.$pc_cd_organic$,false,false,18,120,false) returning id into lesson_0_exercise_b;
insert into public.exercise_questions (exercise_id,question_type,prompt_markdown,options,correct_answers,explanation_markdown,display_order) values (lesson_0_exercise_b,'single_choice',$pc_cd_organic$Pourquoi un alcool primaire peut-il donner deux produits selon la quantité d’oxydant ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$Un aldéhyde avec oxydant en défaut, puis un acide avec oxydant en excès$pc_cd_organic$,$pc_cd_organic$Il change de classe au hasard$pc_cd_organic$,$pc_cd_organic$Il ne réagit jamais$pc_cd_organic$),jsonb_build_array($pc_cd_organic$Un aldéhyde avec oxydant en défaut, puis un acide avec oxydant en excès$pc_cd_organic$),$pc_cd_organic$Le PDF distingue explicitement les deux situations d’oxydation d’un alcool primaire.$pc_cd_organic$,10),(lesson_0_exercise_b,'single_choice',$pc_cd_organic$Quelle transformation conduit à un alcène à partir d’un alcool ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$La déshydratation intramoléculaire$pc_cd_organic$,$pc_cd_organic$La fermentation$pc_cd_organic$,$pc_cd_organic$La réduction de Tollens$pc_cd_organic$),jsonb_build_array($pc_cd_organic$La déshydratation intramoléculaire$pc_cd_organic$),$pc_cd_organic$Une élimination d’eau dans une même molécule forme l’alcène.$pc_cd_organic$,20),(lesson_0_exercise_b,'single_choice',$pc_cd_organic$Comment numérote-t-on la chaîne d’un alcool lors de la nomenclature ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$Pour donner l’indice le plus faible au carbone portant `–OH`$pc_cd_organic$,$pc_cd_organic$Toujours depuis le carbone le plus éloigné$pc_cd_organic$,$pc_cd_organic$Selon l’ordre alphabétique des substituants uniquement$pc_cd_organic$),jsonb_build_array($pc_cd_organic$Pour donner l’indice le plus faible au carbone portant `–OH`$pc_cd_organic$),$pc_cd_organic$Le groupe hydroxyle est la fonction prioritaire pour cette numérotation.$pc_cd_organic$,30),(lesson_0_exercise_b,'single_choice',$pc_cd_organic$Quelle espèce est libérée lors de l’action du sodium sur un alcool ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$Le dihydrogène$pc_cd_organic$,$pc_cd_organic$Le dioxyde de carbone$pc_cd_organic$,$pc_cd_organic$Le dioxygène$pc_cd_organic$),jsonb_build_array($pc_cd_organic$Le dihydrogène$pc_cd_organic$),$pc_cd_organic$La réaction forme un alcoolate et libère `H₂`.$pc_cd_organic$,40);
insert into public.quizzes (subject_id,level_id,series_id,subject_offering_id,chapter_id,lesson_id,title,description,difficulty,duration_minutes,display_order,is_published,is_active,is_test_data) values (target.subject_id,target.level_id,target.series_id,target.offering_id,target_chapter_id,target_lesson_id,$pc_cd_organic$Quiz A — Repères — Les alcools$pc_cd_organic$,$pc_cd_organic$Vérifie les méthodes et notions essentielles de la leçon Les alcools.$pc_cd_organic$,'medium',12,110,false,false,false) returning id into lesson_0_quiz_a; with inserted_questions as (insert into public.quiz_questions (quiz_id,question,explanation,question_type,display_order,points,is_active) values (lesson_0_quiz_a,$pc_cd_organic$Quelle propriété détermine la classe d’un alcool ?$pc_cd_organic$,$pc_cd_organic$La classe primaire, secondaire ou tertiaire dépend de l’environnement du carbone portant `–OH`.$pc_cd_organic$,'single_choice',10,1,true),(lesson_0_quiz_a,$pc_cd_organic$Quel produit obtient-on par oxydation ménagée d’un alcool secondaire selon le support ?$pc_cd_organic$,$pc_cd_organic$Un alcool secondaire conduit à une cétone dans le cadre étudié.$pc_cd_organic$,'single_choice',20,1,true),(lesson_0_quiz_a,$pc_cd_organic$Quelle voie transforme le propène en propan-2-ol dans le PDF ?$pc_cd_organic$,$pc_cd_organic$L’eau s’ajoute sur la double liaison lors de l’hydratation.$pc_cd_organic$,'single_choice',30,1,true),(lesson_0_quiz_a,$pc_cd_organic$Quelle formule correspond à un alcool saturé monofonctionnel ?$pc_cd_organic$,$pc_cd_organic$Les deux autres formules servent ici respectivement aux composés carbonylés et aux amines saturées.$pc_cd_organic$,'single_choice',40,1,true) returning id,display_order) insert into public.quiz_answers(question_id,answer,is_correct,display_order) select iq.id,v.answer,v.is_correct,v.display_order from inserted_questions iq join (values (10,$pc_cd_organic$Le nombre de groupes alkyles liés au carbone fonctionnel$pc_cd_organic$,true,10),(10,$pc_cd_organic$Le nombre total d’atomes d’oxygène$pc_cd_organic$,false,20),(10,$pc_cd_organic$La masse molaire seulement$pc_cd_organic$,false,30),(20,$pc_cd_organic$Une cétone$pc_cd_organic$,true,10),(20,$pc_cd_organic$Un aldéhyde$pc_cd_organic$,false,20),(20,$pc_cd_organic$Un acide carboxylique directement$pc_cd_organic$,false,30),(30,$pc_cd_organic$L’hydratation de l’alcène$pc_cd_organic$,true,10),(30,$pc_cd_organic$La combustion$pc_cd_organic$,false,20),(30,$pc_cd_organic$La réaction avec le sodium$pc_cd_organic$,false,30),(40,$pc_cd_organic$CₙH₂ₙ₊₂O$pc_cd_organic$,true,10),(40,$pc_cd_organic$CₙH₂ₙO$pc_cd_organic$,false,20),(40,$pc_cd_organic$CₙH₂ₙ₊₃N$pc_cd_organic$,false,30)) as v(question_order,answer,is_correct,display_order) on v.question_order=iq.display_order;
insert into public.quizzes (subject_id,level_id,series_id,subject_offering_id,chapter_id,lesson_id,title,description,difficulty,duration_minutes,display_order,is_published,is_active,is_test_data) values (target.subject_id,target.level_id,target.series_id,target.offering_id,target_chapter_id,target_lesson_id,$pc_cd_organic$Quiz B — Raisonnement — Les alcools$pc_cd_organic$,$pc_cd_organic$Vérifie les méthodes et notions essentielles de la leçon Les alcools.$pc_cd_organic$,'medium',12,120,false,false,false) returning id into lesson_0_quiz_b; with inserted_questions as (insert into public.quiz_questions (quiz_id,question,explanation,question_type,display_order,points,is_active) values (lesson_0_quiz_b,$pc_cd_organic$Pourquoi un alcool primaire peut-il donner deux produits selon la quantité d’oxydant ?$pc_cd_organic$,$pc_cd_organic$Le PDF distingue explicitement les deux situations d’oxydation d’un alcool primaire.$pc_cd_organic$,'single_choice',10,1,true),(lesson_0_quiz_b,$pc_cd_organic$Quelle transformation conduit à un alcène à partir d’un alcool ?$pc_cd_organic$,$pc_cd_organic$Une élimination d’eau dans une même molécule forme l’alcène.$pc_cd_organic$,'single_choice',20,1,true),(lesson_0_quiz_b,$pc_cd_organic$Comment numérote-t-on la chaîne d’un alcool lors de la nomenclature ?$pc_cd_organic$,$pc_cd_organic$Le groupe hydroxyle est la fonction prioritaire pour cette numérotation.$pc_cd_organic$,'single_choice',30,1,true),(lesson_0_quiz_b,$pc_cd_organic$Quelle espèce est libérée lors de l’action du sodium sur un alcool ?$pc_cd_organic$,$pc_cd_organic$La réaction forme un alcoolate et libère `H₂`.$pc_cd_organic$,'single_choice',40,1,true) returning id,display_order) insert into public.quiz_answers(question_id,answer,is_correct,display_order) select iq.id,v.answer,v.is_correct,v.display_order from inserted_questions iq join (values (10,$pc_cd_organic$Un aldéhyde avec oxydant en défaut, puis un acide avec oxydant en excès$pc_cd_organic$,true,10),(10,$pc_cd_organic$Il change de classe au hasard$pc_cd_organic$,false,20),(10,$pc_cd_organic$Il ne réagit jamais$pc_cd_organic$,false,30),(20,$pc_cd_organic$La déshydratation intramoléculaire$pc_cd_organic$,true,10),(20,$pc_cd_organic$La fermentation$pc_cd_organic$,false,20),(20,$pc_cd_organic$La réduction de Tollens$pc_cd_organic$,false,30),(30,$pc_cd_organic$Pour donner l’indice le plus faible au carbone portant `–OH`$pc_cd_organic$,true,10),(30,$pc_cd_organic$Toujours depuis le carbone le plus éloigné$pc_cd_organic$,false,20),(30,$pc_cd_organic$Selon l’ordre alphabétique des substituants uniquement$pc_cd_organic$,false,30),(40,$pc_cd_organic$Le dihydrogène$pc_cd_organic$,true,10),(40,$pc_cd_organic$Le dioxyde de carbone$pc_cd_organic$,false,20),(40,$pc_cd_organic$Le dioxygène$pc_cd_organic$,false,30)) as v(question_order,answer,is_correct,display_order) on v.question_order=iq.display_order;
select c.id,l.id into target_chapter_id,target_lesson_id from public.chapters c join public.lessons l on l.chapter_id=c.id where c.subject_offering_id=target.offering_id and c.title ilike '%CHIMIE ORGANIQUE%' and l.title=$pc_cd_organic$Composés carbonylés : aldéhydes et cétones$pc_cd_organic$ and not c.is_test_data and not l.is_test_data limit 1;
if target_lesson_id is null then raise exception 'La leçon % est requise pour la Terminale %.',$pc_cd_organic$Composés carbonylés : aldéhydes et cétones$pc_cd_organic$,target.series_name; end if;
if exists (select 1 from public.lessons l where l.id=target_lesson_id and coalesce(btrim(l.content),'')<>'') then raise exception 'La leçon % de Terminale % contient déjà un cours : écrasement interdit.',$pc_cd_organic$Composés carbonylés : aldéhydes et cétones$pc_cd_organic$,target.series_name; end if;
if exists (select 1 from public.exercises e where e.lesson_id=target_lesson_id and not e.is_test_data) or exists (select 1 from public.quizzes q where q.lesson_id=target_lesson_id and not q.is_test_data) then raise exception 'La leçon % de Terminale % possède déjà des évaluations : duplication interdite.',$pc_cd_organic$Composés carbonylés : aldéhydes et cétones$pc_cd_organic$,target.series_name; end if;
update public.lessons set description=$pc_cd_organic$Reconnaître, nommer et différencier aldéhydes et cétones à partir de leur groupe carbonyle et de leurs tests caractéristiques.$pc_cd_organic$,content=$pc_cd_organic$# Composés carbonylés : aldéhydes et cétones

## Objectif

Les aldéhydes et les cétones possèdent tous deux un groupe carbonyle. Pour les distinguer avec rigueur, il faut combiner **structure**, **nomenclature** et **résultat des tests**.

## 1. Le groupe carbonyle

Un composé carbonylé est un composé organique oxygéné comportant le groupe **C=O**. Dans le cadre des composés acycliques saturés étudiés, le support donne la formule brute **CₙH₂ₙO**.

| Famille | Écriture générale | Position du groupe carbonyle |
|---|---|---|
| Aldéhyde | **R–CHO** | En bout de chaîne ; le carbone carbonylé est lié à un hydrogène. |
| Cétone | **R₁–CO–R₂** | À l’intérieur de la chaîne ; le carbone carbonylé est lié à deux groupes carbonés. |

> **Repère visuel :** la présence du groupe **–CHO** permet d’identifier un aldéhyde. Une cétone ne porte pas ce groupe terminal.

## 2. Nommer correctement

Pour un aldéhyde, le nom de l’alcane correspondant se termine par **-al**. Le carbone fonctionnel est numéroté 1. Pour une cétone, le suffixe est **-one** et le carbone fonctionnel reçoit l’indice le plus petit possible.

| Formule | Nom | Justification |
|---|---|---|
| **CH₃–CHO** | éthanal | Aldéhyde à deux carbones. |
| **CH₃–CH₂–CHO** | propanal | Groupe **–CHO** terminal. |
| **CH₃–CO–CH₃** | propan-2-one ou propanone | Cétone dont le carbonyle est au carbone 2. |
| **CH₃–CO–CH₂–CH₃** | butan-2-one | La numérotation minimise l’indice du carbonyle. |

## 3. Un test commun : la 2,4-DNPH

La 2,4-dinitrophénylhydrazine, abrégée **2,4-DNPH**, donne un précipité jaune-orangé en présence d’un aldéhyde ou d’une cétone. Ce résultat indique la présence d’un composé carbonylé, mais il ne permet pas encore de choisir entre les deux familles.

## 4. Les tests qui distinguent

| Réactif | Aldéhyde | Cétone | Ce que l’on conclut |
|---|---|---|---|
| 2,4-DNPH | Précipité jaune-orangé | Précipité jaune-orangé | Test commun : composé carbonylé. |
| Réactif de Schiff | Coloration rose | Pas de changement décrit | Aldéhyde si la coloration apparaît. |
| Réactif de Tollens | Dépôt ou miroir d’argent | Pas de réaction décrite | L’aldéhyde réduit les ions d’argent. |
| Liqueur de Fehling | Précipité rouge brique de **Cu₂O** | Pas de réaction décrite | L’aldéhyde réduit les ions cuivre II. |

Les aldéhydes sont donc des réducteurs dans les essais de Tollens et de Fehling présentés. Ils sont oxydés en ions carboxylates ; les cétones ne donnent pas ces réponses positives dans le cadre du support.

## 5. Lire une équation de Fehling

La forme générale donnée est :

**R–CHO + 2 Cu²⁺ + 5 OH⁻ → R–COO⁻ + Cu₂O + 3 H₂O**.

Avant de mémoriser une équation, relève le milieu basique, l’oxydation de l’aldéhyde et la réduction des ions cuivre II. L’apparition du précipité rouge brique est l’observation expérimentale qui accompagne cette transformation.

## 6. Méthode d’identification

1. Vérifie d’abord si la 2,4-DNPH est positive : le composé est alors carbonylé.  
2. Utilise ensuite Schiff, Tollens ou Fehling.  
3. Réponse positive à l’un de ces tests différenciants : aldéhyde.  
4. DNPH positive mais tests différenciants négatifs : cétone dans les conditions étudiées.  
5. Termine par la formule semi-développée et le nom cohérents avec les données de chaîne.

> **Synthèse :** DNPH répond à « y a-t-il un carbonyle ? » ; Fehling, Tollens et Schiff répondent à « s’agit-il d’un aldéhyde ? ».

| Vocabulaire | Sens utile |
|---|---|
| Carbonyle | Groupe **C=O** caractéristique des deux familles. |
| Aldéhyde | Composé carbonylé portant un hydrogène sur le carbone fonctionnel. |
| Cétone | Composé carbonylé portant deux groupes carbonés autour du carbone fonctionnel. |
| Réducteur | Espèce qui cède des électrons dans une oxydoréduction. |
| Carboxylate | Ion obtenu par oxydation d’un aldéhyde dans les essais présentés. |$pc_cd_organic$,is_active=false where id=target_lesson_id and coalesce(btrim(content),'')='';
insert into public.exercises (subject_id,level_id,series_id,chapter_id,lesson_id,title,statement,solution,exercise_type,difficulty,content_markdown,correction_markdown,is_published,is_active,estimated_duration_minutes,display_order,is_test_data) values (target.subject_id,target.level_id,target.series_id,target_chapter_id,target_lesson_id,$pc_cd_organic$Exercice d’application — Composés carbonylés : aldéhydes et cétones$pc_cd_organic$,$pc_cd_organic$Réponds aux questions en t’appuyant sur les définitions, tableaux et méthodes de la leçon.$pc_cd_organic$,$pc_cd_organic$La correction explique la notion ou le raisonnement mobilisé pour chaque réponse.$pc_cd_organic$,'single_choice','medium',$pc_cd_organic$Choisis la proposition scientifiquement cohérente avec le cours.$pc_cd_organic$,$pc_cd_organic$Relis l’explication détaillée après chaque réponse.$pc_cd_organic$,false,false,18,210,false) returning id into lesson_1_exercise_a;
insert into public.exercise_questions (exercise_id,question_type,prompt_markdown,options,correct_answers,explanation_markdown,display_order) values (lesson_1_exercise_a,'single_choice',$pc_cd_organic$Quel résultat donne la 2,4-DNPH avec un aldéhyde ou une cétone ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$Un précipité jaune-orangé$pc_cd_organic$,$pc_cd_organic$Un miroir d’argent uniquement$pc_cd_organic$,$pc_cd_organic$Une coloration rose uniquement$pc_cd_organic$),jsonb_build_array($pc_cd_organic$Un précipité jaune-orangé$pc_cd_organic$),$pc_cd_organic$La DNPH est le test commun des composés carbonylés étudiés.$pc_cd_organic$,10),(lesson_1_exercise_a,'single_choice',$pc_cd_organic$Quel groupe permet d’identifier un aldéhyde ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$–CHO$pc_cd_organic$,$pc_cd_organic$–OH$pc_cd_organic$,$pc_cd_organic$–NH₂$pc_cd_organic$),jsonb_build_array($pc_cd_organic$–CHO$pc_cd_organic$),$pc_cd_organic$Le groupe terminal `–CHO` caractérise l’aldéhyde.$pc_cd_organic$,20),(lesson_1_exercise_a,'single_choice',$pc_cd_organic$Quelle observation avec la liqueur de Fehling indique un aldéhyde ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$Un précipité rouge brique de Cu₂O$pc_cd_organic$,$pc_cd_organic$Un précipité jaune-orangé$pc_cd_organic$,$pc_cd_organic$Aucune transformation$pc_cd_organic$),jsonb_build_array($pc_cd_organic$Un précipité rouge brique de Cu₂O$pc_cd_organic$),$pc_cd_organic$Les aldéhydes réduisent les ions cuivre II en oxyde de cuivre I.$pc_cd_organic$,30),(lesson_1_exercise_a,'single_choice',$pc_cd_organic$Comment nomme-t-on `CH₃–CO–CH₃` ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$Propan-2-one ou propanone$pc_cd_organic$,$pc_cd_organic$Propanal$pc_cd_organic$,$pc_cd_organic$Propan-1-ol$pc_cd_organic$),jsonb_build_array($pc_cd_organic$Propan-2-one ou propanone$pc_cd_organic$),$pc_cd_organic$Le groupe carbonyle est interne : il s’agit d’une cétone.$pc_cd_organic$,40);
insert into public.exercises (subject_id,level_id,series_id,chapter_id,lesson_id,title,statement,solution,exercise_type,difficulty,content_markdown,correction_markdown,is_published,is_active,estimated_duration_minutes,display_order,is_test_data) values (target.subject_id,target.level_id,target.series_id,target_chapter_id,target_lesson_id,$pc_cd_organic$Exercice de consolidation — Composés carbonylés : aldéhydes et cétones$pc_cd_organic$,$pc_cd_organic$Réinvestis la méthode dans une situation équivalente puis consulte la correction détaillée.$pc_cd_organic$,$pc_cd_organic$La correction relie chaque réponse à la structure ou à la transformation étudiée.$pc_cd_organic$,'single_choice','medium',$pc_cd_organic$Analyse chaque indice avant de choisir une réponse.$pc_cd_organic$,$pc_cd_organic$Vérifie notamment la famille chimique, le groupe fonctionnel et le lien logique.$pc_cd_organic$,false,false,18,220,false) returning id into lesson_1_exercise_b;
insert into public.exercise_questions (exercise_id,question_type,prompt_markdown,options,correct_answers,explanation_markdown,display_order) values (lesson_1_exercise_b,'single_choice',$pc_cd_organic$Un composé donne DNPH positive et Fehling négative. Quelle famille retient-on dans le cadre du cours ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$Une cétone$pc_cd_organic$,$pc_cd_organic$Un aldéhyde$pc_cd_organic$,$pc_cd_organic$Un alcool primaire$pc_cd_organic$),jsonb_build_array($pc_cd_organic$Une cétone$pc_cd_organic$),$pc_cd_organic$La DNPH confirme le carbonyle ; Fehling distingue l’aldéhyde par une réponse positive.$pc_cd_organic$,10),(lesson_1_exercise_b,'single_choice',$pc_cd_organic$Pourquoi le test de DNPH ne suffit-il pas à distinguer les deux familles ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$Il est positif avec les aldéhydes comme avec les cétones$pc_cd_organic$,$pc_cd_organic$Il est négatif avec tous les carbonylés$pc_cd_organic$,$pc_cd_organic$Il mesure la longueur de la chaîne$pc_cd_organic$),jsonb_build_array($pc_cd_organic$Il est positif avec les aldéhydes comme avec les cétones$pc_cd_organic$),$pc_cd_organic$Il faut compléter avec Schiff, Tollens ou Fehling.$pc_cd_organic$,20),(lesson_1_exercise_b,'single_choice',$pc_cd_organic$Quel suffixe est associé aux aldéhydes ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$-al$pc_cd_organic$,$pc_cd_organic$-one$pc_cd_organic$,$pc_cd_organic$-amine$pc_cd_organic$),jsonb_build_array($pc_cd_organic$-al$pc_cd_organic$),$pc_cd_organic$Les cétones utilisent le suffixe `-one`.$pc_cd_organic$,30),(lesson_1_exercise_b,'single_choice',$pc_cd_organic$Quelle espèce organique est obtenue lorsqu’un aldéhyde est oxydé dans le test de Tollens ou Fehling ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$Un ion carboxylate$pc_cd_organic$,$pc_cd_organic$Un alcoolate$pc_cd_organic$,$pc_cd_organic$Un alcène$pc_cd_organic$),jsonb_build_array($pc_cd_organic$Un ion carboxylate$pc_cd_organic$),$pc_cd_organic$Le PDF décrit l’oxydation de l’aldéhyde en ion carboxylate.$pc_cd_organic$,40);
insert into public.quizzes (subject_id,level_id,series_id,subject_offering_id,chapter_id,lesson_id,title,description,difficulty,duration_minutes,display_order,is_published,is_active,is_test_data) values (target.subject_id,target.level_id,target.series_id,target.offering_id,target_chapter_id,target_lesson_id,$pc_cd_organic$Quiz A — Repères — Composés carbonylés : aldéhydes et cétones$pc_cd_organic$,$pc_cd_organic$Vérifie les méthodes et notions essentielles de la leçon Composés carbonylés : aldéhydes et cétones.$pc_cd_organic$,'medium',12,210,false,false,false) returning id into lesson_1_quiz_a; with inserted_questions as (insert into public.quiz_questions (quiz_id,question,explanation,question_type,display_order,points,is_active) values (lesson_1_quiz_a,$pc_cd_organic$Quel résultat donne la 2,4-DNPH avec un aldéhyde ou une cétone ?$pc_cd_organic$,$pc_cd_organic$La DNPH est le test commun des composés carbonylés étudiés.$pc_cd_organic$,'single_choice',10,1,true),(lesson_1_quiz_a,$pc_cd_organic$Quel groupe permet d’identifier un aldéhyde ?$pc_cd_organic$,$pc_cd_organic$Le groupe terminal `–CHO` caractérise l’aldéhyde.$pc_cd_organic$,'single_choice',20,1,true),(lesson_1_quiz_a,$pc_cd_organic$Quelle observation avec la liqueur de Fehling indique un aldéhyde ?$pc_cd_organic$,$pc_cd_organic$Les aldéhydes réduisent les ions cuivre II en oxyde de cuivre I.$pc_cd_organic$,'single_choice',30,1,true),(lesson_1_quiz_a,$pc_cd_organic$Comment nomme-t-on `CH₃–CO–CH₃` ?$pc_cd_organic$,$pc_cd_organic$Le groupe carbonyle est interne : il s’agit d’une cétone.$pc_cd_organic$,'single_choice',40,1,true) returning id,display_order) insert into public.quiz_answers(question_id,answer,is_correct,display_order) select iq.id,v.answer,v.is_correct,v.display_order from inserted_questions iq join (values (10,$pc_cd_organic$Un précipité jaune-orangé$pc_cd_organic$,true,10),(10,$pc_cd_organic$Un miroir d’argent uniquement$pc_cd_organic$,false,20),(10,$pc_cd_organic$Une coloration rose uniquement$pc_cd_organic$,false,30),(20,$pc_cd_organic$–CHO$pc_cd_organic$,true,10),(20,$pc_cd_organic$–OH$pc_cd_organic$,false,20),(20,$pc_cd_organic$–NH₂$pc_cd_organic$,false,30),(30,$pc_cd_organic$Un précipité rouge brique de Cu₂O$pc_cd_organic$,true,10),(30,$pc_cd_organic$Un précipité jaune-orangé$pc_cd_organic$,false,20),(30,$pc_cd_organic$Aucune transformation$pc_cd_organic$,false,30),(40,$pc_cd_organic$Propan-2-one ou propanone$pc_cd_organic$,true,10),(40,$pc_cd_organic$Propanal$pc_cd_organic$,false,20),(40,$pc_cd_organic$Propan-1-ol$pc_cd_organic$,false,30)) as v(question_order,answer,is_correct,display_order) on v.question_order=iq.display_order;
insert into public.quizzes (subject_id,level_id,series_id,subject_offering_id,chapter_id,lesson_id,title,description,difficulty,duration_minutes,display_order,is_published,is_active,is_test_data) values (target.subject_id,target.level_id,target.series_id,target.offering_id,target_chapter_id,target_lesson_id,$pc_cd_organic$Quiz B — Raisonnement — Composés carbonylés : aldéhydes et cétones$pc_cd_organic$,$pc_cd_organic$Vérifie les méthodes et notions essentielles de la leçon Composés carbonylés : aldéhydes et cétones.$pc_cd_organic$,'medium',12,220,false,false,false) returning id into lesson_1_quiz_b; with inserted_questions as (insert into public.quiz_questions (quiz_id,question,explanation,question_type,display_order,points,is_active) values (lesson_1_quiz_b,$pc_cd_organic$Un composé donne DNPH positive et Fehling négative. Quelle famille retient-on dans le cadre du cours ?$pc_cd_organic$,$pc_cd_organic$La DNPH confirme le carbonyle ; Fehling distingue l’aldéhyde par une réponse positive.$pc_cd_organic$,'single_choice',10,1,true),(lesson_1_quiz_b,$pc_cd_organic$Pourquoi le test de DNPH ne suffit-il pas à distinguer les deux familles ?$pc_cd_organic$,$pc_cd_organic$Il faut compléter avec Schiff, Tollens ou Fehling.$pc_cd_organic$,'single_choice',20,1,true),(lesson_1_quiz_b,$pc_cd_organic$Quel suffixe est associé aux aldéhydes ?$pc_cd_organic$,$pc_cd_organic$Les cétones utilisent le suffixe `-one`.$pc_cd_organic$,'single_choice',30,1,true),(lesson_1_quiz_b,$pc_cd_organic$Quelle espèce organique est obtenue lorsqu’un aldéhyde est oxydé dans le test de Tollens ou Fehling ?$pc_cd_organic$,$pc_cd_organic$Le PDF décrit l’oxydation de l’aldéhyde en ion carboxylate.$pc_cd_organic$,'single_choice',40,1,true) returning id,display_order) insert into public.quiz_answers(question_id,answer,is_correct,display_order) select iq.id,v.answer,v.is_correct,v.display_order from inserted_questions iq join (values (10,$pc_cd_organic$Une cétone$pc_cd_organic$,true,10),(10,$pc_cd_organic$Un aldéhyde$pc_cd_organic$,false,20),(10,$pc_cd_organic$Un alcool primaire$pc_cd_organic$,false,30),(20,$pc_cd_organic$Il est positif avec les aldéhydes comme avec les cétones$pc_cd_organic$,true,10),(20,$pc_cd_organic$Il est négatif avec tous les carbonylés$pc_cd_organic$,false,20),(20,$pc_cd_organic$Il mesure la longueur de la chaîne$pc_cd_organic$,false,30),(30,$pc_cd_organic$-al$pc_cd_organic$,true,10),(30,$pc_cd_organic$-one$pc_cd_organic$,false,20),(30,$pc_cd_organic$-amine$pc_cd_organic$,false,30),(40,$pc_cd_organic$Un ion carboxylate$pc_cd_organic$,true,10),(40,$pc_cd_organic$Un alcoolate$pc_cd_organic$,false,20),(40,$pc_cd_organic$Un alcène$pc_cd_organic$,false,30)) as v(question_order,answer,is_correct,display_order) on v.question_order=iq.display_order;
select c.id,l.id into target_chapter_id,target_lesson_id from public.chapters c join public.lessons l on l.chapter_id=c.id where c.subject_offering_id=target.offering_id and c.title ilike '%CHIMIE ORGANIQUE%' and l.title=$pc_cd_organic$Les amines$pc_cd_organic$ and not c.is_test_data and not l.is_test_data limit 1;
if target_lesson_id is null then raise exception 'La leçon % est requise pour la Terminale %.',$pc_cd_organic$Les amines$pc_cd_organic$,target.series_name; end if;
if exists (select 1 from public.lessons l where l.id=target_lesson_id and coalesce(btrim(l.content),'')<>'') then raise exception 'La leçon % de Terminale % contient déjà un cours : écrasement interdit.',$pc_cd_organic$Les amines$pc_cd_organic$,target.series_name; end if;
if exists (select 1 from public.exercises e where e.lesson_id=target_lesson_id and not e.is_test_data) or exists (select 1 from public.quizzes q where q.lesson_id=target_lesson_id and not q.is_test_data) then raise exception 'La leçon % de Terminale % possède déjà des évaluations : duplication interdite.',$pc_cd_organic$Les amines$pc_cd_organic$,target.series_name; end if;
update public.lessons set description=$pc_cd_organic$Identifier, classer et nommer les amines ; expliquer leur caractère basique et nucléophile à partir du doublet non liant de l’azote.$pc_cd_organic$,content=$pc_cd_organic$# Les amines

## Objectif

Les amines forment une famille organique azotée. Cette leçon relie leur structure aux deux propriétés qui organisent les exercices du support : leur **caractère basique faible** et leur **caractère nucléophile**.

## 1. Définition et formule

Une amine résulte du remplacement d’un ou plusieurs atomes d’hydrogène de l’ammoniac **NH₃** par des groupements alkyles ou aryles. Pour les amines saturées, le support donne la formule brute générale **CₙH₂ₙ₊₃N**.

Le point commun important est le **doublet non liant** de l’atome d’azote. C’est lui qui permet à l’amine de capter un proton dans l’eau et d’attaquer un centre électrophile lors d’une alkylation.

## 2. Les trois classes

| Classe | Écriture générale | Ce que l’on compte |
|---|---|---|
| Amine primaire | **R–NH₂** | Un groupe carboné lié à l’azote. |
| Amine secondaire | **R₁–NH–R₂** | Deux groupes carbonés liés à l’azote. |
| Amine tertiaire | **R₁–N(R₂)–R₃** | Trois groupes carbonés liés à l’azote. |

> **Méthode :** cherche l’atome d’azote, puis compte les groupes carbonés qui lui sont directement liés. Ne confonds pas le nombre total de carbones de la molécule avec la classe de l’amine.

## 3. Nommer une amine

Le support propose deux écritures compatibles. Une amine primaire peut prendre le suffixe **-amine** à partir de l’alcane, par exemple méthanamine, ou la forme alkylamine, par exemple méthylamine. Pour une amine secondaire ou tertiaire, les groupes fixés sur l’azote sont placés avant le nom et repérés par **N-** ou **N,N-**.

| Formule | Nom possible | Classe |
|---|---|---|
| **CH₃–NH₂** | méthanamine ou méthylamine | primaire |
| **C₂H₅–NH–CH₃** | N-méthyléthanamine | secondaire |
| **C₂H₅–N(CH₃)₂** | N,N-diméthyléthanamine | tertiaire |

## 4. Une base faible dans l’eau

Le doublet non liant de l’azote permet à l’amine de capter un proton de l’eau. Pour une amine primaire, l’équation est :

**R–NH₂ + H₂O ⇌ R–NH₃⁺ + OH⁻**.

La flèche double rappelle que le caractère basique est faible : il s’agit d’un équilibre. Lorsque tu écris l’équation de la méthylamine, vérifie la conservation des atomes et des charges avant de conclure que des ions hydroxyde se forment.

## 5. Une espèce nucléophile

Le même doublet non liant rend l’amine nucléophile. Dans la réaction d’Hofmann, ou alkylation des amines selon le support, l’azote attaque le carbone d’un dérivé halogéné **R–X**, avec **X** pouvant être **Cl**, **Br** ou **I**.

L’alkylation peut faire passer progressivement d’une amine primaire à une secondaire puis tertiaire ; une amine tertiaire peut former un ion ammonium quaternaire. Il faut toujours identifier la classe de départ et compter les groupes déjà fixés sur l’azote pour prévoir le type de produit.

## 6. Démarche d’identification

Dans les problèmes du PDF, une composition massique ou une masse molaire permet de déterminer une formule brute. Ensuite :

1. Écris les isomères compatibles avec la formule.  
2. Nomme-les et classe-les en observant l’azote.  
3. Utilise l’indice sur la chaîne — linéaire ou ramifiée — pour choisir la bonne structure.  
4. Si l’eau ou un halogénoalcane est présent, relie l’équation à la propriété basique ou nucléophile demandée.

> **Synthèse :** le doublet non liant explique deux comportements différents mais liés : l’amine peut recevoir un proton dans l’eau et donner son doublet à un carbone électrophile lors de l’alkylation.

| Vocabulaire | Sens utile |
|---|---|
| Doublet non liant | Paire d’électrons non engagée dans une liaison autour de l’azote. |
| Base faible | Espèce qui capte partiellement un proton dans l’eau, à l’équilibre. |
| Nucléophile | Espèce capable de donner un doublet d’électrons à un centre électrophile. |
| Alkylation | Introduction d’un groupe alkyle sur l’azote par réaction avec un dérivé halogéné. |
| Ammonium quaternaire | Ion positif portant quatre groupes carbonés autour de l’azote. |$pc_cd_organic$,is_active=false where id=target_lesson_id and coalesce(btrim(content),'')='';
insert into public.exercises (subject_id,level_id,series_id,chapter_id,lesson_id,title,statement,solution,exercise_type,difficulty,content_markdown,correction_markdown,is_published,is_active,estimated_duration_minutes,display_order,is_test_data) values (target.subject_id,target.level_id,target.series_id,target_chapter_id,target_lesson_id,$pc_cd_organic$Exercice d’application — Les amines$pc_cd_organic$,$pc_cd_organic$Réponds aux questions en t’appuyant sur les définitions, tableaux et méthodes de la leçon.$pc_cd_organic$,$pc_cd_organic$La correction explique la notion ou le raisonnement mobilisé pour chaque réponse.$pc_cd_organic$,'single_choice','medium',$pc_cd_organic$Choisis la proposition scientifiquement cohérente avec le cours.$pc_cd_organic$,$pc_cd_organic$Relis l’explication détaillée après chaque réponse.$pc_cd_organic$,false,false,18,310,false) returning id into lesson_2_exercise_a;
insert into public.exercise_questions (exercise_id,question_type,prompt_markdown,options,correct_answers,explanation_markdown,display_order) values (lesson_2_exercise_a,'single_choice',$pc_cd_organic$Comment détermine-t-on la classe d’une amine ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$En comptant les groupes carbonés directement liés à l’azote$pc_cd_organic$,$pc_cd_organic$En comptant uniquement les atomes d’hydrogène$pc_cd_organic$,$pc_cd_organic$En regardant la couleur de la solution$pc_cd_organic$),jsonb_build_array($pc_cd_organic$En comptant les groupes carbonés directement liés à l’azote$pc_cd_organic$),$pc_cd_organic$Un, deux ou trois groupes carbonés donnent respectivement une amine primaire, secondaire ou tertiaire.$pc_cd_organic$,10),(lesson_2_exercise_a,'single_choice',$pc_cd_organic$Quelle formule représente une amine primaire ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$R–NH₂$pc_cd_organic$,$pc_cd_organic$R₁–NH–R₂$pc_cd_organic$,$pc_cd_organic$R₁–N(R₂)–R₃$pc_cd_organic$),jsonb_build_array($pc_cd_organic$R–NH₂$pc_cd_organic$),$pc_cd_organic$L’azote porte un seul groupe carboné dans une amine primaire.$pc_cd_organic$,20),(lesson_2_exercise_a,'single_choice',$pc_cd_organic$Quelle propriété est mise en évidence lorsque l’amine réagit avec l’eau ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$Son caractère basique faible$pc_cd_organic$,$pc_cd_organic$Son caractère carbonylé$pc_cd_organic$,$pc_cd_organic$Sa combustion complète$pc_cd_organic$),jsonb_build_array($pc_cd_organic$Son caractère basique faible$pc_cd_organic$),$pc_cd_organic$L’amine capte un proton de l’eau grâce au doublet non liant de l’azote.$pc_cd_organic$,30),(lesson_2_exercise_a,'single_choice',$pc_cd_organic$Quelle formule brute générale donne le support pour les amines saturées ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$CₙH₂ₙ₊₃N$pc_cd_organic$,$pc_cd_organic$CₙH₂ₙO$pc_cd_organic$,$pc_cd_organic$CₙH₂ₙ₊₂O$pc_cd_organic$),jsonb_build_array($pc_cd_organic$CₙH₂ₙ₊₃N$pc_cd_organic$),$pc_cd_organic$Les autres formules concernent ici les carbonylés et les alcools saturés monofonctionnels.$pc_cd_organic$,40);
insert into public.exercises (subject_id,level_id,series_id,chapter_id,lesson_id,title,statement,solution,exercise_type,difficulty,content_markdown,correction_markdown,is_published,is_active,estimated_duration_minutes,display_order,is_test_data) values (target.subject_id,target.level_id,target.series_id,target_chapter_id,target_lesson_id,$pc_cd_organic$Exercice de consolidation — Les amines$pc_cd_organic$,$pc_cd_organic$Réinvestis la méthode dans une situation équivalente puis consulte la correction détaillée.$pc_cd_organic$,$pc_cd_organic$La correction relie chaque réponse à la structure ou à la transformation étudiée.$pc_cd_organic$,'single_choice','medium',$pc_cd_organic$Analyse chaque indice avant de choisir une réponse.$pc_cd_organic$,$pc_cd_organic$Vérifie notamment la famille chimique, le groupe fonctionnel et le lien logique.$pc_cd_organic$,false,false,18,320,false) returning id into lesson_2_exercise_b;
insert into public.exercise_questions (exercise_id,question_type,prompt_markdown,options,correct_answers,explanation_markdown,display_order) values (lesson_2_exercise_b,'single_choice',$pc_cd_organic$Pourquoi une amine peut-elle agir comme nucléophile ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$Son azote possède un doublet non liant$pc_cd_organic$,$pc_cd_organic$Elle contient forcément un groupe carbonyle$pc_cd_organic$,$pc_cd_organic$Elle porte toujours un groupe hydroxyle$pc_cd_organic$),jsonb_build_array($pc_cd_organic$Son azote possède un doublet non liant$pc_cd_organic$),$pc_cd_organic$Le doublet peut être donné à un centre électrophile lors de l’alkylation.$pc_cd_organic$,10),(lesson_2_exercise_b,'single_choice',$pc_cd_organic$Quel préfixe indique un substituant porté par l’azote dans la nomenclature ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$N-$pc_cd_organic$,$pc_cd_organic$iso-$pc_cd_organic$,$pc_cd_organic$hydroxy-$pc_cd_organic$),jsonb_build_array($pc_cd_organic$N-$pc_cd_organic$),$pc_cd_organic$On emploie notamment `N-` ou `N,N-` pour les substituants de l’azote.$pc_cd_organic$,20),(lesson_2_exercise_b,'single_choice',$pc_cd_organic$Quelle transformation est aussi appelée réaction d’Hofmann dans le support ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$L’alkylation des amines$pc_cd_organic$,$pc_cd_organic$La déshydratation d’un alcool$pc_cd_organic$,$pc_cd_organic$La réduction de Fehling$pc_cd_organic$),jsonb_build_array($pc_cd_organic$L’alkylation des amines$pc_cd_organic$),$pc_cd_organic$L’amine attaque un carbone électrophile d’un dérivé halogéné.$pc_cd_organic$,30),(lesson_2_exercise_b,'single_choice',$pc_cd_organic$Quel produit acide-base accompagne la protonation d’une amine par l’eau ?$pc_cd_organic$,jsonb_build_array($pc_cd_organic$Des ions hydroxyde OH⁻$pc_cd_organic$,$pc_cd_organic$Du dioxyde de carbone$pc_cd_organic$,$pc_cd_organic$Un miroir d’argent$pc_cd_organic$),jsonb_build_array($pc_cd_organic$Des ions hydroxyde OH⁻$pc_cd_organic$),$pc_cd_organic$L’équation générale produit l’ion aminium et l’ion hydroxyde.$pc_cd_organic$,40);
insert into public.quizzes (subject_id,level_id,series_id,subject_offering_id,chapter_id,lesson_id,title,description,difficulty,duration_minutes,display_order,is_published,is_active,is_test_data) values (target.subject_id,target.level_id,target.series_id,target.offering_id,target_chapter_id,target_lesson_id,$pc_cd_organic$Quiz A — Repères — Les amines$pc_cd_organic$,$pc_cd_organic$Vérifie les méthodes et notions essentielles de la leçon Les amines.$pc_cd_organic$,'medium',12,310,false,false,false) returning id into lesson_2_quiz_a; with inserted_questions as (insert into public.quiz_questions (quiz_id,question,explanation,question_type,display_order,points,is_active) values (lesson_2_quiz_a,$pc_cd_organic$Comment détermine-t-on la classe d’une amine ?$pc_cd_organic$,$pc_cd_organic$Un, deux ou trois groupes carbonés donnent respectivement une amine primaire, secondaire ou tertiaire.$pc_cd_organic$,'single_choice',10,1,true),(lesson_2_quiz_a,$pc_cd_organic$Quelle formule représente une amine primaire ?$pc_cd_organic$,$pc_cd_organic$L’azote porte un seul groupe carboné dans une amine primaire.$pc_cd_organic$,'single_choice',20,1,true),(lesson_2_quiz_a,$pc_cd_organic$Quelle propriété est mise en évidence lorsque l’amine réagit avec l’eau ?$pc_cd_organic$,$pc_cd_organic$L’amine capte un proton de l’eau grâce au doublet non liant de l’azote.$pc_cd_organic$,'single_choice',30,1,true),(lesson_2_quiz_a,$pc_cd_organic$Quelle formule brute générale donne le support pour les amines saturées ?$pc_cd_organic$,$pc_cd_organic$Les autres formules concernent ici les carbonylés et les alcools saturés monofonctionnels.$pc_cd_organic$,'single_choice',40,1,true) returning id,display_order) insert into public.quiz_answers(question_id,answer,is_correct,display_order) select iq.id,v.answer,v.is_correct,v.display_order from inserted_questions iq join (values (10,$pc_cd_organic$En comptant les groupes carbonés directement liés à l’azote$pc_cd_organic$,true,10),(10,$pc_cd_organic$En comptant uniquement les atomes d’hydrogène$pc_cd_organic$,false,20),(10,$pc_cd_organic$En regardant la couleur de la solution$pc_cd_organic$,false,30),(20,$pc_cd_organic$R–NH₂$pc_cd_organic$,true,10),(20,$pc_cd_organic$R₁–NH–R₂$pc_cd_organic$,false,20),(20,$pc_cd_organic$R₁–N(R₂)–R₃$pc_cd_organic$,false,30),(30,$pc_cd_organic$Son caractère basique faible$pc_cd_organic$,true,10),(30,$pc_cd_organic$Son caractère carbonylé$pc_cd_organic$,false,20),(30,$pc_cd_organic$Sa combustion complète$pc_cd_organic$,false,30),(40,$pc_cd_organic$CₙH₂ₙ₊₃N$pc_cd_organic$,true,10),(40,$pc_cd_organic$CₙH₂ₙO$pc_cd_organic$,false,20),(40,$pc_cd_organic$CₙH₂ₙ₊₂O$pc_cd_organic$,false,30)) as v(question_order,answer,is_correct,display_order) on v.question_order=iq.display_order;
insert into public.quizzes (subject_id,level_id,series_id,subject_offering_id,chapter_id,lesson_id,title,description,difficulty,duration_minutes,display_order,is_published,is_active,is_test_data) values (target.subject_id,target.level_id,target.series_id,target.offering_id,target_chapter_id,target_lesson_id,$pc_cd_organic$Quiz B — Raisonnement — Les amines$pc_cd_organic$,$pc_cd_organic$Vérifie les méthodes et notions essentielles de la leçon Les amines.$pc_cd_organic$,'medium',12,320,false,false,false) returning id into lesson_2_quiz_b; with inserted_questions as (insert into public.quiz_questions (quiz_id,question,explanation,question_type,display_order,points,is_active) values (lesson_2_quiz_b,$pc_cd_organic$Pourquoi une amine peut-elle agir comme nucléophile ?$pc_cd_organic$,$pc_cd_organic$Le doublet peut être donné à un centre électrophile lors de l’alkylation.$pc_cd_organic$,'single_choice',10,1,true),(lesson_2_quiz_b,$pc_cd_organic$Quel préfixe indique un substituant porté par l’azote dans la nomenclature ?$pc_cd_organic$,$pc_cd_organic$On emploie notamment `N-` ou `N,N-` pour les substituants de l’azote.$pc_cd_organic$,'single_choice',20,1,true),(lesson_2_quiz_b,$pc_cd_organic$Quelle transformation est aussi appelée réaction d’Hofmann dans le support ?$pc_cd_organic$,$pc_cd_organic$L’amine attaque un carbone électrophile d’un dérivé halogéné.$pc_cd_organic$,'single_choice',30,1,true),(lesson_2_quiz_b,$pc_cd_organic$Quel produit acide-base accompagne la protonation d’une amine par l’eau ?$pc_cd_organic$,$pc_cd_organic$L’équation générale produit l’ion aminium et l’ion hydroxyde.$pc_cd_organic$,'single_choice',40,1,true) returning id,display_order) insert into public.quiz_answers(question_id,answer,is_correct,display_order) select iq.id,v.answer,v.is_correct,v.display_order from inserted_questions iq join (values (10,$pc_cd_organic$Son azote possède un doublet non liant$pc_cd_organic$,true,10),(10,$pc_cd_organic$Elle contient forcément un groupe carbonyle$pc_cd_organic$,false,20),(10,$pc_cd_organic$Elle porte toujours un groupe hydroxyle$pc_cd_organic$,false,30),(20,$pc_cd_organic$N-$pc_cd_organic$,true,10),(20,$pc_cd_organic$iso-$pc_cd_organic$,false,20),(20,$pc_cd_organic$hydroxy-$pc_cd_organic$,false,30),(30,$pc_cd_organic$L’alkylation des amines$pc_cd_organic$,true,10),(30,$pc_cd_organic$La déshydratation d’un alcool$pc_cd_organic$,false,20),(30,$pc_cd_organic$La réduction de Fehling$pc_cd_organic$,false,30),(40,$pc_cd_organic$Des ions hydroxyde OH⁻$pc_cd_organic$,true,10),(40,$pc_cd_organic$Du dioxyde de carbone$pc_cd_organic$,false,20),(40,$pc_cd_organic$Un miroir d’argent$pc_cd_organic$,false,30)) as v(question_order,answer,is_correct,display_order) on v.question_order=iq.display_order;
  end loop;
end $physics_chemistry_cd_organic$;