-- Brouillons SVT Terminale A1/A2 : biosynthèse des protéines.
-- L8 évolution contrôlée comme doublon pédagogique déjà couvert : aucune création ni écrasement.
-- Citations : 20 nouvelles citations authentiques équilibrées par matière, toutes en brouillon.
do $svt_terminal_lot3$
declare
  a2 record;
  nutrient_chapter_uuid uuid;
  target record;
  next_chapter_order integer;
  exercise_a_uuid uuid;
  exercise_b_uuid uuid;
  quiz_uuid uuid;
  expected_count integer;
begin
  select o.id as offering_id,o.subject_id,o.level_id,o.series_id into a2
  from public.course_subject_offerings o join public.subjects sub on sub.id=o.subject_id join public.levels lv on lv.id=o.level_id join public.series s on s.id=o.series_id
  where sub.name='Sciences de la Vie et de la Terre' and lv.name='Terminale' and s.name='A2' limit 1;
  if a2.offering_id is null then raise exception 'Offre SVT Terminale A2 introuvable.'; end if;

  select coalesce(max(c.display_order),0)+10 into next_chapter_order from public.chapters c where c.subject_offering_id=a2.offering_id;
  insert into public.chapters (subject_id,level_id,series_id,subject_offering_id,title,description,display_order,is_test_data,is_active)
  select a2.subject_id,a2.level_id,a2.series_id,a2.offering_id,'Thème : Le devenir des nutriments dans l’organisme.','Étude du devenir des nutriments et de la biosynthèse des protéines.',next_chapter_order,false,false
  where not exists (select 1 from public.chapters c where c.subject_offering_id=a2.offering_id and c.title='Thème : Le devenir des nutriments dans l’organisme.');
  select c.id into nutrient_chapter_uuid from public.chapters c where c.subject_offering_id=a2.offering_id and c.title='Thème : Le devenir des nutriments dans l’organisme.' limit 1;
  if nutrient_chapter_uuid is null then raise exception 'Chapitre SVT A2 sur le devenir des nutriments introuvable.'; end if;
  insert into public.lessons (chapter_id,title,description,content,display_order,is_test_data,is_active)
  select nutrient_chapter_uuid,'Leçon : L’utilisation des nutriments : la biosynthèse des protéines.','Acteurs, code génétique, transcription et traduction dans la biosynthèse des protéines.',null,10,false,false
  where not exists (select 1 from public.lessons l where l.chapter_id=nutrient_chapter_uuid and l.title='Leçon : L’utilisation des nutriments : la biosynthèse des protéines.');

  select count(*) into expected_count
  from public.lessons l join public.chapters c on c.id=l.chapter_id join public.course_subject_offerings o on o.id=c.subject_offering_id join public.subjects sub on sub.id=o.subject_id join public.levels lv on lv.id=o.level_id join public.series s on s.id=o.series_id
  where sub.name='Sciences de la Vie et de la Terre' and lv.name='Terminale' and s.name in ('A1','A2') and c.title='Thème : Le devenir des nutriments dans l’organisme.' and l.title='Leçon : L’utilisation des nutriments : la biosynthèse des protéines.';
  if expected_count <> 2 then raise exception 'Deux leçons SVT A1/A2 de biosynthèse sont requises avant remplissage ; transaction annulée.'; end if;

  for target in
    select l.id as lesson_id,c.id as chapter_id,o.id as offering_id,o.subject_id,o.level_id,o.series_id
    from public.lessons l join public.chapters c on c.id=l.chapter_id join public.course_subject_offerings o on o.id=c.subject_offering_id join public.subjects sub on sub.id=o.subject_id join public.levels lv on lv.id=o.level_id join public.series s on s.id=o.series_id
    where sub.name='Sciences de la Vie et de la Terre' and lv.name='Terminale' and s.name in ('A1','A2') and c.title='Thème : Le devenir des nutriments dans l’organisme.' and l.title='Leçon : L’utilisation des nutriments : la biosynthèse des protéines.'
    order by s.name,c.display_order,l.display_order
  loop
    if exists (select 1 from public.lessons where id=target.lesson_id and coalesce(btrim(content),'') <> '') then raise exception 'La leçon SVT % contient déjà un cours. Écrasement interdit.', target.lesson_id; end if;
    update public.lessons set description='Acteurs, code génétique, transcription et traduction dans la biosynthèse des protéines.',content=$biosynthese$
## L’utilisation des nutriments : la biosynthèse des protéines

> **Objectif :** expliquer comment la cellule utilise des nutriments pour fabriquer une protéine en distinguant les acteurs, le code génétique, la transcription et la traduction.

## 1. La question directrice du cours

Le document demande comment la cellule synthétise les protéines. La réponse ne se réduit pas à une seule étape : une information portée par l’ADN est d’abord copiée sous forme d’ARN messager, puis cette information est lue pour assembler une chaîne d’acides aminés.

$$
\text{ADN matrice} \longrightarrow \text{ARNm} \longrightarrow \text{chaîne polypeptidique}
$$

> **Définition : protéine.** Grande molécule constituée d’une ou plusieurs chaînes d’acides aminés.  
> **Définition : biosynthèse.** Production d’une molécule par un organisme ou une cellule, à partir d’éléments disponibles et selon des mécanismes organisés.

## 2. Les acteurs de la synthèse protéique

| Acteur | Caractéristique citée dans le support | Rôle dans la démarche étudiée |
|---|---|---|
| ADN | Molécule bicaténaire | Porte l’information d’un gène utilisé comme matrice lors de la transcription |
| ARNm | ARN monocaténaire | Transporte l’information copiée vers le cytoplasme |
| ARNt | ARN porteur d’un anticodon | Associe un acide aminé au codon correspondant dans le modèle étudié |
| ARNr et ribosome | Ribosome à deux sous-unités | Participent au lieu de lecture de l’ARNm et d’assemblage de la chaîne |

> **Définition : bicaténaire.** Formé de deux brins complémentaires.  
> **Définition : monocaténaire.** Formé d’un seul brin.  
> **Définition : ribosome.** Structure cellulaire décrite dans le document comme formée de deux sous-unités et impliquée dans la traduction.

## 3. Lire le code génétique avec précision

Le code génétique relie des triplets de nucléotides de l’ARNm, appelés **codons**, aux acides aminés de la chaîne en formation. Le PDF indique 64 codons : 61 codent un acide aminé et trois codons, UAA, UAG et UGA, correspondent à des signaux de terminaison. AUG est présenté comme un codon d’initiation.

| Repère | Sens dans le cours |
|---|---|
| Codon | Triplet de nucléotides lu sur l’ARNm |
| AUG | Signal de départ de la traduction dans le modèle présenté |
| UAA, UAG, UGA | Codons stop : ils marquent la terminaison |
| Redondance | Plusieurs codons peuvent correspondre au même acide aminé |
| Universalité | Le même tableau de correspondance est mobilisé pour les êtres vivants étudiés |

> **Attention :** un codon n’est pas un acide aminé. Il s’agit d’une information de trois nucléotides qui permet de sélectionner un acide aminé ou de signaler l’arrêt.

## 4. La transcription : copier une information de l’ADN vers l’ARNm

La transcription se déroule dans le noyau. Un gène de l’ADN sert de matrice à la fabrication d’un ARNm complémentaire. Le document insiste sur une différence de vocabulaire et de composition : dans l’ARNm, **l’uracile U remplace la thymine T**.

> **Définition : gène.** Portion d’ADN portant une information utilisée dans le cours pour fabriquer un ARNm.  
> **Définition : complémentarité.** Correspondance organisée entre des nucléotides permettant de produire un brin associé à un brin matrice.

> **Méthode :** identifiez d’abord le brin d’ADN matrice. Écrivez ensuite l’ARNm complémentaire en utilisant U à la place de T. Découpez enfin l’ARNm en codons avant de consulter le code génétique.

## 5. La traduction : assembler les acides aminés

La traduction se déroule dans le cytoplasme, au niveau des ribosomes. Un ARNt porte un acide aminé et un **anticodon**. Son anticodon reconnaît le codon complémentaire de l’ARNm. Le PDF décrit une succession d’étapes : initiation, élongation et terminaison.

1. **Initiation :** le ribosome se positionne au niveau du codon de départ indiqué par le modèle.
2. **Élongation :** des ARNt apportent progressivement des acides aminés ; les sites P et A du ribosome sont mentionnés dans le document.
3. **Liaison peptidique :** elle relie les acides aminés successifs dans une chaîne polypeptidique.
4. **Terminaison :** un codon stop met fin à l’assemblage.

> **Définition : anticodon.** Triplet porté par un ARNt et associé au codon complémentaire de l’ARNm.  
> **Définition : liaison peptidique.** Liaison qui relie deux acides aminés dans la chaîne en formation.  
> **Définition : chaîne polypeptidique.** Succession d’acides aminés reliés entre eux.

> **Attention :** transcription et traduction sont deux mécanismes différents. La première produit l’ARNm à partir de l’ADN dans le noyau ; la seconde lit l’ARNm pour assembler des acides aminés au niveau des ribosomes.

## 6. Synthèse à retenir

> **Synthèse :** la cellule exploite l’information d’un gène par transcription, puis utilise l’ARNm lors de la traduction. Les codons de l’ARNm sont lus par le ribosome ; les ARNt apportent les acides aminés correspondants. L’assemblage se termine à un codon stop et produit une chaîne polypeptidique.

## Référence pédagogique

Contenu reformulé et approfondi à partir du PDF fourni : **« L’utilisation des nutriments : la biosynthèse des protéines »**, SVT, Terminale A, Côte d’Ivoire – École numérique.
$biosynthese$,is_active=false where id=target.lesson_id and coalesce(btrim(content),'')='';

    exercise_a_uuid := null;
    insert into public.exercises (subject_id,level_id,series_id,chapter_id,lesson_id,title,statement,solution,exercise_type,difficulty,content_markdown,correction_markdown,is_published,is_active,estimated_duration_minutes,display_order)
    select target.subject_id,target.level_id,target.series_id,target.chapter_id,target.lesson_id,'Exercice 1 — Acteurs et code génétique de la biosynthèse','Répondez aux questions en mobilisant les définitions et les étapes décrites dans le cours.','La correction relie chaque réponse au mécanisme de biosynthèse étudié.','single_choice','easy','## Consigne

Choisissez la réponse juste puis relisez la partie correspondante du cours.','## Correction

Chaque réponse est expliquée avec le vocabulaire précis de la leçon.',false,false,15,10
    where not exists (select 1 from public.exercises e where e.lesson_id=target.lesson_id and e.title='Exercice 1 — Acteurs et code génétique de la biosynthèse') returning id into exercise_a_uuid;
    if exercise_a_uuid is not null then
      insert into public.exercise_questions (exercise_id,question_type,prompt_markdown,options,correct_answers,explanation_markdown,display_order) values
      (exercise_a_uuid,'single_choice','Quel ARN porte un anticodon dans le modèle du cours ?',jsonb_build_array('ARNt', 'ARNm', 'ADN', 'ARNr uniquement'),jsonb_build_array('ARNt'),'L’ARNt porte un anticodon et apporte un acide aminé au ribosome.',10),
      (exercise_a_uuid,'single_choice','Quel codon est présenté comme signal d’initiation ?',jsonb_build_array('AUG', 'UAA', 'UAG', 'UGA'),jsonb_build_array('AUG'),'Le cours présente AUG comme le codon de départ de la traduction.',20),
      (exercise_a_uuid,'true_false','Les codons UAA, UAG et UGA codent chacun un acide aminé.',jsonb_build_array('Vrai', 'Faux'),jsonb_build_array('Faux'),'Ces trois codons correspondent à des signaux de terminaison dans le modèle présenté.',30);
    end if;

    exercise_b_uuid := null;
    insert into public.exercises (subject_id,level_id,series_id,chapter_id,lesson_id,title,statement,solution,exercise_type,difficulty,content_markdown,correction_markdown,is_published,is_active,estimated_duration_minutes,display_order)
    select target.subject_id,target.level_id,target.series_id,target.chapter_id,target.lesson_id,'Exercice 2 — Transcription et traduction d’une information génétique','Analysez le passage de l’information génétique à la chaîne polypeptidique.','La correction distingue précisément transcription et traduction.','single_choice','medium','## Consigne

Choisissez l’analyse la plus complète et justifiez-la par une notion précise.','## Correction

Une bonne réponse distingue un lieu, un acteur, une information et une étape du mécanisme.',false,false,20,20
    where not exists (select 1 from public.exercises e where e.lesson_id=target.lesson_id and e.title='Exercice 2 — Transcription et traduction d’une information génétique') returning id into exercise_b_uuid;
    if exercise_b_uuid is not null then
      insert into public.exercise_questions (exercise_id,question_type,prompt_markdown,options,correct_answers,explanation_markdown,display_order) values
      (exercise_b_uuid,'single_choice','Quelle base est utilisée dans l’ARNm à la place de la thymine de l’ADN ?',jsonb_build_array('Uracile', 'Cytosine', 'Guanine', 'Adénine'),jsonb_build_array('Uracile'),'L’ARN utilise l’uracile U au lieu de la thymine T.',10),
      (exercise_b_uuid,'single_choice','Où se déroule la traduction dans le modèle étudié ?',jsonb_build_array('Dans le cytoplasme, au niveau des ribosomes', 'Uniquement dans le noyau', 'Dans la membrane cellulaire', 'Dans les chromosomes'),jsonb_build_array('Dans le cytoplasme, au niveau des ribosomes'),'La traduction lit l’ARNm au niveau des ribosomes du cytoplasme.',20),
      (exercise_b_uuid,'true_false','La transcription et la traduction désignent une seule et même étape de la biosynthèse des protéines.',jsonb_build_array('Vrai', 'Faux'),jsonb_build_array('Faux'),'La transcription produit l’ARNm à partir de l’ADN ; la traduction assemble ensuite les acides aminés.',30);
    end if;

    quiz_uuid := null;
    insert into public.quizzes (subject_id,level_id,series_id,subject_offering_id,chapter_id,lesson_id,title,description,difficulty,duration_minutes,display_order,is_published,is_active)
    select target.subject_id,target.level_id,target.series_id,target.offering_id,target.chapter_id,target.lesson_id,'Quiz de révision — Biosynthèse des protéines','Vérifiez votre maîtrise des acteurs, du code génétique, de la transcription et de la traduction.','medium',12,10,false,false
    where not exists (select 1 from public.quizzes q where q.lesson_id=target.lesson_id and q.title='Quiz de révision — Biosynthèse des protéines') returning id into quiz_uuid;
    if quiz_uuid is not null then
      with inserted_questions as (insert into public.quiz_questions (quiz_id,question,explanation,question_type,display_order,points,is_active) values
        (quiz_uuid,'Qu’est-ce qu’un codon ?','C’est un triplet de nucléotides lu sur l’ARNm.','single_choice',10,1,true),
        (quiz_uuid,'Quel est le rôle général de l’ARNm ?','Il transporte l’information copiée à partir de l’ADN vers le lieu de traduction.','single_choice',20,1,true),
        (quiz_uuid,'Quel type de liaison relie les acides aminés ?','Le cours appelle cette liaison une liaison peptidique.','single_choice',30,1,true),
        (quiz_uuid,'Quel événement marque la terminaison ?','Un codon stop met fin à l’assemblage de la chaîne polypeptidique.','single_choice',40,1,true)
      returning id,display_order)
      insert into public.quiz_answers (question_id,answer,is_correct,display_order)
      select inserted_questions.id,answers.answer,answers.is_correct,answers.display_order from inserted_questions join (values
        (10,'Un triplet de nucléotides de l’ARNm',true,10),
        (10,'Une protéine complète',false,20),
        (20,'Transporter l’information génétique copiée',true,10),
        (20,'Former seul une protéine',false,20),
        (30,'La liaison peptidique',true,10),
        (30,'La liaison ionique uniquement',false,20),
        (40,'La rencontre d’un codon stop',true,10),
        (40,'Le remplacement de U par T',false,20)
      ) as answers(question_order,answer,is_correct,display_order) on answers.question_order=inserted_questions.display_order;
    end if;
  end loop;
end;
$svt_terminal_lot3$;

do $citations_lot3$
declare citation_seed record; citation_subject_uuid uuid; citation_uuid uuid;
begin
  for citation_seed in select * from (values
      ('Français','Et bien, dansez maintenant.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable I, « La Cigale et la Fourmi »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire la conséquence littéraire de l’imprévoyance. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'travail', 'prévoyance']::text[],'Fable'),
      ('Français','La Fourmi n’est pas prêteuse : c’est là son moindre défaut.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable I, « La Cigale et la Fourmi »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire la construction d’un personnage et son jugement moral. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'personnification', 'morale']::text[],'Fable'),
      ('Français','Le monde est plein de gens qui ne sont pas plus sages.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable III, « La Grenouille qui se veut faire aussi grosse que le Bœuf »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire la généralisation satirique qui dépasse le seul récit animalier. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'satire', 'ambition']::text[],'Satire'),
      ('Français','Tout Bourgeois veut bâtir comme les grands Seigneurs.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable III, « La Grenouille qui se veut faire aussi grosse que le Bœuf »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire la critique de la vanité et de l’imitation sociale. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'satire', 'vanité']::text[],'Satire'),
      ('Français','Quittez les bois, vous ferez bien.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable V, « Le Loup et le Chien »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire l’opposition entre la promesse de confort et la liberté. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'liberté', 'dialogue']::text[],'Liberté'),
      ('Français','Je ne veux en aucune sorte ; et ne voudrais pas même à ce prix un trésor.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable V, « Le Loup et le Chien »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire le refus d’un avantage obtenu au prix de l’asservissement. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'liberté', 'choix']::text[],'Liberté'),
      ('Français','Lynx envers nos pareils, et Taupes envers nous.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable VII, « La Besace »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire la difficulté humaine à juger ses propres défauts. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'défaut', 'autocritique']::text[],'Morale'),
      ('Français','Nous nous pardonnons tout, et rien aux autres hommes.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable VII, « La Besace »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire la dissymétrie entre le jugement de soi et le jugement d’autrui. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'morale', 'autrui']::text[],'Morale'),
      ('Français','Quiconque a beaucoup vu, peut avoir beaucoup retenu.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable VIII, « L’Hirondelle et les petits Oiseaux »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire le lien entre expérience, mémoire et capacité d’anticipation. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'expérience', 'sagesse']::text[],'Prévoyance'),
      ('Français','Nous n’écoutons d’instincts que ceux qui sont les nôtres, et ne croyons le mal que quand il est venu.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable VIII, « L’Hirondelle et les petits Oiseaux »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire la critique de l’aveuglement face à un danger annoncé. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'prévoyance', 'morale']::text[],'Prévoyance'),
      ('Français','Je mange tout à loisir.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable IX, « Le Rat de Ville et le Rat des Champs »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire l’opposition entre une vie simple et un plaisir exposé à la crainte. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'bonheur', 'simplicité']::text[],'Bonheur'),
      ('Français','Fi du plaisir que la crainte peut corrompre.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable IX, « Le Rat de Ville et le Rat des Champs »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire la remise en cause d’un bonheur fondé sur le luxe mais privé de sécurité. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'crainte', 'plaisir']::text[],'Bonheur'),
      ('Français','La raison du plus fort est toujours la meilleure.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable X, « Le Loup et l’Agneau »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire l’ironie qui dénonce une justice confondue avec la force. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'justice', 'pouvoir']::text[],'Justice'),
      ('Français','Sans autre forme de procès.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable X, « Le Loup et l’Agneau »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire la brièveté finale qui souligne l’absence de procédure juste. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'procès', 'injustice']::text[],'Justice'),
      ('Français','Je plie, et ne romps pas.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable XXII, « Le Chêne et le Roseau »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire la métaphore de l’adaptation face à une force supérieure. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'résilience', 'métaphore']::text[],'Résilience'),
      ('Français','L’Arbre tient bon, le Roseau plie.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable XXII, « Le Chêne et le Roseau »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire le contraste narratif qui prépare la morale sur la souplesse. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'opposition', 'résilience']::text[],'Résilience'),
      ('Français','Il faut autant qu’on peut obliger tout le monde.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable XI, « Le Lion et le Rat »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire la valeur de l’obligation et de l’entraide entre des êtres inégaux. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'solidarité', 'morale']::text[],'Solidarité'),
      ('Français','On a souvent besoin d’un plus petit que soi.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable XI, « Le Lion et le Rat »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire la portée universelle d’une fable où le faible devient indispensable. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'entraide', 'humilité']::text[],'Solidarité'),
      ('Français','Qui prétend contenter tout le monde et son père est bien fou du cerveau.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable I du second recueil, « Le Meunier, son Fils et l’Âne »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire le caractère impossible de la recherche permanente d’approbation. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'opinion', 'jugement social']::text[],'Opinion'),
      ('Français','Qu’on dise quelque chose, ou qu’on ne dise rien ; j’en veux faire à ma tête.','Jean de La Fontaine','Fables choisies, mises en vers','Livre I, fable I du second recueil, « Le Meunier, son Fils et l’Âne »','https://fr.wikisource.org/wiki/Fables_de_La_Fontaine_(%C3%A9d._Barbin)','Cette citation éclaire l’affirmation d’une décision personnelle après la succession de critiques contradictoires. Elle peut être mobilisée pour identifier la portée morale, critique ou argumentative de la fable et justifier une interprétation par le texte.',array['La Fontaine', 'fable', 'autonomie', 'opinion']::text[],'Opinion'),
      ('Philosophie','L’homme est né libre, et partout il est dans les fers.','Jean-Jacques Rousseau','Du contrat social','Livre I, chapitre I','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner la tension entre liberté naturelle et ordre social. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'liberté', 'politique', 'contrat social']::text[],'Liberté'),
      ('Philosophie','L’ordre social est un droit sacré, qui sert de base à tous les autres.','Jean-Jacques Rousseau','Du contrat social','Livre I, chapitre I','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner le fondement conventionnel de l’ordre politique. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'ordre social', 'droit', 'politique']::text[],'Politique'),
      ('Philosophie','Le plus fort n’est jamais assez fort pour être toujours le maître, s’il ne transforme sa force en droit et l’obéissance en devoir.','Jean-Jacques Rousseau','Du contrat social','Livre I, chapitre III','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner la critique de la confusion entre la force matérielle et le droit légitime. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'force', 'droit', 'devoir']::text[],'Droit'),
      ('Philosophie','Céder à la force est un acte de nécessité, non de volonté.','Jean-Jacques Rousseau','Du contrat social','Livre I, chapitre III','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner la différence entre contrainte subie et consentement libre. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'force', 'volonté', 'liberté']::text[],'Aliénation'),
      ('Philosophie','Force ne fait pas droit.','Jean-Jacques Rousseau','Du contrat social','Livre I, chapitre III','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner la thèse concise qui refuse de fonder la justice sur la puissance. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'droit', 'force', 'justice']::text[],'Droit'),
      ('Philosophie','Renoncer à sa liberté c’est renoncer à sa qualité d’homme, aux droits de l’humanité, même à ses devoirs.','Jean-Jacques Rousseau','Du contrat social','Livre I, chapitre IV','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner l’incompatibilité entre liberté humaine et aliénation totale. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'liberté', 'humanité', 'esclavage']::text[],'Aliénation'),
      ('Philosophie','La guerre n’est donc point une relation d’homme à homme, mais une relation d’État à État.','Jean-Jacques Rousseau','Du contrat social','Livre I, chapitre IV','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner la distinction entre les personnes et les États dans l’analyse de la guerre. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'guerre', 'État', 'citoyen']::text[],'Politique'),
      ('Philosophie','Trouver une forme d’association qui défende et protège de toute la force commune la personne et les biens de chaque associé.','Jean-Jacques Rousseau','Du contrat social','Livre I, chapitre VI','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner le problème que le contrat social entend résoudre. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'association', 'contrat social', 'protection']::text[],'Contrat social'),
      ('Philosophie','Chacun de nous met en commun sa personne et toute sa puissance sous la suprême direction de la volonté générale.','Jean-Jacques Rousseau','Du contrat social','Livre I, chapitre VI','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner le principe de mise en commun des forces dans le pacte social. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'volonté générale', 'association', 'souveraineté']::text[],'Contrat social'),
      ('Philosophie','Les maisons font la ville mais les Citoyens font la Cité.','Jean-Jacques Rousseau','Du contrat social','Livre I, chapitre VI, note','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner la distinction entre un espace urbain et une communauté politique de citoyens. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'citoyen', 'cité', 'politique']::text[],'Citoyenneté'),
      ('Philosophie','Ce que l’homme perd par le contrat social, c’est sa liberté naturelle ; ce qu’il gagne, c’est la liberté civile.','Jean-Jacques Rousseau','Du contrat social','Livre I, chapitre VIII','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner la comparaison entre liberté naturelle et liberté civile. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'liberté naturelle', 'liberté civile', 'contrat']::text[],'Liberté'),
      ('Philosophie','L’obéissance à la loi qu’on s’est prescrite est liberté.','Jean-Jacques Rousseau','Du contrat social','Livre I, chapitre VIII','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner la définition de l’autonomie comme obéissance à une loi à laquelle on participe. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'loi', 'autonomie', 'liberté']::text[],'Autonomie'),
      ('Philosophie','La volonté générale peut seule diriger les forces de l’État selon la fin de son institution, qui est le bien commun.','Jean-Jacques Rousseau','Du contrat social','Livre II, chapitre I','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner la finalité collective attribuée à la volonté générale. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'volonté générale', 'bien commun', 'État']::text[],'Volonté générale'),
      ('Philosophie','La souveraineté n’étant que l’exercice de la volonté générale ne peut jamais s’aliéner.','Jean-Jacques Rousseau','Du contrat social','Livre II, chapitre I','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner le caractère inaliénable de la souveraineté dans la théorie rousseauiste. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'souveraineté', 'volonté générale', 'peuple']::text[],'Souveraineté'),
      ('Philosophie','Le pouvoir peut bien se transmettre, mais non pas la volonté.','Jean-Jacques Rousseau','Du contrat social','Livre II, chapitre I','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner la différence entre délégation d’un pouvoir et représentation de la volonté générale. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'pouvoir', 'volonté', 'souveraineté']::text[],'Souveraineté'),
      ('Philosophie','La volonté générale est toujours droite et tend toujours à l’utilité publique.','Jean-Jacques Rousseau','Du contrat social','Livre II, chapitre III','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner la distinction entre le principe du bien commun et les erreurs possibles des délibérations. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'volonté générale', 'utilité publique', 'politique']::text[],'Autonomie'),
      ('Philosophie','Il y a souvent bien de la différence entre la volonté de tous et la volonté générale.','Jean-Jacques Rousseau','Du contrat social','Livre II, chapitre III','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner la différence entre une somme d’intérêts privés et l’intérêt commun. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'volonté de tous', 'volonté générale', 'intérêt commun']::text[],'Volonté générale'),
      ('Philosophie','Il faut donc des conventions et des lois pour unir les droits aux devoirs et ramener la justice à son objet.','Jean-Jacques Rousseau','Du contrat social','Livre II, chapitre VI','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner le rôle des conventions et des lois dans l’organisation de la justice civile. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'convention', 'loi', 'justice']::text[],'Citoyenneté'),
      ('Philosophie','Les lois ne sont proprement que les conditions de l’association civile.','Jean-Jacques Rousseau','Du contrat social','Livre II, chapitre VI','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner la place de la loi dans la construction de l’association politique. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'loi', 'association civile', 'politique']::text[],'Loi'),
      ('Philosophie','Le Peuple soumis aux lois en doit être l’auteur.','Jean-Jacques Rousseau','Du contrat social','Livre II, chapitre VI','https://fr.wikisource.org/wiki/Du_contrat_social/%C3%89dition_1762/Texte_entier','Cette formulation permet d’examiner l’exigence de participation du peuple à l’élaboration de la loi. Elle aide l’élève à distinguer la thèse de Rousseau, ses enjeux politiques ou moraux et l’usage qu’il peut en faire dans une argumentation.',array['Rousseau', 'peuple', 'loi', 'citoyenneté']::text[],'Loi'),
      ('Histoire-Géographie','Toute personne a droit à la jouissance des droits et libertés reconnus et garantis dans la présente Charte sans distinction aucune.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 2','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise le principe de non-discrimination dans la jouissance des droits. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'droits', 'non-discrimination', 'égalité']::text[],'Non-discrimination'),
      ('Histoire-Géographie','Toutes les personnes bénéficient d’une totale égalité devant la loi.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 3','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise l’égalité juridique des personnes. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'égalité', 'loi', 'droits']::text[],'Égalité'),
      ('Histoire-Géographie','Toutes les personnes ont droit à une égale protection de la loi.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 3','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise la garantie égale de la protection juridique. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'protection', 'loi', 'État de droit']::text[],'Égalité'),
      ('Histoire-Géographie','La personne humaine est inviolable.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 4','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise la protection de la vie et de l’intégrité de la personne. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'vie', 'intégrité', 'dignité']::text[],'Droits fondamentaux'),
      ('Histoire-Géographie','Tout individu a droit au respect de la dignité inhérente à la personne humaine.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 5','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise l’interdiction des atteintes à la dignité humaine. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'dignité', 'esclavage', 'torture']::text[],'Droits fondamentaux'),
      ('Histoire-Géographie','Tout individu a droit à la liberté et à la sécurité de sa personne.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 6','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise la protection contre la privation arbitraire de liberté. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'liberté', 'sécurité', 'droits']::text[],'Libertés publiques'),
      ('Histoire-Géographie','Toute personne a droit à l’information.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 9','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise le rôle de l’accès à l’information dans la participation citoyenne. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'information', 'opinion', 'liberté']::text[],'Libertés publiques'),
      ('Histoire-Géographie','Tous les citoyens ont le droit de participer librement à la direction des affaires publiques de leur pays.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 13','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise la participation directe ou représentative aux affaires publiques. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'citoyenneté', 'participation', 'affaires publiques']::text[],'Citoyenneté'),
      ('Histoire-Géographie','Toute personne a le droit de travailler dans des conditions équitables et satisfaisantes.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 15','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise le travail comme droit social et condition de justice. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'travail', 'équité', 'droits sociaux']::text[],'Droits sociaux'),
      ('Histoire-Géographie','Toute personne a droit à l’éducation.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 17','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise l’éducation comme droit et condition de participation à la vie sociale. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'éducation', 'culture', 'droits sociaux']::text[],'Droits sociaux'),
      ('Histoire-Géographie','La famille est l’élément naturel et la base de la société.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 18','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise la place de la famille et les obligations de protection publique. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'famille', 'société', 'protection']::text[],'Société'),
      ('Histoire-Géographie','Tous les peuples sont égaux ; ils jouissent de la même dignité et ont les mêmes droits.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 19','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise l’égalité des peuples et le refus de toute domination. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'peuples', 'égalité', 'domination']::text[],'Peuples'),
      ('Histoire-Géographie','Tout peuple a droit à l’existence.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 20','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise le droit des peuples à exister et à choisir leur statut politique. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'peuple', 'existence', 'autodétermination']::text[],'Peuples'),
      ('Histoire-Géographie','Les peuples ont la libre disposition de leurs richesses et de leurs ressources naturelles.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 21','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise la souveraineté des peuples sur leurs ressources et ses enjeux de coopération. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'ressources', 'richesses', 'coopération']::text[],'Développement'),
      ('Histoire-Géographie','Tous les peuples ont droit à leur développement économique, social et culturel.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 22','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise le développement conçu dans ses dimensions économique, sociale et culturelle. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'développement', 'économie', 'culture']::text[],'Développement'),
      ('Histoire-Géographie','Les peuples ont droit à la paix et à la sécurité tant sur le plan national que sur le plan international.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 23','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise le lien entre paix, sécurité, solidarité et relations entre États. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'paix', 'sécurité', 'relations internationales']::text[],'Paix'),
      ('Histoire-Géographie','Tous les peuples ont droit à un environnement satisfaisant et global, propice à leur développement.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 24','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise la relation entre environnement et droit au développement. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'environnement', 'développement', 'peuples']::text[],'Paix'),
      ('Histoire-Géographie','Les États parties à la présente Charte ont le devoir de promouvoir et d’assurer, par l’enseignement, l’éducation et la diffusion, le respect des droits et des libertés.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 25','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise la responsabilité des États dans l’éducation aux droits et libertés. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'droits humains', 'éducation', 'État']::text[],'Citoyenneté'),
      ('Histoire-Géographie','Chaque individu a des devoirs envers la famille et la société, envers l’État et les autres collectivités légalement reconnues et envers la Communauté Internationale.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 27','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise l’articulation entre droits individuels et devoirs envers les communautés. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'devoirs', 'société', 'communauté internationale']::text[],'Société'),
      ('Histoire-Géographie','Chaque individu a le devoir de respecter et de considérer ses semblables sans discrimination aucune.','Organisation de l’unité africaine','Charte africaine des droits de l’homme et des peuples','Article 28','https://achpr.au.int/fr/charter/charte-africaine-des-droits-de-lhomme-et-des-peuples','Cet article de la Charte africaine précise la tolérance réciproque comme devoir social. Il permet de relier une norme de droits humains à des notions d’État, de citoyenneté, de développement ou de relations internationales.',array['Charte africaine', 'tolérance', 'respect', 'non-discrimination']::text[],'Non-discrimination'),
      ('Physique-Chimie','L’observation simple ne lui suffit pas.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Première partie, chapitre I','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence la limite d’une observation non prolongée par des moyens d’investigation. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'observation', 'investigation', 'science']::text[],'Observation'),
      ('Physique-Chimie','Dans le sens philosophique, l’observation montre et l’expérience instruit.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Première partie, chapitre I','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence la complémentarité entre constater un phénomène et tirer un enseignement expérimental. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'observation', 'expérience', 'méthode']::text[],'Observation'),
      ('Physique-Chimie','L’expérience n’étant en effet qu’un jugement, elle exige nécessairement comparaison entre deux choses.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Première partie, chapitre I','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence la nécessité de comparer des faits dans une expérience. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'expérience', 'comparaison', 'jugement']::text[],'Expérimentation'),
      ('Physique-Chimie','Tout se passe suivant des lois qui sont absolues, c’est-à-dire toujours normales et déterminées.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Première partie, chapitre I','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence l’idée de régularité des phénomènes naturels. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'loi', 'déterminisme', 'phénomène']::text[],'Déterminisme'),
      ('Physique-Chimie','L’observation est le point d’appui de l’esprit qui raisonne.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Première partie, chapitre I','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence le rôle des faits observés dans le raisonnement scientifique. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'observation', 'raisonnement', 'faits']::text[],'Raisonnement scientifique'),
      ('Physique-Chimie','L’observation est le point d’appui de l’esprit qui raisonne, et l’expérience le point d’appui de l’esprit qui conclut.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Première partie, chapitre I','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence l’articulation entre les faits observés, le raisonnement et une conclusion expérimentale. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'observation', 'expérience', 'raisonnement']::text[],'Raisonnement scientifique'),
      ('Physique-Chimie','L’homme ne peut dicter des lois à la nature.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Première partie, chapitre II','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence la nécessité de confronter les idées à la nature au lieu de les imposer. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'nature', 'critique', 'méthode']::text[],'Esprit critique'),
      ('Physique-Chimie','L’expérimentateur, plus modeste, pose au contraire son idée comme une question.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Première partie, chapitre II','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence la différence entre une hypothèse vérifiable et une affirmation dogmatique. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'hypothèse', 'question', 'expérimentateur']::text[],'Hypothèse'),
      ('Physique-Chimie','L’idée expérimentale est donc aussi une idée a priori, mais c’est une idée qui se présente sous la forme d’une hypothèse.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Première partie, chapitre II','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence le passage d’une intuition à une hypothèse soumise à vérification. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'idée', 'hypothèse', 'expérience']::text[],'Idée expérimentale'),
      ('Physique-Chimie','La raison à son tour doit être guidée par l’expérience.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Première partie, chapitre II','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence le contrôle empirique indispensable aux raisonnements sur la nature. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'raison', 'expérience', 'méthode']::text[],'Méthode scientifique'),
      ('Physique-Chimie','L’hypothèse expérimentale doit toujours être fondée sur une observation antérieure.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Première partie, chapitre II','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence l’ancrage d’une hypothèse dans un fait effectivement observé. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'hypothèse', 'observation', 'méthode']::text[],'Hypothèse'),
      ('Physique-Chimie','Une recherche expérimentale a pour point de départ une observation.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Troisième partie, chapitre I','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence l’observation comme point de départ possible d’une recherche. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'recherche', 'observation', 'démarche']::text[],'Recherche'),
      ('Physique-Chimie','Une recherche expérimentale a pour point de départ une hypothèse ou une théorie.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Troisième partie, chapitre I','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence l’autre point de départ possible : une hypothèse ou une théorie à éprouver. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'recherche', 'hypothèse', 'théorie']::text[],'Recherche'),
      ('Physique-Chimie','Il n’y a pas de mauvaises expériences.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Troisième partie, chapitre I','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence l’intérêt scientifique d’un résultat inattendu lorsqu’il est observé et interprété. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'expérience', 'résultat', 'découverte']::text[],'Expérimentation'),
      ('Physique-Chimie','Il y a un déterminisme absolu dans toutes les sciences.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Deuxième partie, chapitre I','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence la recherche de conditions nécessaires aux phénomènes étudiés. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'déterminisme', 'science', 'conditions']::text[],'Déterminisme'),
      ('Physique-Chimie','Le but que se propose la méthode expérimentale est le même partout ; il consiste à rattacher par l’expérience les phénomènes naturels à leurs conditions d’existence ou à leurs causes prochaines.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Deuxième partie, chapitre I','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence la recherche de causes prochaines et de conditions d’existence. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'causalité', 'conditions', 'méthode expérimentale']::text[],'Méthode scientifique'),
      ('Physique-Chimie','L’un et l’autre se proposent pour but commun de remonter à la cause prochaine des phénomènes qu’ils étudient.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Deuxième partie, chapitre I','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence l’unité de but entre l’étude des corps vivants et celle des corps bruts. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'cause', 'physique', 'biologie']::text[],'Causalité'),
      ('Physique-Chimie','Il n’y a pas des forces en opposition et en lutte les unes avec les autres ; dans la nature il ne saurait y avoir qu’arrangement et dérangement, qu’harmonie et désharmonie.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Deuxième partie, chapitre I','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence la recherche de relations organisées plutôt que l’invocation de forces mystérieuses. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'nature', 'harmonie', 'phénomène']::text[],'Causalité'),
      ('Physique-Chimie','La critique expérimentale ne doit porter que sur des faits et jamais sur des mots.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Troisième partie, chapitre I','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence la priorité donnée à la discussion des faits sur les querelles de vocabulaire. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'critique', 'faits', 'méthode']::text[],'Esprit critique'),
      ('Physique-Chimie','Toute l’initiative expérimentale est dans l’idée, car c’est elle qui provoque l’expérience.','Claude Bernard','Introduction à l’étude de la médecine expérimentale','Première partie, chapitre II','https://fr.wikisource.org/wiki/Introduction_%C3%A0_l%E2%80%99%C3%A9tude_de_la_m%C3%A9decine_exp%C3%A9rimentale','Cette formulation de Claude Bernard met en évidence le rôle moteur d’une idée dans la conception d’une expérience. Elle aide à distinguer observation, hypothèse, contrôle expérimental et interprétation raisonnée des faits.',array['Claude Bernard', 'idée', 'initiative', 'expérience']::text[],'Idée expérimentale')
  ) as seed(subject_name,quote_text,author,source_title,source_reference,source_url,pedagogical_explanation,keywords,theme) loop
    citation_uuid := null;
    select id into citation_subject_uuid from public.subjects where name=citation_seed.subject_name limit 1;
    if citation_subject_uuid is null then raise exception 'Matière Citations % introuvable.', citation_seed.subject_name; end if;
    insert into public.citations (subject_id,quote_text,author,source_title,source_reference,source_url,pedagogical_explanation,keywords,is_active,is_validated)
    select citation_subject_uuid,citation_seed.quote_text,citation_seed.author,citation_seed.source_title,citation_seed.source_reference,citation_seed.source_url,citation_seed.pedagogical_explanation,citation_seed.keywords,false,false
    where not exists (select 1 from public.citations c where c.subject_id=citation_subject_uuid and c.quote_text=citation_seed.quote_text and c.author=citation_seed.author)
    returning id into citation_uuid;
    if citation_uuid is not null then
      insert into public.citation_scopes (citation_id,level_id,series_id) select citation_uuid,lv.id,s.id from public.levels lv cross join public.series s where lv.name='Terminale' and s.name in ('A1','A2','C','D');
      insert into public.citation_themes (citation_id,theme) values (citation_uuid,citation_seed.theme);
    end if;
  end loop;
end;
$citations_lot3$;
