import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Redirect, useLocalSearchParams, useRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, View } from "react-native";
import { AppScreen } from "@/components/edutech/app-screen";
import { AdminField, AdminLoading, AdminNotice, AdminToggle } from "@/components/edutech/admin-ui";
import { PageHeader } from "@/components/edutech/page-header";
import { PrimaryButton } from "@/components/edutech/primary-button";
import { useSupabaseAuth } from "@/lib/auth/supabase-auth-provider";
import { AdminSubject, deleteAdminSubject, getAdminSubject, getSubjectDependencySummary, saveAdminSubject } from "@/lib/admin/course-admin-service";
import { useEduTheme } from "@/lib/edutech/theme-context";

export default function AdminSubjectEditor() {
  const { subjectId } = useLocalSearchParams<{ subjectId: string }>(); const router = useRouter(); const { isAdmin } = useSupabaseAuth(); const { colors } = useEduTheme(); const styles = useMemo(() => createStyles(colors), [colors]); const creating = subjectId === "new"; const [subject, setSubject] = useState<AdminSubject | null>(null); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [icon, setIcon] = useState(""); const [displayOrder, setDisplayOrder] = useState("0"); const [isActive, setIsActive] = useState(true); const [loading, setLoading] = useState(!creating); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (creating) return; setLoading(true); try { const item = await getAdminSubject(subjectId); if (!item) { setError("Cette matière n’est plus disponible."); return; } setSubject(item); setName(item.name); setDescription(item.description ?? ""); setIcon(item.icon ?? ""); setDisplayOrder(String(item.displayOrder)); setIsActive(item.isActive); } catch (cause) { setError(cause instanceof Error ? cause.message : "La matière n’a pas pu être chargée."); } finally { setLoading(false); } }, [creating, subjectId]);
  useEffect(() => { void load(); }, [load]);
  const persist = async (nextActive = isActive) => { setNotice(null); setError(null); setSaving(true); try { const saved = await saveAdminSubject({ name, description, icon, isActive: nextActive, displayOrder: Number(displayOrder) || 0 }, creating ? undefined : subjectId); setSubject(saved); setIsActive(saved.isActive); setNotice("Matière enregistrée dans Supabase."); if (creating) router.replace(`/administration/subjects/${saved.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "La matière n’a pas pu être enregistrée."); } finally { setSaving(false); } };
  const remove = async () => { if (!subject) return; setError(null); try { const dependencies = await getSubjectDependencySummary(subject.id); if (subject.isTestData) { setError("La matière de test existante est protégée contre la suppression."); return; } if (dependencies.offerings || dependencies.chapters) { Alert.alert("Suppression sécurisée", `Cette matière contient ${dependencies.offerings} association(s) et ${dependencies.chapters} chapitre(s). Pour éviter une perte de contenu, désactivez-la plutôt.`, [{ text: "Annuler", style: "cancel" }, { text: "Désactiver", onPress: () => void persist(false) }]); return; } Alert.alert("Supprimer cette matière ?", "Cette action est irréversible.", [{ text: "Annuler", style: "cancel" }, { text: "Supprimer", style: "destructive", onPress: async () => { try { await deleteAdminSubject(subject); router.replace("/administration/subjects"); } catch (cause) { setError(cause instanceof Error ? cause.message : "La suppression a échoué."); } } }]); } catch (cause) { setError(cause instanceof Error ? cause.message : "Les dépendances n’ont pas pu être vérifiées."); } };
  if (!isAdmin) return <Redirect href="/(tabs)" />;
  if (loading) return <AppScreen><AdminLoading label="Chargement de la matière…" /></AppScreen>;
  return <AppScreen edges={["top", "bottom", "left", "right"]}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.flex}><ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><PageHeader title={creating ? "Nouvelle matière" : "Modifier la matière"} subtitle="Les changements sont protégés par votre rôle Supabase." back /><View style={styles.form}><AdminField label="Nom" value={name} onChange={setName} placeholder="Ex. Littérature" /><AdminField label="Description" value={description} onChange={setDescription} multiline required={false} placeholder="Objectif ou présentation de la matière" /><AdminField label="Icône (facultatif)" value={icon} onChange={setIcon} required={false} placeholder="Ex. menu-book" /><AdminField label="Ordre d’affichage" value={displayOrder} onChange={setDisplayOrder} keyboardType="numeric" placeholder="0" /><AdminToggle label="Matière active" description="Une matière inactive reste administrable mais est masquée dans le parcours élève." value={isActive} onChange={setIsActive} />{subject?.isTestData ? <AdminNotice tone="warning">Cette matière contient des données de test protégées. Aucun contenu n’est modifié automatiquement.</AdminNotice> : null}{notice ? <AdminNotice tone="success">{notice}</AdminNotice> : null}{error ? <AdminNotice tone="error">{error}</AdminNotice> : null}<PrimaryButton label={creating ? "Créer la matière" : "Enregistrer les modifications"} onPress={() => void persist()} loading={saving} icon={<MaterialIcons name="save" size={19} color={colors.surface} />} />{!creating && subject ? <PrimaryButton label="Gérer les associations" variant="secondary" onPress={() => router.push(`/administration/subjects/${subject.id}/offerings`)} icon={<MaterialIcons name="tune" size={19} color={colors.primary} />} /> : null}{!creating && subject && !subject.isTestData ? <PrimaryButton label="Supprimer ou désactiver" variant="danger" onPress={() => void remove()} icon={<MaterialIcons name="delete-outline" size={19} color={colors.surface} />} /> : null}<Text style={styles.help}>La suppression définitive est bloquée lorsque des associations ou chapitres existent. L’inactivation est la solution recommandée pour préserver les contenus.</Text></View></ScrollView></KeyboardAvoidingView></AppScreen>;
}
const createStyles = (colors: ReturnType<typeof useEduTheme>["colors"]) => StyleSheet.create({ flex: { flex: 1 }, content: { paddingTop: 18, paddingBottom: 28 }, form: { gap: 13 }, help: { color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: "center", paddingHorizontal: 8 } });
